### ISSUE TITLE
Disclaimer is not configurable

### ISSUE THREAD

**Issue by Plack-Blague** [globaleaks/GlobaLeaks#3347] opened 2023-02-10 12:07 UTC
Good afternoon, after upgrading to the latest version [ Software version: 4.10.18 ] we are not able to activate or edit the disclaimer page so now we have the disclaiemr 'stuck', with old information that we cant edit or delete.

Any suggestion to solve this issue?

_Originally posted by @Plack-Blague in https://github.com/globaleaks/GlobaLeaks/issues/2625#issuecomment-1423140731_

**Comment by evilaliv3** [comment] 2023-02-10 12:16
Thank you for reporting this @Plack-Blague 

I just tested the latest release and i'm not able to reproduce the issue.

The disclaimer is always configurable as long that the platform is running with its DEFAULT mode.

Are you the administrator of your system? do you know in which mode it is configured the system that you are using?

**Comment by Plack-Blague** [comment] 2023-02-10 16:19
Good afternoon,

 

We used the online demo available on the website to check the issue and the Disclaimer option is not available there as well:



 I

 

The location of it changed? Not under settings?

 

What do you mean with “DEFAULT mode”. We personalized the portal to our needs and image.

 

Yes, I’m the administrator. No, I don’t know which mode its configured on my system? How can I know it and change it, if needed?

 

Best regards

BP

**Comment by Plack-Blague** [comment] 2023-02-10 16:22
Good afternoon,
We used the online demo available on the website to check the issue and the Disclaimer option is not available there as well:

![image](https://user-images.githubusercontent.com/77781694/218142730-ad948093-ffee-4b6a-90a2-552ce5d069a1.png)

The location of it changed? Not under settings?

What do you mean with “DEFAULT mode”. We personalized the portal to our needs and image.

Yes, I’m the administrator. No, I don’t know which mode its configured on my system? How can I know it and change it, if needed?



Best regards

BP

**Comment by evilaliv3** [comment] 2023-02-10 16:34
Thank you.

Yes the disclaimer when configurable appear in the Settings interface.
On our demo, that uses the mode "DEMO", the disclaimer is not configurable.
If you could provide a link to your platform i may try to understand which configuration you are using and why the disclaimer option is not available

**Comment by Plack-Blague** [comment] 2023-02-10 16:41
Thank you for your quick reply,

Here it goes: https://whistleblowing.inova.business/

Ill be waiting for your feedback.
Best Regards

**Comment by evilaliv3** [comment] 2023-02-10 16:47
Thank you @Plack-Blague 

It seems that you or an other administrators have configured your system in "DEMO" mode and this is why the disclaimer appears not confgurable.
Log on the main platform, access the "Sites" management panel and reconfigure this site in "DEFAULT" mode.

I would like to make you aware that by removing the "Powered by GlobaLeaks" statement in the footer you are currently incurring in the violation of the software [LICENSE](https://github.com/globaleaks/GlobaLeaks/blob/main/LICENSE)
We kindly request to restore the software attribution statement that is required to continuing using the software.

**Comment by evilaliv3** [comment] 2023-02-10 17:07
Yes, I guess someone in your team had plaid with the multitenancy feature
in the past and enabled the demo option.

Now that you solves the issue you may proceed disabling the multisite
option again.

**Comment by Plack-Blague** [comment] 2023-02-10 17:09
Good afternoon,

I didnt even need to change the option ON, since just 'ticking' without saving allow me to access the menu.

Thank you again and have a great weekend.

**Comment by evilaliv3** [comment] 2023-02-10 17:12
Ok, thank you for confirming this.

Closing the ticket then.

Please note that with reference to the LICENSE you have actually 30 days for restoring the software attribution to continue to be entitled to use the software. Thank you if you could prioritize this activity.

**Closed by evilaliv3** 2023-02-10 17:12 UTC
