### ISSUE TITLE
Can't change or add PGP key

### ISSUE THREAD

**Issue by infosquatter** [globaleaks/GlobaLeaks#1332] opened 2015-07-16 23:05 UTC
This time the error log is different:

2015-07-16 22:55:23+0000 [-] [http] 500 PUT &#47;admin&#47;receiver&#47;8d40904c-bb7d-431c-a139-c8503d2737fc (127.0.0.1) 146.71ms
2015-07-16 22:55:23+0000 [GLHTTPConnection,29,127.0.0.1] &quot;[!] Critical, OS error in operating with GnuPG home: [Errno 13] Permission denied: &#39;&#47;dev&#47;shm&#47;globaleaks&#47;gnupg&#47;k2ottx6Q&#39;&quot;
2015-07-16 22:55:23+0000 [-] &quot;[!] Uncaught exception &lt;type &#39;exceptions.OSError&#39;&gt; [Errno 13] Permission denied: &#39;&#47;dev&#47;shm&#47;globaleaks&#47;gnupg&#47;k2ottx6Q&#39; &lt;traceback object at 0x4f29998&gt;&quot;
2015-07-16 22:55:23+0000 [-] [ ] [Errno 13] Permission denied: &#39;&#47;dev&#47;shm&#47;globaleaks&#47;gnupg&#47;k2ottx6Q&#39;

**Comment by fpietrosanti** [comment] 2015-07-17 06:11
@infosquatter Is it possible that you have a broken apparmor profile for some reason?

a) Please issue command "ls -la /dev/shm/gl*" and paste here output

b) Please issue command "sudo service apparmor reload" and try to repeat the operations

**Comment by infosquatter** [comment] 2015-07-18 00:16
This is the ourput of "ls -la /dev/shm/gl*":

-rw------- 1 globaleaks globaleaks 200  aeskey-Z9psnNdv6vTwjlCD
-rw------- 1 globaleaks globaleaks 179  aeskey-zZaLnlNE8yJ8M8wU
drwx------ 2 root       root        40  gnupg

I tried "chown -R globaleaks gnupg", and it seems the issue is solved.


Fabio (naif) Pietrosanti:

**Comment by vecna** [comment] 2015-07-27 13:56
ok so the error is gnupg directory as 'root' and not as globaleaks. why that would ever happen ?

**Comment by evilaliv3** [comment] 2015-08-01 17:42
not reproducible. closing the ticket for now.

**Comment by fpietrosanti** [comment] 2015-08-01 18:13
@evilaliv3 there's a bug in a unhanded exception to be handled with a properly formatted log:
2015-07-16 22:55:23+0000 [-] "[!] Uncaught exception <type 'exceptions.OSError'> [Errno 13] Permission denied: '/dev/shm/globaleaks/gnupg/k2ottx6Q' <traceback object at 0x4f29998>"
2015-07-16 22:55:23+0000 [-] [ ] [Errno 13] Permission denied: '/dev/shm/globaleaks/gnupg/k2ottx6Q'

**Comment by vecna** [comment] 2015-08-03 07:56
it is happen to me doing, from an old setup, remove, update, install.
the privileges in /dev/shm/globaleaks are ok, but the one in gnupg/ are marked as root.root

when globaleaks runs in it, permission denied. to solve, chown -R globaleaks.globaleaks, but I don't know the reason why happen.

long term solutions:

  * in uninstall script can be removed /dev/shm/globaleaks,
  * in the install script the privileges can be forced in post-install.

**Comment by fpietrosanti** [comment] 2015-08-03 08:05
Easier fix, already happening for other stuff:
- fix/restore all permissions from init script at each start/stop

**Comment by evilaliv3** [comment] 2015-08-03 08:19
right suggestion, right know we do the fix but not recursive inside /dev/shm/globaleaks:
https://github.com/globaleaks/GlobaLeaks/blob/master/backend/bin/gl-fix-permissions#L22

**Comment by evilaliv3** [comment] 2015-08-03 08:22
the same apply to /var/run/globaleaks.

i would not change instead anything recursively inside /var/globaleaks.

**Comment by evilaliv3** [comment] 2015-08-03 09:25
fixed!

**Closed by evilaliv3** 2015-08-03 09:25 UTC
Labels: C: GLBackend, OTF-D1.5: Support installation with debian package only, OTF-D1: Easier Installation, Type: bug
