### ISSUE TITLE
Unhandled exception in     An error occurred in an `OpenSSL.crypto` API.

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2083] opened 2017-09-15 16:19 UTC
**Current behavior**
This exception is unhandled

Platform: xxx ()
Version: 2.72.3

OpenSSL.crypto.Error 
    An error occurred in an `OpenSSL.crypto` API.
    

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/base.py", line 42, in run
    yield threads.deferToThread(self.operation)

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/x509_cert_check_sched.py", line 40, in operation
    self.cert_expiration_checks()

  File "/usr/lib/python2.7/dist-packages/globaleaks/orm.py", line 83, in __call__
    return self.run(self._wrap, self.method, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/orm.py", line 128, in run
    return function(*args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/orm.py", line 103, in _wrap
    result = function(self.instance, store, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/x509_cert_check_sched.py", line 73, in cert_expiration_checks
    cert = load_certificate(FILETYPE_PEM, GLSettings.memory_copy.private.https_cert)

  File "/usr/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 1511, in load_certificate
    _raise_current_error()

  File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)

Error: [('PEM routines', 'PEM_read_bio', 'no start line')]

**Comment by NSkelsey** [comment] 2017-09-18 08:37
This error is getting generated by a platform that has HTTPS enabled and an invalid HTTPS certificate loaded. It is not clear how the platform arrived in this state. With a normal submission of a certificate that is empty or poorly formatted, the same exception will be raised on its submission and the admin supplied certificate will be rejected. Maybe a delete, or the reset functionality incorrectly left empty certificates while `private.https_enabled` remained set to `True`.

**Comment by fpietrosanti** [comment] 2017-09-18 08:42
If it trigger when the certificate it's loaded by underlying OpenSSL subsystem, maybe we could add the "validate_function_whatsoever()" before we pass it to the OpenSSL subsystem, to avoid triggering that error, managing it at application layer

**Comment by NSkelsey** [comment] 2017-09-18 08:48
So, this error is occuring in a job. and i'll add the validation of the loaded configuration before executing this job. Its just funky that validation we do on submission of the certificate did not catch this error.

**Comment by NSkelsey** [comment] 2017-09-22 14:59
An interesting log line from this error reveals that the X509 Cert Check jobs is always failing on this machine due to the same low and high response times.

From `/var/globaleaks/log/globaleaks.log`

```
2017-09-22 10:22:12+0000 [-] Starting factory &lt;txsocksx.client.SOCKS5ClientFactory instance at 0x7f3db1851248&gt;
2017-09-22 10:22:12+0000 [-] [E] Job X509 Cert Check died with runtime 3.0000 [low: 3.0000, high: 3.0000]
2017-09-22 10:22:12+0000 [-] Traceback (most recent call last):
2017-09-22 10:22:12+0000 [-]   File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;globaleaks&#47;jobs&#47;base.py&quot;, line 42, in run
2017-09-22 10:22:12+0000 [-]     yield threads.deferToThread(self.operation)
2017-09-22 10:22:12+0000 [-]   File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;python&#47;threadpool.py&quot;, line 246, in inContext
2017-09-22 10:22:12+0000 [-]     result = inContext.theWork()
2017-09-22 10:22:12+0000 [-]   File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;python&#47;threadpool.py&quot;, line 262, in &lt;lambda&gt;
2017-09-22 10:22:12+0000 [-]     inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
2017-09-22 10:22:12+0000 [-]   File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;python&#47;context.py&quot;, line 118, in callWithContext
2017-09-22 10:22:12+0000 [-]     return self.currentContext().callWithContext(ctx, func, *args, **kw)
2017-09-22 10:22:12+0000 [-]   File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;python&#47;context.py&quot;, line 81, in callWithContext
2017-09-22 10:22:12+0000 [-]     return func(*args,**kw)
2017-09-22 10:22:12+0000 [-]   File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;globaleaks&#47;jobs&#47;x509_cert_check_sched.py&quot;, line 40, in operation
2017-09-22 10:22:12+0000 [-]     self.cert_expiration_checks()
2017-09-22 10:22:12+0000 [-]   File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;globaleaks&#47;orm.py&quot;, line 83, in __call__
2017-09-22 10:22:12+0000 [-]     return self.run(self._wrap, self.method, *args, **kwargs)
2017-09-22 10:22:12+0000 [-]   File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;globaleaks&#47;orm.py&quot;, line 128, in run
2017-09-22 10:22:12+0000 [-]     return function(*args, **kwargs)
2017-09-22 10:22:12+0000 [-]   File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;globaleaks&#47;orm.py&quot;, line 103, in _wrap
2017-09-22 10:22:12+0000 [-]     result = function(self.instance, store, *args, **kwargs)
2017-09-22 10:22:12+0000 [-]   File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;globaleaks&#47;jobs&#47;x509_cert_check_sched.py&quot;, line 73, in cert_expiration_checks
2017-09-22 10:22:12+0000 [-]     cert = load_certificate(FILETYPE_PEM, GLSettings.memory_copy.private.https_cert)
2017-09-22 10:22:12+0000 [-]   File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;OpenSSL&#47;crypto.py&quot;, line 1511, in load_certificate
2017-09-22 10:22:12+0000 [-]     _raise_current_error()
2017-09-22 10:22:12+0000 [-]   File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;OpenSSL&#47;_util.py&quot;, line 48, in exception_from_error_queue
2017-09-22 10:22:12+0000 [-]     raise exception_type(errors)
2017-09-22 10:22:12+0000 [-] Error: [(&#39;PEM routines&#39;, &#39;PEM_read_bio&#39;, &#39;no start line&#39;)]
2017-09-22 10:22:12+0000 [-] [E] Unhandled exception raised:
2017-09-22 10:22:12+0000 [-] [E] OpenSSL.crypto.Error &#92;n    An error occurred in an `OpenSSL.crypto` API.&#92;n    &#92;n&#92;nTraceback (most recent call last):&#92;n&#92;n  File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;globaleaks&#47;jobs&#47;base.py&quot;, line 42, in run&#92;n    yield threads.deferToThread(self.operation)&#92;n&#92;n  File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;python&#47;threadpool.py&quot;, line 246, in inContext&#92;n    result = inContext.theWork()&#92;n&#92;n  File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;python&#47;threadpool.py&quot;, line 262, in &lt;lambda&gt;&#92;n    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)&#92;n&#92;n  File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;python&#47;context.py&quot;, line 118, in callWithContext&#92;n    return self.currentContext().callWithContext(ctx, func, *args, **kw)&#92;n&#92;n  File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;python&#47;context.py&quot;, line 81, in callWithContext&#92;n    return func(*args,**kw)&#92;n&#92;n  File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;globaleaks&#47;jobs&#47;x509_cert_check_sched.py&quot;, line 40, in operation&#92;n    self.cert_expiration_checks()&#92;n&#92;n  File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;globaleaks&#47;orm.py&quot;, line 83, in __call__&#92;n    return self.run(self._wrap, self.method, *args, **kwargs)&#92;n&#92;n  File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;globaleaks&#47;orm.py&quot;, line 128, in run&#92;n    return function(*args, **kwargs)&#92;n&#92;n  File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;globaleaks&#47;orm.py&quot;, line 103, in _wrap&#92;n    result = function(self.instance, store, *args, **kwargs)&#92;n&#92;n  File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;globaleaks&#47;jobs&#47;x509_cert_check_sched.py&quot;, line 73, in cert_expiration_checks&#92;n    cert = load_certificate(FILETYPE_PEM, GLSettings.memory_copy.private.https_cert)&#92;n&#92;n  File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;OpenSSL&#47;crypto.py&quot;, line 1511, in load_certificate&#92;n    _raise_current_error()&#92;n&#92;n  File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;OpenSSL&#47;_util.py&quot;, line 48, in exception_from_error_queue&#92;n    raise exception_type(errors)&#92;n&#92;nError: [(&#39;PEM routines&#39;, &#39;PEM_read_bio&#39;, &#39;no start line&#39;)]&#92;n
2017-09-22 10:22:15+0000 [-] Stopping factory &lt;txsocksx.client.SOCKS5ClientFactory instance at 0x7f3db1851248&gt;
```

What follows a theory on how this exception is generated and why it has evaded reproduction.

When HTTPS is configured via the AcmeHandlers the memory copy is never updated with the newly generated certificates, so when the X509 job goes looking for them, they are still in their uninitialized state.

There are two things to do here 1) Refresh the memory_copy after a successful acme run in `db_acme_cert_issuance` or in the handler at `AcmeHandler.put` 2) Use the store to fetch the certificates in `X509Certcheck.operation` instead of using the memory_copy.

Point 1) is slightly out side of the style for our handlers because in that file i've tried to only update the memory_copy vars that at the time were changed, instead of doing one mass refresh. I think in this case I'll continue to follow this style as a model for the rest of the app to use in the future.

Point 2) is an easy win because there is no serious performance hit for adding another query that runs once every 3 days.

**Comment by evilaliv3** [comment] 2017-09-22 15:11
fine for both the points.

a lot probably would change in relation to 1 and the multitenancy but for the moment what you are proposing is totally correct.

**Comment by NSkelsey** [comment] 2017-09-22 16:11
See devel stack exception list for a bunch of emails confirming the hypothesis all from 22/9/17.

**Comment by NSkelsey** [comment] 2017-09-22 17:26
Okay, 581c708 should provide the solution for this specific issue with 37e101f providing some quick fixes.

It should be noted that our test coverage of `jobs/x509_cert_check_sched.py` is very low.

**Comment by NSkelsey** [comment] 2017-09-22 17:29
Closing for now. Its fine to reopen if the issue reappears in versions past `v2.72.4`

**Closed by NSkelsey** 2017-09-22 17:29 UTC
Labels: F: Exception Notification, T: Bug
