### ISSUE TITLE
Glyphicon's not loading in tor 5.5 in some environments

### ISSUE THREAD

**Issue by danilort** [globaleaks/GlobaLeaks#1680] opened 2016-05-27 10:30 UTC
The glyphicon is not visible, using TorBrowser.
Try also on  https://demo.globaleaks.org/#/

TorBrowser 5.5.5 (FF 38.8)
Globaleaks  2.61.12

![2016-05-27_121335](https://cloud.githubusercontent.com/assets/16148184/15605488/9704b146-2406-11e6-81e2-aacb2753f6bd.png)

Danilo

**Comment by NSkelsey** [comment] 2016-05-27 11:11
Hi Danilo,

Thanks for reporting the issue. 

I have tried the reproducing the issue on Windows 8.1 with Tor 5.5.5 and the glyphicons display.

Can you share additional information about your environment?

**Comment by danilort** [comment] 2016-05-27 13:11
SOLVED.
When I access from my company INTRAnet, the icons are missing (but in previous versions of GL, I saw icons).
When I access from external internet, the icons are ok.

Sorry
Danilo

**Comment by NSkelsey** [comment] 2016-05-27 13:20
Great!

I wonder why an intranet would have any effect on the resource. The glyphicons are loaded via a base64 encoded URI maybe there is a cross-origin violation going on? 

I'd like to leave this issue open until we get an answer to that question.

@danilort could you take a quick look into it?

**Comment by danilort** [comment] 2016-05-27 13:31
Please, see #1603. 
Is there a relationship?

**Comment by evilaliv3** [comment] 2016-05-27 14:41
i would say no @danilort 

that ticket addressed the following topic:
- since always we avoid files to be cached by Internet Explorer
- we just discovered that on this situation glyphicons where not loaded by IE because the browser in case caching is disabled is no able to reach downloaded files.

to change this and improve the optimization of the platform now, the glyphicons (that are contained in a font file) are inlined inside the css using datauri.

the above makes for me so strange the possibility that you have different failures depending on the host because the font is inline inside the css file.

if you look in the browser resources do you get any failure?

**Comment by danilort** [comment] 2016-05-30 06:31
see 2 attachment:


![2016-05-30_083047](https://cloud.githubusercontent.com/assets/16148184/15641399/e4b1d77a-2640-11e6-8c0c-be3ca2553915.png)


[ERRORI.txt](https://github.com/globaleaks/GlobaLeaks/files/288922/ERRORI.txt)

**Comment by fpietrosanti** [comment] 2016-05-30 06:38
Interesting, the "downloadable font: not usable by platform" is reported also on Firefox bug tracker:
https://bugzilla.mozilla.org/show_bug.cgi?id=1228799
https://bugzilla.mozilla.org/show_bug.cgi?id=723482

**Comment by danilort** [comment] 2016-05-30 07:04
I confirm. I get the same error with:
https://bugzilla.mozilla.org/attachment.cgi?id=8728664

I use Win10 Pro.

**Comment by fpietrosanti** [comment] 2016-06-02 16:54
Tor Browser 6 is out!
https://blog.torproject.org/blog/tor-browser-60-released

Does the problem reproduce also with latests Tor Browser based on Firefox 45?

**Comment by evilaliv3** [comment] 2016-06-02 20:21
i think i've understood the issue; it should be related to direct2d/direct3d and probably in relations to nvidia cards:
https://bugzilla.mozilla.org/show_bug.cgi?id=1228799#c26
https://bugzilla.mozilla.org/show_bug.cgi?id=1228799#c28

@danilort lookin at this two comments in the mozzilla bugtracker do you confirm it?

**Comment by danilort** [comment] 2016-06-06 09:37
TorBrowser 6 not solve.
The problem is hardware acceleration (confirmed).
See attachments.

[PROVE ESEGUITE.pdf](https://github.com/globaleaks/GlobaLeaks/files/300080/PROVE.ESEGUITE.pdf)

Danilo

**Comment by evilaliv3** [comment] 2016-06-06 10:04
ok now that the issue is confirmed we can try to notify it to bootstrap developer in order to understand it in detail and see if that is solvable by them or not.

alternatives could be to go for different implementations of icons if they do not have such issues.

@danilort when you have time could you please try to see if this page loads?

http://fontawesome.io/icons/

it is the font-awesome page for the showcase of their icons.

the page should look like these:
![screenshot from 2016-06-06 12 03 53](https://cloud.githubusercontent.com/assets/217034/15818636/d244bb54-2bde-11e6-8af1-d582c2ce4a01.png)

**Comment by evilaliv3** [comment] 2016-06-06 10:04
thank you so much @danilort for all your help.

**Comment by danilort** [comment] 2016-06-06 10:33
![2016-06-06_122852](https://cloud.githubusercontent.com/assets/16148184/15819229/3df28220-2be2-11e6-9e20-6a946cd5e7b8.png)

----------------
Firefox crashes When using hardware acceleration
https://lists.torproject.org/pipermail/tor-bugs/2014-January/052074.html

Tor crashes when hardware acceleration option is turned on
https://www.reddit.com/r/TOR/comments/40btg2/tor_crashes_when_hardware_acceleration_option_is/

Firefox crashes When using hardware acceleration
https://trac.torproject.org/projects/tor/ticket/10531

**Comment by danilort** [comment] 2016-06-06 13:00
Le icone di ICONIC si vedono anche con TorBrowser.
Esempio: http://www.html.it/articoli/37270/esempi/esempio4.html

Danilo

**Comment by evilaliv3** [comment] 2016-06-07 10:11
thanks @danilort 

the bootstrap peaople are not aware of the issue and as they already removed the glyphicons from bootstrap4 they are not going to help directly.

your suggestion on the iconic library is right but for such a change we would have to assess first eventually all the browser compatibility.

i'm not investigating a different solution;
bootstrap includes more than one kind of css: svg, woff, woff2, ttf

i would kindly ask you to try to visit the following pages and see if one of these opens correctly on your PC:

http://www.evilaliv3.org/icons/woff/
http://www.evilaliv3.org/icons/woff2/
http://www.evilaliv3.org/icons/svg/
http://www.evilaliv3.org/icons/ttf/

the reason is that given the fact that we are targetting specific browsers (e.g. IE>11, firefox > x, chrome > 0, supposing svg will work on all we can include only the svg with the benefit for all the project also in matter of performance of the first load.

thank you so much for all this great feedback

**Comment by evilaliv3** [comment] 2016-06-07 10:39
ok after a better analyisis i think the only one that give compatibility over all the different browsers, and will so continue to work with all in full compatibility is the WOFF format.

i've already setup a demo globaleaks server that is only including that, this way we could all see on different platform if it behave well: https://demo.globaleaks.org/#/

**Comment by danilort** [comment] 2016-06-07 12:42
[woff.pdf](https://github.com/globaleaks/GlobaLeaks/files/302559/woff.pdf)
[woff2.pdf](https://github.com/globaleaks/GlobaLeaks/files/302560/woff2.pdf)
[svg.pdf](https://github.com/globaleaks/GlobaLeaks/files/302561/svg.pdf)
[ttf.pdf](https://github.com/globaleaks/GlobaLeaks/files/302563/ttf.pdf)

But the pages do not contain icons. They are all images PNG

Danilo

**Comment by danilort** [comment] 2016-06-07 12:43
https://demo.globaleaks.org/#/

![2016-06-07_143751](https://cloud.githubusercontent.com/assets/16148184/15857917/29fd1762-2cbe-11e6-85a3-c0dabc59e6e7.png)

Danilo

**Comment by evilaliv3** [comment] 2016-06-07 12:48
you are right danilo; i wrongly pasted you the link without the '/components' subpath.

the ones i'm interested in are:
http://www.evilaliv3.org/icons/woff/components/
http://www.evilaliv3.org/icons/woff2/components/
http://www.evilaliv3.org/icons/eot/components/
http://www.evilaliv3.org/icons/svg/components/

but sadly you already configmred me that the woff (that is the only one more compatible) is not working anyhow.

**Comment by danilort** [comment] 2016-06-07 13:05
alcune si vedono, ma molte no.

![warning](https://cloud.githubusercontent.com/assets/16148184/15858491/0da4731e-2cc1-11e6-95d2-f7c853fb7653.png)


![woff](https://cloud.githubusercontent.com/assets/16148184/15858495/105d630e-2cc1-11e6-82c5-d6df8778aeea.png)


![woff2](https://cloud.githubusercontent.com/assets/16148184/15858499/12cdb5d0-2cc1-11e6-9d59-8ccaa1e3cc6b.png)


![eot](https://cloud.githubusercontent.com/assets/16148184/15858500/16a4b622-2cc1-11e6-976b-def86debc1a1.png)


![svg](https://cloud.githubusercontent.com/assets/16148184/15858503/1b8724b8-2cc1-11e6-8b8c-bbe87679dfa5.png)

**Comment by danilort** [comment] 2016-06-07 13:15
FF46 - hardware acceleration = ON

![ff-on](https://cloud.githubusercontent.com/assets/16148184/15858778/943c0d14-2cc2-11e6-82d5-1c718b42c43a.png)



FF46 - hardware acceleration = OFF

![ff46-off](https://cloud.githubusercontent.com/assets/16148184/15858774/91b5fdd4-2cc2-11e6-9ead-fdc4adec9727.png)

**Comment by NSkelsey** [comment] 2017-07-06 11:19
Closing as bug in browser/OS specific rendering of font.

**Closed by NSkelsey** 2017-07-06 11:19 UTC
Labels: T: Bug
