### ISSUE TITLE
Support button redirecting to whistleblower's side

### ISSUE THREAD

**Issue by danielvaknine** [globaleaks/GlobaLeaks#3727] opened 2023-10-26 13:45 UTC
### What version of GlobaLeaks are you using?

4.13.15

### What browser(s) are you seeing the problem on?

Chrome

### What operating system(s) are you seeing the problem on?

macOS

### Describe the issue

When logged in as a recipient and clicking the support button in the top right corner, the "background" of the screen switches to the whistleblower's side. Seems like a small bug

**Comment by evilaliv3** [comment] 2023-10-26 15:00
Thank you @danielvaknine 

This is a regression introduced by me and  @gingerlime while working on https://github.com/orgs/globaleaks/discussions/3633

commit: https://github.com/globaleaks/GlobaLeaks/commit/24ffd5a83b3614a88f92e1de597c107b5f070fea

@gingerlime @http-alba: i think in the short term i will need to just rollback the improvements of SEO made, since functionality is of course to be prioritized over SEO.

@gingerlime: i think that adding the href= on the link impacts the data-ng-click functionality. Later on to address the improvement you made we should probably cosider to find a replacemenet for the <a> html tag.

**Comment by gingerlime** [comment] 2023-10-26 15:07
sorry about that. I’m not that familiar with angular, but I hope there’s a way to have semantic hrefs that work with it. Agree that functionality is more important of course.

**Comment by evilaliv3** [comment] 2023-10-26 17:54
No worris @gingerlime ! it part of the game writing patches and new bugs! :)

I should have fixed all with my last commit by replacing url links of type <a> with html tags of type <span> on which we can keep just the data-ng-link without having any impact on SEO

Closing the ticket as this patch will land in the next minor release in few days.

**Closed by evilaliv3** 2023-10-26 17:54 UTC
Labels: T: Bug, C: Client
