### ISSUE TITLE
Corrupted zip file in 'download all files' feature when file names in zip are cyrillic

### ISSUE THREAD

**Issue by kyrylkov** [globaleaks/GlobaLeaks#1295] opened 2015-06-14 10:10 UTC
![screen shot 2015-06-13 at 15 08 23](https://cloud.githubusercontent.com/assets/6225870/8148154/8bd74a86-1296-11e5-9ddc-0eeb3fac6233.png)

**Comment by evilaliv3** [comment] 2015-06-20 23:17
Okay the issue is fixed and will be released in the next stable release pushded tomorrow or the day after.

@fpietrosanti: the issue afted both zipfile/tar/targz/bz2.
currently is only fixed for zipfiles that now implemente a complete unittesting and the test use charactes took from the internationalization system we have so that the test is more effective.
in the meantime i've removed tar/targz/tarbz2 code that is buggy and not exposed.

\cc @vecna

**Comment by fpietrosanti** [comment] 2015-06-21 07:38
Less code = more tested code = love

Btw the zip logic need anyhow to be moved client side as soon as we do integration of end-to-end Encryption.

**Comment by evilaliv3** [comment] 2015-06-21 07:49
when answering by email please remove the shitty spammy text an leave only your reply :)

**Comment by evilaliv3** [comment] 2015-06-21 08:07
anyhow its' not real that zips would become not useful when end2end encryption will be in place.

in fact as already exposed it would be always usefult to have a simple api /files where to get all together the files maybe zipped without compression(stored mode, basically a tar if applying compression would result simply in waste of resources) or with compression (deflated mode)

**Comment by evilaliv3** [comment] 2015-06-22 13:17
with commit https://github.com/globaleaks/GlobaLeaks/commit/5b4c9944854b0fd5ade040fef05a2b4e7da7b19f the issue is finally fixed.

before:
![screenshot from 2015-06-22 15 02 17](https://cloud.githubusercontent.com/assets/217034/8282504/9719d452-18f1-11e5-9e68-c78352293f6d.png)

after:
![screenshot from 2015-06-22 15 02 45](https://cloud.githubusercontent.com/assets/217034/8282509/9d6b4200-18f1-11e5-9fd5-33e22062c3c0.png)

i had simply to reuse some python2.7/3.4 code o zipfile.py to update spideroak version that was probably starting from a previous version.

**Closed** 2015-06-22 13:34 UTC
Labels: C: GLBackend, F: AdopterRequest, Type: bug

**Comment by evilaliv3** [comment] 2015-06-22 20:53
@kyrylkov can you please retest if the release 2.60.82 is fixing the issue also for your setup?

**Comment by kyrylkov** [comment] 2015-06-27 20:17
@evilaliv3  Everything works as expected

**Comment by evilaliv3** [comment] 2015-06-28 08:57
great @kyrylkov 

in relation to this i'm now releaseing a package that fixes https://github.com/globaleaks/GlobaLeaks/issues/1316. it will be out in an hour.
