### ISSUE TITLE
tor2web instructions don't work

### ISSUE THREAD

**Issue by gszathmari** [globaleaks/GlobaLeaks#1711] opened 2016-06-30 14:05 UTC
I was following the instructions on https://github.com/globaleaks/GlobaLeaks/wiki/Installing-GlobaLeaks-Tor2web-Letsencrypt 

When I am connecting with my browser, I get the default Tor2Web page instead of the actual Globaleaks main page

<img width="973" alt="screen shot 2016-06-30 at 23 56 09" src="https://cloud.githubusercontent.com/assets/4806014/16491014/7563e7b2-3f1f-11e6-96ee-406acf5df02a.png">

**Comment by evilaliv3** [comment] 2016-06-30 14:12
Dear @gszathmari thanks for getting back to us.

The issue is known and is due to old files included in the current release of tor2web.

A new version is going to be released, in the meantime you could use the update version of the globaleaks configuration for tor2web and get back to us in case of issues: https://github.com/globaleaks/Tor2web/blob/master/data/conf/tor2web-globaleaks.conf

**Comment by gszathmari** [comment] 2016-06-30 14:19
Hi @evilaliv3 , thanks for the quick response.

I am getting the folllowing error with the conf file:

```root@sd1:~# /etc/init.d/tor2web restart
Letsencrypt detected, fixing permission for /etc/letsencrypt/{live,archive} for tor2web user
 * Enabling Tor2web Apparmor Sandboxing...                                                                                                    * Restarting Tor2web tor2web...                                                                                                              * Starting tor daemon...                                                                                                             [ OK ] 
                                                                                                                                      [ OK ]
root@sd1:~# Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
Failure: twisted.spread.pb.PBConnectionLost: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
]
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
Failure: twisted.spread.pb.PBConnectionLost: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
]
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
Failure: twisted.spread.pb.PBConnectionLost: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
]
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
Failure: twisted.spread.pb.PBConnectionLost: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
]
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
Failure: twisted.spread.pb.PBConnectionLost: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
]
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
Failure: twisted.spread.pb.PBConnectionLost: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
]
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
Failure: twisted.spread.pb.PBConnectionLost: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
]```

```[main]

## TOR2WEB CONFIGURATION FOR GLOBALEAKS
# This is a minimal configuration template for a Tor2web to be used
# with globaleaks installed on the same server.
# WARNING: That setup is only valid for mid/low-risks deployments, such as anticorruption compliance in western countries

# Hostname of the public website
basehost = haha.com

# Local IP address Tor2web must be listening
listen_ipv4 = 1.2.3.4

# Tor Hidden Service 
# To get it issue the following command
# cat /var/globaleaks/torhs/hostname 
mode = TRANSLATION
onion = lol.onion

# This allows Tor2web to work as a proxy for a local GlobaLeaks platform exposed on http://127.0.0.1:8082
dummyproxy = http://127.0.0.1:8082

# CERTIFICATE CONFIGURATION
# For the commands needed for generating the files below specified refer to the wiki page at:
# https://github.com/globaleaks/Tor2web/wiki/Installation-Guide
ssl_key = /home/tor2web/certs/tor2web-key.pem
#
# LOAD THE .CRT FILE THAT HAS BEEN GIVEN YOU BY YOUR CA
ssl_cert = /home/tor2web/certs/tor2web-cer.pem
#
# LOAD HERE INTERMEDIATE CERTIFICATE CHAIN OF YOUR CA
# PLEASE BE CAREFUL TO PUT THE CERT CHAIN IN THE RIGHT ORDER!!
ssl_intermediate = /home/tor2web/certs/tor2web-intermediate.pem

# IF GLOBALEAKS IS USED IN EMBEDDED MODE UNCOMMENT THIS
# AND READ https://github.com/globaleaks/GlobaLeaks/wiki/Integration-Guide
# disable_tor_redirection = True
# blockhotlinking = False

# IF YOU WANT TO SERVE TORBROWSER FILES FROM THIS SERVER
# COMMENT THIS OUT and READ https://github.com/globaleaks/Tor2web/wiki/GetTor
disable_gettor = True

# If set to True will disable the tor2web disclaimer
disable_disclaimer = True

# If set to True will disable the tor2web banner
disable_banner = True```

**Comment by evilaliv3** [comment] 2016-07-01 09:42
@gszathmari i think that the issue here, could be that you written 1.2.3.4 in the IP?

or this was simply for not showing us the ip of your setup?

anyhow you find our a new release of tor2web that may have fixed your issues.

**Comment by gszathmari** [comment] 2016-07-01 11:23
Ah sorry I rewrote the IP here to protect my privacy

**Comment by gszathmari** [comment] 2016-07-01 11:31
Unfortunately I still got this error after `/etc/init.d/tor2web start`

```Unhandled Error
Traceback (most recent call last):
Failure: twisted.spread.pb.PBConnectionLost: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
]```

My config is the following:

```
[main]
basehost = secret.com
listen_ipv4 = x.x.x.x
mode = TRANSLATION
onion = secret.onion
dummyproxy = http://127.0.0.1:8082
ssl_key = /home/tor2web/certs/tor2web-key.pem
ssl_cert = /home/tor2web/certs/tor2web-cer.pem
ssl_intermediate = /home/tor2web/certs/tor2web-intermediate.pem
disable_gettor = True
disable_disclaimer = True
disable_banner = True
```

**Comment by evilaliv3** [comment] 2016-07-24 16:35
@gszathmari have you managed to get this fixed?

closing the ticket for now as we have retested and fixed the released configuration that i think now should works.

feel free to reopen the ticket in case you need further assistance on this topic.

**Closed by evilaliv3** 2016-07-24 16:35 UTC
Labels: C: Documentation, T: Bug

**Comment by caztillo** [comment] 2016-11-07 00:39
@evilaliv3 Hello, I'm facing the same problem when I try to start tor2web
 `Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
Failure: twisted.spread.pb.PBConnectionLost: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.`
