### ISSUE TITLE
Wizard does not detect the default language of the browser providing a preselection of language

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1445] opened 2015-10-19 13:31 UTC
Wizard does not detect the default language of the browser providing a preselection of language of the user browser

**Comment by evilaliv3** [comment] 2015-10-27 11:11
This is not a bug but a desiderata; i not that any missing feature should be marked as bug.

**Comment by fpietrosanti** [comment] 2015-10-28 08:14
It could be applied as an application-wide improvements, to automatically select the right language from the enabled ones, based on the user browser.

**Comment by NSkelsey** [comment] 2015-11-12 00:43
For this to change, the default language field in the backend must be deprecated. 

Currently, [this line](https://github.com/globaleaks/GlobaLeaks/blob/devel/backend/globaleaks/settings.py#L180) sets the language initially for the entire application until it is configured in the wizard. 

The function (set_language)[https://github.com/globaleaks/GlobaLeaks/blob/master/client/app/scripts/controllers/main.js#L277-L281] in the javascript must change for this to be implemented. (Along with the glue inbetween)

**Comment by evilaliv3** [comment] 2015-11-12 17:33
nice arguments @NSkelsey, and the point where to glue the detector is somehow the one you identified.

let me clarify why the default_language will  still remain  useful and make you  a  full example on  how this thing should probably work and let's discuss  if you  think a different approach  would work better:

what i'm describing apply not only to the wizard but would then work also for the whistleblower when  landing on  the platform  but also for admins/recipients arrive on the platform and are still not logged in.

given that:
- for sure globaleaks  won't be  able to provide all  the  possible languages ever
- an admin can enable a subset  of all the languages  available in globaleaks (e.g. 'en' and 'it' among all  language).

whenever a  german user get in, supposing that the browser is configured in german  what should be the language requested by the client?  this is the situation where the node default will  continue to be needed.

so in my opinion things should work like following:
- the platform should set the language at init/page_refresh time based on the following variable and int the following precise order: user_preference (available for logged users, only admin/receivers), language_used_through_the_selector, best_language_supporrted_in_the_browser_if_that_language_is_in_the_one_supported, as_last_resourt_the default_node_language
- there should be a detect_language function() with internal glue for  getting the browser language and uniform naming to the one used in globaleaks.  (e.g.  de_DE  as de_SOMETHING OTHER should be probably mapped on de, and  this  kind of fixing should go here)

the functions that probably we need are:
get_browser_versions() // returns an ordered array of browsers languages, mapping names  onto globaleaks names (e.g. de_DE  mapped on  de as sadly browsers also use different name various situations)

get_user_language() // mix get_browser_versions(),  node.languages, node.default_language, preference,  current_eventually_user_selected_language

the set_language() should probably continue to exists and simply be  called  in  the following fashion:

init() {
   //  this function will be  called as now on  init/refresh
   user_language = get_user_language()
   set_language(user_language)
}

user_selected_language(language) {
  set_language(language)
}

**Comment by NSkelsey** [comment] 2015-11-12 19:58
So once the admin picks the application's 'language', a whistleblower should still be able to visit the site and use it in their native tongue if the translation is available. This makes sense.

The auto-detection and choice of language that the user first sees is something that the client code can determine when the page loads. If we go with the `init` function you describe above, we run into problems when the whistleblower reaches a submission context. My understanding is that globaleaks does not support multiple translations of fields or contexts. An admin could create multiple contexts for each language they think whistleblowers need, but that is a clunky solution.

```javascript
init() {
  // this function will be called on init and refresh
  user_language = get_user_language()
  set_language(user_language)
}
```

The nice thing about the current setup is that it is simple. Adding multi-langauge support for a single deployment is almost its own issue.

**Comment by evilaliv3** [comment] 2015-11-12 23:18
all is already multilanguage!

questions, basic fields, their options etc :)

even if all is not performant as it relies on json and the python parsers
are known to be slow

**Comment by NSkelsey** [comment] 2016-05-02 13:37
A browser sniffing solution is implemented in the current devel branch. This commit adds the support 5b0a8585b2992eb

**Closed by NSkelsey** 2016-05-02 13:37 UTC
Labels: C: Client, easy, F: Internationalization, F: UserInterface, OTF-D3.1 GlobaLeaks' interface basic customization by a paypal-like approach, OTF-D3: Easier Customization, T: Enhancement, U: Admin
