### ISSUE TITLE
Failure uploading .jpg

### ISSUE THREAD

**Issue by infosquatter** [globaleaks/GlobaLeaks#1195] opened 2015-03-13 20:19 UTC
In Mexicoleaks partner reported that .jpg files arrive with 1kb size and, obviously, in blank once downloaded and open. Partners say it happened with more than 1 submission tip.

**Comment by evilaliv3** [comment] 2015-03-14 02:26
@fpietrosanti do you remember? it happened one time to lemonde. but we were not able to reproduce it. i will test it a bit. the thing is really strange as both reportts that the jpg is a valid one.

@infosquatter. are you able to reproduce it now?

**Comment by fpietrosanti** [comment] 2015-03-14 07:14
@infosquatter Please share the jpg file with which it's possible to reproduce the issue to facilitate the dev team to work on it, fixing it

**Comment by infosquatter** [comment] 2015-03-16 15:17
I tried,  but I could not reproduce it.

Giovanni Pellerano:

**Comment by infosquatter** [comment] 2015-03-16 15:18
I dont have the access to the file. Will try to ask it.

Fabio (naif) Pietrosanti:
> @infosquatter Please share the jpg file with which it's possible to reproduce the issue to facilitate the dev team to work on it, fixing it
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/globaleaks/GlobaLeaks/issues/1195#issuecomment-80050642
> 

-- 
PEDRO NOEL
- Editor
Associated Whistle-Blowing Press - https://awp.is
Chaussée d'Alsemberg 608A
1180 Uccle/Bruxelles - Belgique
GPG key: http://pgp.mit.edu/pks/lookup?op=get&search=0x72B725E1410034FB

**Comment by vecna** [comment] 2015-03-27 18:26
I guess is an heisenbug, propose to close this issue. 
very likely, an instability on the Tor circuit. 

@evilaliv3 we have in place a content-length check between the declared length in the file upload and the actual received size. so I guess in the upload phase is guarnatee.

**Comment by evilaliv3** [comment] 2015-03-27 19:42
i do not think an instability in the Tor circuit can cause it.

this issue has been reported twice. it happened also on SourceSure; receivers were able to open a correct image but all white. we should check if the jquery file uploader is the cause of the issue and if somewhere somebone had same issue.

**Comment by infosquatter** [comment] 2015-04-22 11:21
We received more complains in this issue today. It happened with again in Mexicoleaks. Same blank .jpg.

**Comment by evilaliv3** [comment] 2015-04-22 12:04
@infosquatter the code related to the file upload is now changed entirely in latest release and is now using flowjs instead of jquery-file-uploader.

i would suggest to schedule a backup of the /var/globaleaks and then update.

**Comment by evilaliv3** [comment] 2015-11-06 02:40
this ticket is outdated. let's close it.

**Closed** 2015-11-23 10:49 UTC
Labels: A: MexicoLeaks, F: AdopterRequest
