### ISSUE TITLE
submit form don´t send after enabling multiwebsite.

### ISSUE THREAD

**Issue by armeniovganga** [globaleaks/GlobaLeaks#3292] opened 2022-10-02 22:39 UTC
**Describe the bug**
I have one instalation ins app.rgpdi.com and all is working fine, but i enable the multiwebsite and create new account denuncia.gangas.pt and after doing all configuration the form don´t send, only happen in multiwebsite 

app.rgpdi.com ( original instalation ) 
denuncia.gangas.pt ( multiwebsite configuration )
denuncia.priscilaganga.pt ( multwebsite configuration )

**To Reproduce**
1. Go to 'denuncia.gangas.pt' 
2. Click on 'fill the form and click send form'
3. don´t show any error and dont´send the form

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by evilaliv3** [comment] 2022-10-03 06:55
Thank you for reportin this @armeniovganga 

Actuially this is not a bug, let me explain why this is happening and how to properly configure your secondary tenants.

Each system requires that at least one recipient is configured and assigned to the submission context.

In your case probably this new tenant have no recipients assigned to the default context.

When you installed globaleaks for the first time, you have created a recipient during the wizard and this recipient has been automatically attached to the submission context.

Please try to create a recipient user and assign it to the default submission context. This should solve your issue.

**Closed by evilaliv3** 2022-10-03 06:55 UTC

**Comment by armeniovganga** [comment] 2022-10-03 11:24
Bro apreciate your reply

Yes is working properly ;) 

thanks you are the best
