### ISSUE TITLE
label isn't shown in submission list

### ISSUE THREAD

**Issue by jbitlloch** [globaleaks/GlobaLeaks#2800] opened 2020-04-03 13:59 UTC
**Current behavior**

the label entered by the receiver inside the submission , it isn't shown in the list of submissions.

I also tested in your website :  try.globaleaks.org , and is the same behaviour

**Expected behavior**

list of submissions should show the text entered, as in previous versions.

**Steps to reproduce the problem or feature illustration**

1) submit a new report
2) receiver enter the report
3) reveiver enter a label
4) receiver go to the list
5) receiver don't see the label entered (blank instead)

**What is the motivation or use case for changing the behavior?**

it's an issue

**GlobaLeaks version:**

4.0.4 - 2020-04-18 

**Browser:**

Chrome

**Server Operating System and Version (if applicable):**
 
Ubuntu

**Client Operating System and Version (if applicable):**

Ubuntu

**Comment by evilaliv3** [comment] 2020-04-03 14:24
Thank you Joan!

This is actually a regression introduced with this feature addition: https://github.com/globaleaks/GlobaLeaks/issues/2727

**Comment by jbitlloch** [comment] 2020-04-03 15:30
hi, i solved it moving to he old behaviour.
  ( advanced configuration -> enable private labels )

the issue is only when labels are shared

**Comment by evilaliv3** [comment] 2020-04-03 16:47
Thank you for the feedback @jbitlloch.

Actually there is no manual fix for this behaviour because as you may understand given that the platform was offering private labels it is possible that multiple recipients have called the tip off differently.

The best could be to swich to the new shared label configuration and before that ask one recipient to copy the labels and re-assign them later.

**Closed** 2020-04-03 16:56 UTC
