### ISSUE TITLE
Make it possible to require whistleblowers to upload files before proceeding with the completion of the submission

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#3116] opened 2021-11-22 12:27 UTC
**Describe the bug**
In questionnaires if an attachment field is set as required, alarm is not given and report can be sent without the attachment.

**To Reproduce**
1. On a questionnaire set an attachment field as required.
2. When you try to file a report the upsaid required field is ignored, and if there are other errors, It's ignored in the error list also.
3. Same if there are multiple files

**Expected behavior**
An alarm of missed attachment should be expected

**Desktop (please complete the following information):**
 - OS: w10
 - Browser: firefox 94

**Comment by evilaliv3** [comment] 2021-11-22 13:58
Thannk you @larrykind for this feedback.

Actually this is not a bug but a UI issue because actually the feature is not implemented.

I propose to do the following:
- in the short term i will hide this option on file uploads so that users wont be confused thinking that the feature exists.
- i will rename this ticket so to keep track of this possible feature and plan for implementing it.

**Comment by larrykind** [comment] 2021-11-22 14:45
thank you @evilaliv3 for the quick answer. 
Any javascript solution to accomplish this?

**Comment by evilaliv3** [comment] 2021-11-22 15:09
At the moment no. The whole implementation that i plan to do will be based on a clientside check on this.

Before simply disabling the feature i will check if i could easily implement the feature instead.

**Comment by evilaliv3** [comment] 2021-11-26 12:45
Implemented @larrykind ! The patch will be included in 4.5.9

**Closed** 2021-11-26 12:45 UTC
Labels: T: Enhancement, C: Client
