### ISSUE TITLE
GL do not install again in Cubian (Wheezy)

### ISSUE THREAD

**Issue by calamarim** [globaleaks/GlobaLeaks#1207] opened 2015-03-20 18:46 UTC
this is what I obtain, withour pressing a single key as answer

root@cloud-in-a-box-20:~# curl https://deb.globaleaks.org/install-globaleaks.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6564  100  6564    0     0   1165      0  0:00:05  0:00:05 --:--:-- 16369
bash: line 82: lsb_release: command not found
bash: line 87: lsb_release: command not found
!!!!!!!!!!!! WARNING !!!!!!!!!!!!
You are attempting to install GlobaLeaks on an unsupported platform.
Supported platform are Debian (wheezy, jessie) and Ubuntu (precise, trusty)\n
Do you wish to continue at your own risk [Y|N]? 
bash: line 107: [: too many arguments
Installation aborted. Still friends, right?

**Comment by vecna** [comment] 2015-03-27 18:32
Another user report the same bug. I'v esuggest to open he file and execute the commands manually.

**Comment by evilaliv3** [comment] 2015-03-29 16:49
@calamarim with latest commit the issue should be fixed.
we should avoid suggestin to do "curl antani.sh | bash" because "| bash" does not work with bash "read" directive.

so the new instruction to test (and install) are:

    curl https://raw.githubusercontent.com/globaleaks/GlobaLeaks/7d292f57e45ec1b1bfb6f85a0369222edd587553/scripts/install.sh
   chmod +x install.sh
   ./install.sh

could you please test it and confirm us that the issue is solved?

**Comment by calamarim** [comment] 2015-03-29 20:40
curl send the script to the terminal
so i redirected it to a file with the right name
but the script do not do anythyng

see the full story

root@cloud-in-a-box-20:~# curl https://raw.githubusercontent.com/globaleaks/GlobaLeaks/7d292f57e45ec1b1bfb6f85a0369222edd587553/scripts/install.sh > install.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6752  100  6752    0     0   8296      0 --:--:-- --:--:-- --:--:-- 10468
root@cloud-in-a-box-20:~# chmod +x install.sh
root@cloud-in-a-box-20:~# ./install.sh
!!!!!!!!!!!! WARNING !!!!!!!!!!!!
You are attempting to install GlobaLeaks on an unsupported platform.
Supported platform are Debian (wheezy, jessie) and Ubuntu (precise, trusty)
Do you wish to continue anyhow? [y|n]?

Please answer y/n.
Do you wish to continue anyhow? [y|n]?y
root@cloud-in-a-box-20:~# curl https://raw.githubusercontent.com/globaleaks/GlobaLeaks/7d292f57e45ec1b1bfb6f85a0369222edd587553/scripts/install.sh > install.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6752  100  6752    0     0   8147      0 --:--:-- --:--:-- --:--:-- 12057
root@cloud-in-a-box-20:~# chmod +x install.sh
root@cloud-in-a-box-20:~# ./install.sh
!!!!!!!!!!!! WARNING !!!!!!!!!!!!
You are attempting to install GlobaLeaks on an unsupported platform.
Supported platform are Debian (wheezy, jessie) and Ubuntu (precise, trusty)
Do you wish to continue anyhow? [y|n]?y
root@cloud-in-a-box-20:~#

**Comment by evilaliv3** [comment] 2015-03-29 21:40
ah sorry @calamarim 

can you retry now?

so the new instruction to test (and install) are:

    curl https://raw.githubusercontent.com/globaleaks/GlobaLeaks/eba10b952037df33c44af7cfa2c0777edd4790db/scripts/install.sh
    chmod +x install.sh
    ./install.sh

**Comment by evilaliv3** [comment] 2015-04-01 10:34
the issue seems to be solved.

**Closed by evilaliv3** 2015-04-01 10:34 UTC
Labels: C: ReleaseScripts, InstallScripts, Type: bug
