### ISSUE TITLE
Unexpected behavior disable/enable privacy panel

### ISSUE THREAD

**Issue by pvigoseidor** [globaleaks/GlobaLeaks#3401] opened 2023-03-24 12:29 UTC
### What version of GlobaLeaks are you using?

4.11.0

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

When the **Enable multisite feature** is enabled, individual sites can't disable or enable or customize the privacy panel.

### Proposed solution

It would be great if the individuals sites from a multisite installation could configure the privacy panel as they want.

**Comment by evilaliv3** [comment] 2023-03-24 20:48
@pvigoseidor: Actually i just retested the functionality and actually i'm not able to reproduce the bug.

I suspect you could have incurred in a false positive; actually in fact the privacy panel is always configurable up to the user choice except as long that the platform is running in default or demo mode.

I'm closing this issue, but please feel free to re-open it in case you are still incurring in the issue or your find a way to reproduce the bug.

**Closed** 2023-03-24 20:49 UTC

**Comment by pvigoseidor** [comment] 2023-03-29 10:26
Thank you Giovanni.

We confirm the correct behavior of the solution, and we think the issue could be by our load balancer.
