### ISSUE TITLE
Problem in managing languages.

### ISSUE THREAD

**Issue by CEDEssedi** [globaleaks/GlobaLeaks#4076] opened 2024-05-21 07:12 UTC
### What version of GlobaLeaks are you using?

The system version is 4.15.4.

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### Describe the issue

Dears,
I would like to point out a problem in managing languages. In the Settings section, the "Project Name" and "Description" fields are not multilingual. We have three language enabled but, when we put something in above fields, the value is replicated also in other languages and we are not able to specify different values for different languages.

**Comment by evilaliv3** [comment] 2024-05-21 07:53
Thank you for feeback @CEDEssedi 

At the moment the project name was designed to not be subject to internationalization because typically the project name is subject to branding.
We will consider you feedback during next development.

**Comment by evilaliv3** [comment] 2024-06-15 13:15
closing as duplicated ticket fr https://github.com/globaleaks/GlobaLeaks/issues/3757

**Closed by evilaliv3** 2024-06-15 13:15 UTC
Labels: T: Enhancement
