### ISSUE TITLE
Passwords containing special Danish letters making passwords for recovery key impossible to retreive

### ISSUE THREAD

**Issue by schris-dk** [globaleaks/GlobaLeaks#3466] opened 2023-06-01 06:49 UTC
### What version of GlobaLeaks are you using?

4.11.5

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

We have a Danish  admin user, who have created a password containing the Danish letter "Å". The password works for login, but it does not work for the creation of a Account Recovery Key - login fails and user is returned to the passwords screen.

When omitting the speical letter, login works, and Account Recovery Key can be retreived

### Proposed solution

It seems like the verification of the passwords are using two different schemes

**Comment by evilaliv3** [comment] 2023-06-01 07:38
Hello @schris-dk 

I just tried the following but it works for me:
- I created a user
- I've set the password including Å at the end
- I've asked the account recovery key providing the password 

Would you please clarify if this i how i should reproduce the issue?

On which distribution / version is your setup based?

**Comment by schris-dk** [comment] 2023-06-01 07:58
Hi!

We are using 4.11.5


I’ve just tried to create a new Admin user with the password ÅÅøøæwBWYddQI5~nh^7XE'0Yp

It refuses to show Account recovery key

Same with Recipient user

Med venlig hilsen
Søren Christensen
Senior Manager
BDO Statsautoriseret revisionsaktieselskab

**Comment by evilaliv3** [comment] 2023-06-02 17:33
@schris-dk : on which operating system is globaleaks installed and which is the version of the operating system?

**Comment by schris-dk** [comment] 2023-06-02 17:50
We sre using VM’s in Azure - running latestvDebian distro

Søren Christensen
Senior manager
BDO Risk Assurance - Forensic Services
***@***.***
+45 30 93 49 33
________________________________
Fra: Giovanni Pellerano ***@***.***>
Sendt: Friday, June 2, 2023 7:34:08 PM
Til: globaleaks/GlobaLeaks ***@***.***>
Cc: Søren Christensen ***@***.***>; Mention ***@***.***>
Emne: Re: [globaleaks/GlobaLeaks] Passwords containing special Danish letters making passwords for recovery key impossible to retreive (Issue #3466)


Denne e-mail blev sendt af nogen uden for BDO i Danmark. Tænk dig altid om, når du åbner vedhæftede filer, klikker på links fra ukendte afsendere, eller når du modtager uventede e-mails.

@schris-dk<https://github.com/schris-dk> : on which operating system is globaleaks installed and which is the version of the operating system?

**Comment by evilaliv3** [comment] 2023-06-02 17:55
I'm testing this exact setup using as Client a Firefox installed in english.

I expect the problem is in parsing the encoding string arriving from a browser with danish locale probably using a particular encoding when sending data.

**Comment by schris-dk** [comment] 2023-06-02 18:01
OK - we’ve been trying Firefox,Chrome and Edge

Anything we can do at the moment?

Søren Christensen
Senior manager
BDO Risk Assurance - Forensic Services
***@***.***
+45 30 93 49 33
________________________________
Fra: Giovanni Pellerano ***@***.***>
Sendt: Friday, June 2, 2023 7:55:47 PM
Til: globaleaks/GlobaLeaks ***@***.***>
Cc: Søren Christensen ***@***.***>; Mention ***@***.***>
Emne: Re: [globaleaks/GlobaLeaks] Passwords containing special Danish letters making passwords for recovery key impossible to retreive (Issue #3466)


Denne e-mail blev sendt af nogen uden for BDO i Danmark. Tænk dig altid om, når du åbner vedhæftede filer, klikker på links fra ukendte afsendere, eller når du modtager uventede e-mails.

I'm testing this exact setup using as Client a Firefox installed in english.

I expect the problem is in parsing the encoding string arriving from a browser with danish locale probably using a particular encoding when sending data.

**Comment by evilaliv3** [comment] 2023-06-02 18:28
On which operating system are you testing the clients? Which is the language of these setups?

**Comment by schris-dk** [comment] 2023-06-02 18:35
Windows 11 - Danish language

Søren Christensen
Senior manager
BDO Risk Assurance - Forensic Services
***@***.***
+45 30 93 49 33
________________________________
Fra: Giovanni Pellerano ***@***.***>
Sendt: Friday, June 2, 2023 8:28:11 PM
Til: globaleaks/GlobaLeaks ***@***.***>
Cc: Søren Christensen ***@***.***>; Mention ***@***.***>
Emne: Re: [globaleaks/GlobaLeaks] Passwords containing special Danish letters making passwords for recovery key impossible to retreive (Issue #3466)


Denne e-mail blev sendt af nogen uden for BDO i Danmark. Tænk dig altid om, når du åbner vedhæftede filer, klikker på links fra ukendte afsendere, eller når du modtager uventede e-mails.

On which operating system are you testing the clients? Which is the language of these setups?

**Comment by evilaliv3** [comment] 2023-06-02 19:20
@schris-dk : I may have identified a fix and i've loaded it on https://try.globaleaks.org;

Would you please try if it works for you?

**Comment by schris-dk** [comment] 2023-06-09 12:49
HI Giovanni!

There still seems to be a problem.

I created a TRY site and logged in to set admin PW, initially setting the PW with Danish special Char like below:

***@***.***

The password could not be accepted

When changing the Danish letters, there was no issue

***@***.***

Passwords used:

ÆøÅqqqqql12345678#

XpXqqqqql12345678#


Med venlig hilsen
Søren Christensen
Senior Manager
Telefon: +4539159901
Mobil: +4530934933
***@***.******@***.***>

BDO Statsautoriseret revisionsaktieselskab
CVR: 20222670
Havneholmen 29
1561 København V
Tlf.: +4539155200
www.bdo.dk<https://www.bdo.dk/da-dk/bdo-danmark>

BDO Statsautoriseret revisionsaktieselskab, danskejet rådgivnings- og revisionsvirksomhed, er medlem af BDO International Limited - et UK-baseret selskab med begrænset hæftelse - og del af det internationale BDO netværk bestående af uafhængige medlemsfirmaer. BDO er varemærke for både BDO netværket og for alle BDO medlemsfirmaerne. BDO i Danmark beskæftiger mere end 1.400 medarbejdere, mens det verdensomspændende BDO netværk har over 111.000 medarbejdere i mere end 164 lande.

Denne e-mail og enhver vedhæftet fil er fortrolig. Hvis du ikke er rette modtager, bedes du venligst omgående underrette os og derefter slette e-mailen og enhver vedhæftet fil uden at beholde kopi og uden at videregive oplysninger om indholdet.

Tænk på miljøet - er det nødvendigt at printe mailen?



Fra: Giovanni Pellerano ***@***.***>
Sendt: 2. juni 2023 21:21
Til: globaleaks/GlobaLeaks ***@***.***>
Cc: Søren Christensen ***@***.***>; Mention ***@***.***>
Emne: Re: [globaleaks/GlobaLeaks] Passwords containing special Danish letters making passwords for recovery key impossible to retreive (Issue #3466)


Denne e-mail blev sendt af nogen uden for BDO i Danmark. Tænk dig altid om, når du åbner vedhæftede filer, klikker på links fra ukendte afsendere, eller når du modtager uventede e-mails.

@schris-dk<https://github.com/schris-dk> : I may have identified a fix and i've loaded it on https://try.globaleaks.org;

Would you please try if it works for you?

**Comment by evilaliv3** [comment] 2023-06-09 18:45
Thank you @schris-dk 

Actually this is quite strange and to solve this we need that you try to inspect the javascript console more.

Are you sure that the problem is not between your computer and the remote desktop environment and that when you type the password the system does actually change the characters set?

Let me explain what i know and what i tested:
- the only part that is different between logging with a password and using password configrmation is that during password configmration the password is passed in an HTTP header.
- http headers as standard are encoded by any browser with ISO-8859-1
- ISO-8859-1 is known to includeonly some characters and this is the reason of your initial failure
- We are testing a patch where before sending a password we run this algorithm: btoa(unescape(encodeURIComponent(password))); that is expected to be a know solution for this problem.

Would you please try to run this code in your javascript console and see if you get the same result?
```btoa(unescape(encodeURIComponent('ÆøÅqqqqql12345678#')));
'w4bDuMOFcXFxcXFsMTIzNDU2Nzgj'```

If you look at the requests mage by your browser, do you see on the request do you see the header "x-confirmation" showing this value?




From what i

**Comment by evilaliv3** [comment] 2023-06-10 09:22
Thank you @schris-dk 

I've reworked the fix and now i hope it should work.

The problem is that HTTP headers are encoded by standard in ISO-8859-1 and transmitting danish characters as http header requires some quirks because they do not fit the ISO-8859-1 encoding as described here: https://en.wikipedia.org/wiki/ISO/IEC_8859-1

For this reason we have applied a known algorithm that is expected to fix the situation: https://developer.mozilla.org/en-US/docs/Web/API/btoa

We will be releasing this update in a little and in the meantime it would be very great if you could confirm the fix on try.globaleaks.org (you can use the tenant you already created for retesting purpose).

**Comment by evilaliv3** [comment] 2023-06-13 12:48
@schris-dk: If it possible for you to check on try.globaleaks.org if this issue is solved?

Thank you!

**Comment by schris-dk** [comment] 2023-06-13 13:08
Hi!

Unfortunately I still see the same issue:

Using the PW ÆøÅqqqqql12345678#  I get this error when trying to set new password

***@***.***

I’ve been testing on Danish Win 11 (Chrome and Edge), English WinServer 2016 and English WinServer2019 Datacenter

Med venlig hilsen
Søren Christensen
Senior Manager
Telefon: +4539159901
Mobil: +4530934933
***@***.******@***.***>

BDO Statsautoriseret revisionsaktieselskab
CVR: 20222670
Havneholmen 29
1561 København V
Tlf.: +4539155200
www.bdo.dk<https://www.bdo.dk/da-dk/bdo-danmark>

BDO Statsautoriseret revisionsaktieselskab, danskejet rådgivnings- og revisionsvirksomhed, er medlem af BDO International Limited - et UK-baseret selskab med begrænset hæftelse - og del af det internationale BDO netværk bestående af uafhængige medlemsfirmaer. BDO er varemærke for både BDO netværket og for alle BDO medlemsfirmaerne. BDO i Danmark beskæftiger mere end 1.400 medarbejdere, mens det verdensomspændende BDO netværk har over 111.000 medarbejdere i mere end 164 lande.

Denne e-mail og enhver vedhæftet fil er fortrolig. Hvis du ikke er rette modtager, bedes du venligst omgående underrette os og derefter slette e-mailen og enhver vedhæftet fil uden at beholde kopi og uden at videregive oplysninger om indholdet.

Tænk på miljøet - er det nødvendigt at printe mailen?



Fra: Giovanni Pellerano ***@***.***>
Sendt: 13. juni 2023 14:49
Til: globaleaks/GlobaLeaks ***@***.***>
Cc: Søren Christensen ***@***.***>; Mention ***@***.***>
Emne: Re: [globaleaks/GlobaLeaks] Passwords containing special Danish letters making passwords for recovery key impossible to retreive (Issue #3466)


Denne e-mail blev sendt af nogen uden for BDO i Danmark. Tænk dig altid om, når du åbner vedhæftede filer, klikker på links fra ukendte afsendere, eller når du modtager uventede e-mails.

@schris-dk<https://github.com/schris-dk>: If it possible for you to check on try.globaleaks.org if this issue is solved?

Thank you!

**Comment by schris-dk** [comment] 2023-06-16 05:24
Hi Giovanni!

I’m a little unsure what you want me to do here – do you want me to run the code (then where) or what else? Been trying to open the developers page in Chrome, but do not get any output ther

Another thing regarding the use of bdodk.try.globaleaks.org – the issue with the passwords already occouers when trying to change the passwords for the account – not just the recovery key

***@***.***

Med venlig hilsen
Søren Christensen
Senior Manager
Telefon: +4539159901
Mobil: +4530934933
***@***.******@***.***>

BDO Statsautoriseret revisionsaktieselskab
CVR: 20222670
Havneholmen 29
1561 København V
Tlf.: +4539155200
www.bdo.dk<https://www.bdo.dk/da-dk/bdo-danmark>

BDO Statsautoriseret revisionsaktieselskab, danskejet rådgivnings- og revisionsvirksomhed, er medlem af BDO International Limited - et UK-baseret selskab med begrænset hæftelse - og del af det internationale BDO netværk bestående af uafhængige medlemsfirmaer. BDO er varemærke for både BDO netværket og for alle BDO medlemsfirmaerne. BDO i Danmark beskæftiger mere end 1.400 medarbejdere, mens det verdensomspændende BDO netværk har over 111.000 medarbejdere i mere end 164 lande.

Denne e-mail og enhver vedhæftet fil er fortrolig. Hvis du ikke er rette modtager, bedes du venligst omgående underrette os og derefter slette e-mailen og enhver vedhæftet fil uden at beholde kopi og uden at videregive oplysninger om indholdet.

Tænk på miljøet - er det nødvendigt at printe mailen?



Fra: Giovanni Pellerano ***@***.***>
Sendt: 13. juni 2023 17:17
Til: globaleaks/GlobaLeaks ***@***.***>
Cc: Søren Christensen ***@***.***>; Mention ***@***.***>
Emne: Re: [globaleaks/GlobaLeaks] Passwords containing special Danish letters making passwords for recovery key impossible to retreive (Issue #3466)


Denne e-mail blev sendt af nogen uden for BDO i Danmark. Tænk dig altid om, når du åbner vedhæftede filer, klikker på links fra ukendte afsendere, eller når du modtager uventede e-mails.

This is actually quite strange. I do not have any issue.

When you request the account recovery key, the system asks for your password and send it via an HTTP header and there there was definitely a bug because HTTP headers cannot support danish characters.

Now we are instead running this algorithm:

    encodeString: function(string) {

      var result1, result2;

      // convert a Unicode string to a string in which

      // each 16-bit unit occupies only one byte

      const codeUnits = Uint16Array.from(

        { length: string.length },

          (element, index) => string.charCodeAt(index)

      );



      const charCodes = new Uint8Array(codeUnits.buffer);



      result1 = "";

      charCodes.forEach((char) => {

        result1 += String.fromCharCode(char);

      });



      result2 = btoa(result);



      return result2;

    }```



Are you able to test it with your browsers and inspect the values of the variables result1 and result2?

**Comment by evilaliv3** [comment] 2023-06-16 06:11
Thank you @schris-dk 

I've prepared for you a specific code to test at: bdodk.try.globaleaks.org 

Thank you if you could do the following:

1. Please open the page, log in as recipient, and request the account recovery key.
2. then open the console
3. input the password only after openin the console
4. log and pass me the output of the console
5. log and pass me the headers of the request on the handler /api/user/operation

**Comment by schris-dk** [comment] 2023-06-16 07:07
Output with console:

***@***.***

Med venlig hilsen
Søren Christensen
Senior Manager
Telefon: +4539159901
Mobil: +4530934933
***@***.******@***.***>

BDO Statsautoriseret revisionsaktieselskab
CVR: 20222670
Havneholmen 29
1561 København V
Tlf.: +4539155200
www.bdo.dk<https://www.bdo.dk/da-dk/bdo-danmark>

BDO Statsautoriseret revisionsaktieselskab, danskejet rådgivnings- og revisionsvirksomhed, er medlem af BDO International Limited - et UK-baseret selskab med begrænset hæftelse - og del af det internationale BDO netværk bestående af uafhængige medlemsfirmaer. BDO er varemærke for både BDO netværket og for alle BDO medlemsfirmaerne. BDO i Danmark beskæftiger mere end 1.400 medarbejdere, mens det verdensomspændende BDO netværk har over 111.000 medarbejdere i mere end 164 lande.

Denne e-mail og enhver vedhæftet fil er fortrolig. Hvis du ikke er rette modtager, bedes du venligst omgående underrette os og derefter slette e-mailen og enhver vedhæftet fil uden at beholde kopi og uden at videregive oplysninger om indholdet.

Tænk på miljøet - er det nødvendigt at printe mailen?



Fra: Giovanni Pellerano ***@***.***>
Sendt: 16. juni 2023 08:12
Til: globaleaks/GlobaLeaks ***@***.***>
Cc: Søren Christensen ***@***.***>; Mention ***@***.***>
Emne: Re: [globaleaks/GlobaLeaks] Passwords containing special Danish letters making passwords for recovery key impossible to retreive (Issue #3466)


Ekstern afsender

Thank you @schris-dk<https://github.com/schris-dk>

I've prepared for you a specific code to test at: bdodk.try.globaleaks.org

Thank you if you could do the following:

  1.  Please open the page, log in as recipient, and request the account recovery key.
  2.  then open the console
  3.  input the password only after openin the console
  4.  log and pass me the output of the console
  5.  log and pass me the headers of the request on the handler /api/user/operation

**Comment by evilaliv3** [comment] 2023-06-16 15:25
@schris-dk would you please acquire a screenshot like the following?

i've redacted some part that is the part i would like to see.

Thank you

![example](https://github.com/globaleaks/GlobaLeaks/assets/217034/00d50022-86fb-47e0-81be-e8529dbe92f3)

**Comment by schris-dk** [comment] 2023-06-18 11:06
Output from Chrome Console

***@***.***


Output from Edge console

***@***.***


Med venlig hilsen
Søren Christensen
Senior Manager
Telefon: +4539159901
Mobil: +4530934933
***@***.******@***.***>

BDO Statsautoriseret revisionsaktieselskab
CVR: 20222670
Havneholmen 29
1561 København V
Tlf.: +4539155200
www.bdo.dk<https://www.bdo.dk/da-dk/bdo-danmark>

BDO Statsautoriseret revisionsaktieselskab, danskejet rådgivnings- og revisionsvirksomhed, er medlem af BDO International Limited - et UK-baseret selskab med begrænset hæftelse - og del af det internationale BDO netværk bestående af uafhængige medlemsfirmaer. BDO er varemærke for både BDO netværket og for alle BDO medlemsfirmaerne. BDO i Danmark beskæftiger mere end 1.400 medarbejdere, mens det verdensomspændende BDO netværk har over 111.000 medarbejdere i mere end 164 lande.

Denne e-mail og enhver vedhæftet fil er fortrolig. Hvis du ikke er rette modtager, bedes du venligst omgående underrette os og derefter slette e-mailen og enhver vedhæftet fil uden at beholde kopi og uden at videregive oplysninger om indholdet.

Tænk på miljøet - er det nødvendigt at printe mailen?



Fra: Giovanni Pellerano ***@***.***>
Sendt: 16. juni 2023 17:26
Til: globaleaks/GlobaLeaks ***@***.***>
Cc: Søren Christensen ***@***.***>; Mention ***@***.***>
Emne: Re: [globaleaks/GlobaLeaks] Passwords containing special Danish letters making passwords for recovery key impossible to retreive (Issue #3466)


Ekstern afsender

@schris-dk<https://github.com/schris-dk> would you please acquire a screenshot like the following?

i've redacted some part that is the part i would like to see.

Thank you

[example]<https://user-images.githubusercontent.com/217034/246461077-00d50022-86fb-47e0-81be-e8529dbe92f3.png>

**Comment by evilaliv3** [comment] 2023-06-18 13:24
Thank you.

Actually the provided feedback seems incomplete.
In the log there should be multiple lines like in the one I provided.

Is it possible for you to attach a full screenshot like mine?


Thank you

**Comment by schris-dk** [comment] 2023-06-18 13:25
This is all the output I get :(

Søren Christensen
Senior manager
BDO Risk Assurance - Forensic Services
***@***.***
+45 30 93 49 33
________________________________
Fra: Giovanni Pellerano ***@***.***>
Sendt: Sunday, June 18, 2023 3:24:36 PM
Til: globaleaks/GlobaLeaks ***@***.***>
Cc: Søren Christensen ***@***.***>; Mention ***@***.***>
Emne: Re: [globaleaks/GlobaLeaks] Passwords containing special Danish letters making passwords for recovery key impossible to retreive (Issue #3466)


Ekstern afsender

Thank you.

Actually the provided feedback seems incomplete.
In the log there should be multiple lines like in the one I provided.

Is it possible for you to attach a full screenshot like mine?


Thank you

**Comment by schris-dk** [comment] 2023-06-18 13:26
We can do a screen share if needed

Søren Christensen
Senior manager
BDO Risk Assurance - Forensic Services
***@***.***
+45 30 93 49 33
________________________________
Fra: Søren Christensen ***@***.***>
Sendt: Sunday, June 18, 2023 3:25:27 PM
Til: globaleaks/GlobaLeaks ***@***.***>; globaleaks/GlobaLeaks ***@***.***>
Cc: Mention ***@***.***>
Emne: Re: [globaleaks/GlobaLeaks] Passwords containing special Danish letters making passwords for recovery key impossible to retreive (Issue #3466)

This is all the output I get :(

Søren Christensen
Senior manager
BDO Risk Assurance - Forensic Services
***@***.***
+45 30 93 49 33
________________________________
Fra: Giovanni Pellerano ***@***.***>
Sendt: Sunday, June 18, 2023 3:24:36 PM
Til: globaleaks/GlobaLeaks ***@***.***>
Cc: Søren Christensen ***@***.***>; Mention ***@***.***>
Emne: Re: [globaleaks/GlobaLeaks] Passwords containing special Danish letters making passwords for recovery key impossible to retreive (Issue #3466)


Ekstern afsender

Thank you.

Actually the provided feedback seems incomplete.
In the log there should be multiple lines like in the one I provided.

Is it possible for you to attach a full screenshot like mine?


Thank you

**Comment by evilaliv3** [comment] 2023-06-18 13:30
I'm out now and unfortunately with limited time to work in this period.

If you can please attach a screenshot.

Which platform are you testing right know?

**Comment by schris-dk** [comment] 2023-06-18 13:57
Latest try

***@***.***

Med venlig hilsen
Søren Christensen
Senior Manager
Telefon: +4539159901
Mobil: +4530934933
***@***.******@***.***>

BDO Statsautoriseret revisionsaktieselskab
CVR: 20222670
Havneholmen 29
1561 København V
Tlf.: +4539155200
www.bdo.dk<https://www.bdo.dk/da-dk/bdo-danmark>

BDO Statsautoriseret revisionsaktieselskab, danskejet rådgivnings- og revisionsvirksomhed, er medlem af BDO International Limited - et UK-baseret selskab med begrænset hæftelse - og del af det internationale BDO netværk bestående af uafhængige medlemsfirmaer. BDO er varemærke for både BDO netværket og for alle BDO medlemsfirmaerne. BDO i Danmark beskæftiger mere end 1.400 medarbejdere, mens det verdensomspændende BDO netværk har over 111.000 medarbejdere i mere end 164 lande.

Denne e-mail og enhver vedhæftet fil er fortrolig. Hvis du ikke er rette modtager, bedes du venligst omgående underrette os og derefter slette e-mailen og enhver vedhæftet fil uden at beholde kopi og uden at videregive oplysninger om indholdet.

Tænk på miljøet - er det nødvendigt at printe mailen?



Fra: Giovanni Pellerano ***@***.***>
Sendt: 18. juni 2023 15:30
Til: globaleaks/GlobaLeaks ***@***.***>
Cc: Søren Christensen ***@***.***>; Mention ***@***.***>
Emne: Re: [globaleaks/GlobaLeaks] Passwords containing special Danish letters making passwords for recovery key impossible to retreive (Issue #3466)


Ekstern afsender
I'm out now and unfortunately with limited time to work in this period.

If you can please attach a screenshot.

Which platform are you testing right know?

**Comment by evilaliv3** [comment] 2023-06-18 15:29
Thank you.

I do not see screenshots attached. Maybe you missed to upload it?

On which platform are you testing this?

**Comment by schris-dk** [comment] 2023-06-18 16:17
Hi Giovanni!

Pocture insertede in mail

Using Win10

***@***.***

Med venlig hilsen
Søren Christensen
Senior Manager
Telefon: +4539159901
Mobil: +4530934933
***@***.******@***.***>

BDO Statsautoriseret revisionsaktieselskab
CVR: 20222670
Havneholmen 29
1561 København V
Tlf.: +4539155200
www.bdo.dk<https://www.bdo.dk/da-dk/bdo-danmark>

BDO Statsautoriseret revisionsaktieselskab, danskejet rådgivnings- og revisionsvirksomhed, er medlem af BDO International Limited - et UK-baseret selskab med begrænset hæftelse - og del af det internationale BDO netværk bestående af uafhængige medlemsfirmaer. BDO er varemærke for både BDO netværket og for alle BDO medlemsfirmaerne. BDO i Danmark beskæftiger mere end 1.400 medarbejdere, mens det verdensomspændende BDO netværk har over 111.000 medarbejdere i mere end 164 lande.

Denne e-mail og enhver vedhæftet fil er fortrolig. Hvis du ikke er rette modtager, bedes du venligst omgående underrette os og derefter slette e-mailen og enhver vedhæftet fil uden at beholde kopi og uden at videregive oplysninger om indholdet.

Tænk på miljøet - er det nødvendigt at printe mailen?



Fra: Giovanni Pellerano ***@***.***>
Sendt: 18. juni 2023 17:30
Til: globaleaks/GlobaLeaks ***@***.***>
Cc: Søren Christensen ***@***.***>; Mention ***@***.***>
Emne: Re: [globaleaks/GlobaLeaks] Passwords containing special Danish letters making passwords for recovery key impossible to retreive (Issue #3466)


Ekstern afsender
Thank you.

I do not see screenshots attached. Maybe you missed to upload it?

On which platform are you testing this?

**Comment by evilaliv3** [comment] 2023-06-18 17:14
Thank you.

Actually to load the screenshots you should attach them using your GitHub
account.


Probably you attached screenshots like this before? They were never
received! Could you please check and upload all the tests collected?

Thank you!

**Comment by schris-dk** [comment] 2023-06-18 18:14
![gtDQbGu5RC](https://github.com/globaleaks/GlobaLeaks/assets/70965554/efb303d6-a9be-4f88-89be-23dc43119f41)

**Comment by evilaliv3** [comment] 2023-06-18 20:44
@schris-dk : this is not the requested screenshot.  

Please follow the procedure provided in https://github.com/globaleaks/GlobaLeaks/issues/3466#issuecomment-1594159651.

Thank you

**Comment by schris-dk** [comment] 2023-06-19 04:19
Hi Giovanni!
As you can see from the screenshot I cannot even get the PW to work when I try to change it at first login now

Søren Christensen
Senior manager
BDO Risk Assurance - Forensic Services
***@***.***
+45 30 93 49 33
________________________________
Fra: Giovanni Pellerano ***@***.***>
Sendt: Sunday, June 18, 2023 10:44:48 PM
Til: globaleaks/GlobaLeaks ***@***.***>
Cc: Søren Christensen ***@***.***>; Mention ***@***.***>
Emne: Re: [globaleaks/GlobaLeaks] Passwords containing special Danish letters making passwords for recovery key impossible to retreive (Issue #3466)


Ekstern afsender

@schris-dk<https://github.com/schris-dk> : this is not the requested screenshot.

Please follow the procedure provided in #3466 (comment)<https://github.com/globaleaks/GlobaLeaks/issues/3466#issuecomment-1594159651>.

Thank you

**Comment by schris-dk** [comment] 2023-06-19 04:21
If there is a spcific screenshot you request from th console, I need you to assist me further, as then I’m not sure what you request from me :)

Søren Christensen
Senior manager
BDO Risk Assurance - Forensic Services
***@***.***
+45 30 93 49 33
________________________________
Fra: Søren Christensen ***@***.***>
Sendt: Monday, June 19, 2023 6:19:36 AM
Til: globaleaks/GlobaLeaks ***@***.***>; globaleaks/GlobaLeaks ***@***.***>
Cc: Mention ***@***.***>
Emne: Re: [globaleaks/GlobaLeaks] Passwords containing special Danish letters making passwords for recovery key impossible to retreive (Issue #3466)

 Hi Giovanni!
As you can see from the screenshot I cannot even get the PW to work when I try to change it at first login now

Søren Christensen
Senior manager
BDO Risk Assurance - Forensic Services
***@***.***
+45 30 93 49 33
________________________________
Fra: Giovanni Pellerano ***@***.***>
Sendt: Sunday, June 18, 2023 10:44:48 PM
Til: globaleaks/GlobaLeaks ***@***.***>
Cc: Søren Christensen ***@***.***>; Mention ***@***.***>
Emne: Re: [globaleaks/GlobaLeaks] Passwords containing special Danish letters making passwords for recovery key impossible to retreive (Issue #3466)


Ekstern afsender

@schris-dk<https://github.com/schris-dk> : this is not the requested screenshot.

Please follow the procedure provided in #3466 (comment)<https://github.com/globaleaks/GlobaLeaks/issues/3466#issuecomment-1594159651>.

Thank you

**Comment by evilaliv3** [comment] 2023-06-19 05:03
Thank you.

Actually what I made on this setup is to change the code of the account
recovery key request and i adding some log in

For this reason if you are encouraging issues on the password change is
because you are entering a password that do not satisfy the security level.
please check the message

**Comment by schris-dk** [comment] 2023-06-19 05:46
Hi!
The password used is  ÆøÅqqqqql12345678#  which should meet the requirements by length and complexity (18 char, number, upper case, lower case and special char)

Med venlig hilsen
Søren Christensen
Senior Manager
Telefon: +4539159901
Mobil: +4530934933
***@***.******@***.***>

BDO Statsautoriseret revisionsaktieselskab
CVR: 20222670
Havneholmen 29
1561 København V
Tlf.: +4539155200
www.bdo.dk<https://www.bdo.dk/da-dk/bdo-danmark>

BDO Statsautoriseret revisionsaktieselskab, danskejet rådgivnings- og revisionsvirksomhed, er medlem af BDO International Limited - et UK-baseret selskab med begrænset hæftelse - og del af det internationale BDO netværk bestående af uafhængige medlemsfirmaer. BDO er varemærke for både BDO netværket og for alle BDO medlemsfirmaerne. BDO i Danmark beskæftiger mere end 1.400 medarbejdere, mens det verdensomspændende BDO netværk har over 111.000 medarbejdere i mere end 164 lande.

Denne e-mail og enhver vedhæftet fil er fortrolig. Hvis du ikke er rette modtager, bedes du venligst omgående underrette os og derefter slette e-mailen og enhver vedhæftet fil uden at beholde kopi og uden at videregive oplysninger om indholdet.

Tænk på miljøet - er det nødvendigt at printe mailen?



Fra: Giovanni Pellerano ***@***.***>
Sendt: 19. juni 2023 07:04
Til: globaleaks/GlobaLeaks ***@***.***>
Cc: Søren Christensen ***@***.***>; Mention ***@***.***>
Emne: Re: [globaleaks/GlobaLeaks] Passwords containing special Danish letters making passwords for recovery key impossible to retreive (Issue #3466)


Ekstern afsender
Thank you.

Actually what I made on this setup is to change the code of the account
recovery key request and i adding some log in

For this reason if you are encouraging issues on the password change is
because you are entering a password that do not satisfy the security level.
please check the message

**Comment by evilaliv3** [comment] 2023-06-20 06:23
Thank you @schris-dk 

Actually you just detected a different problem. Character  Æ is not recognized as capital because in software traditionally uppercase characters are characters from A to Z (english characters) and lowercase characters are characters from a to z.

For your test and screenshot please use the password: 

Actually due to how softwares works ÆAøÅqqqqql12345678#

**Comment by schris-dk** [comment] 2023-06-20 06:29
Hi Giovanni!
The PW provided works :-)

I've actually just had another customer, who had issues with pw containing these letters again, so it is actually an issue for the Danish users :-)

I'm happy that you have found the root cause of the problem - looking forward to the update to solve this :-) (and thnx for all your hard work :-))

**Comment by evilaliv3** [comment] 2023-06-20 06:58
@schris-dk did you test only the password change or do you confirm already that the issue is solved also for the original issue (Passwords containing special Danish letters making passwords for recovery key impossible to retreive
#3466) ?

**Comment by schris-dk** [comment] 2023-06-20 07:09
I tested the provided password against the "forced password change" upon admin account setup and subsequently also against the AccountRecoveryKey reveal :-)

**Comment by schris-dk** [comment] 2023-06-20 07:13
Hey - just tried to change the Recipient account password to the provided - it failed like with the admin account .....

**Comment by schris-dk** [comment] 2023-06-20 07:20
FYI - th PW you provided  "ÆAøÅqqqqql12345678#" works - however when using my previous used PW "ÆøÅqqqqql12345678#" (on REcipient account) - it fails - seems that there still is a char issue :(

**Comment by evilaliv3** [comment] 2023-12-13 18:51
Closing as it should be addressed by now.

Please feel free to reopen it if you still encounter this problem.

**Closed by evilaliv3** 2023-12-13 18:51 UTC
Labels: T: Bug, C: Backend
