### ISSUE TITLE
Exception generated after some questionnaire actions

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#3158] opened 2022-01-28 16:39 UTC
**Describe the bug**
When clicking "no" in identity section to not declare identity, or when click "add" in a multi-answer field, an exception is generated, 
and browser goes to login page.

**To Reproduce**
1. Fill a questionnaire identity field 
2. Answer "no" to identity declaration
3. Exception is generated, error stack attached
4. Same problem after click "add" in a multi-answer field

That's the error stack:
--------------------------------------------------------------------------------------------------------------
`URL: /

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0

Error Message: TypeError: e[t] is undefined

Stacktrace:
[
  {
    "columnNumber": 256088,
    "lineNumber": 64,
    "fileName": "https://myglobaleaks.it/js/scripts.min.js",
    "functionName": "isUploading",
    "source": "~~~~~~@~~~~~~://myglobaleaks.it/js/scripts.min.js:64:256088"
  },
  {
    "columnNumber": 114534,
    "lineNumber": 8,
    "fileName": "https://myglobaleaks.it/js/scripts.min.js",
    "functionName": "recurse/<",
    "source": "recurse/<@https://myglobaleaks.it/js/scripts.min.js:8:114534"
  },
  {
    "columnNumber": 117383,
    "lineNumber": 8,
    "fileName": "https://myglobaleaks.it/js/scripts.min.js",
    "functionName": "binary||/<",
    "source": "binary||/<@https://myglobaleaks.it/js/scripts.min.js:8:117383"
  },
  {
    "columnNumber": 101305,
    "lineNumber": 8,
    "fileName": "https://myglobaleaks.it/js/scripts.min.js",
    "functionName": "$digest",
    "source": "$~~~~~~@~~~~~~://myglobaleaks.it/js/scripts.min.js:8:101305"
  },
  {
    "columnNumber": 103102,
    "lineNumber": 8,
    "fileName": "https://myglobaleaks.it/js/scripts.min.js",
    "functionName": "$apply",
    "source": "$~~~~~~@~~~~~~://myglobaleaks.it/js/scripts.min.js:8:103102"
  },
  {
    "columnNumber": 151932,
    "lineNumber": 8,
    "fileName": "https://myglobaleaks.it/js/scripts.min.js",
    "functionName": "Rr/compile/</<",
    "source": "Rr/compile/</<@https://myglobaleaks.it/js/scripts.min.js:8:151932"
  },
  {
    "columnNumber": 17501,
    "lineNumber": 8,
    "fileName": "https://myglobaleaks.it/js/scripts.min.js",
    "functionName": "Rt",
    "source": "~~~~~~@~~~~~~://myglobaleaks.it/js/scripts.min.js:8:17501"
  },
  {
    "columnNumber": 20371,
    "lineNumber": 8,
    "fileName": "https://myglobaleaks.it/js/scripts.min.js",
    "functionName": "n",
    "source": "~~~~~~@~~~~~~://myglobaleaks.it/js/scripts.min.js:8:20371"
  }
]
`

**Comment by evilaliv3** [comment] 2022-01-28 17:43
Thank you @larrykind , it is likely that this issue is caused by the same behaviour that caused https://github.com/globaleaks/GlobaLeaks/issues/3146

I may have already fixed this withing 4.7.7 but i will for sure retry thiis but and get sure it is fixed within the next minor release.

When you creare reproducibility for a ticker if possible please upload for me a questionnaire that i could load to reproduce the issue! thank you!

**Comment by larrykind** [comment] 2022-01-31 08:35
ok @evilaliv3, will update to 4.7.7 and retry. Thanks

**Comment by larrykind** [comment] 2022-01-31 10:47
@evilaliv3 on 4.7.7 issue seems to be solved. thanks.

**Closed** 2022-01-31 10:47 UTC

**Comment by larrykind** [comment] 2022-03-04 17:16
@evilaliv3 this situation verifies also in 4.7.17 this case:
In my case in the send report page there is a mandatory "terms of service" field. If the report is about to be sent and "send" is clicked without check the mandatory flag and you "play" with that mandatory check and the "send" button, when you finally go to send the report, the send page remains stuck or redirection to login page: no key code is generated and no report is sent.
No exception is generated with this anomaly.
Could you please verify.

**Comment by evilaliv3** [comment] 2022-03-04 18:05
Is it possible for you to attach a simple questionnaire to replicate this?

This is always helpful to get sure to replicate the exact scenario

Thank you

**Comment by larrykind** [comment] 2022-03-07 08:35
@evilaliv3 thank you for the reply, 
test questionnaire is here:
[q2.zip](https://github.com/globaleaks/GlobaLeaks/files/8196061/q2.zip)

**Comment by evilaliv3** [comment] 2022-03-07 09:29
Thank you, i will try to retest this by today.

**Comment by larrykind** [comment] 2022-03-07 10:19
@evilaliv3 should it be possible to leave the send button disabled until all mandatory fields are checked, as done for withleblower identity backend and for additional questionnaire?

**Comment by evilaliv3** [comment] 2022-03-07 10:23
Actually this should be the situation already.

Can you describe me the bug with more detail and with an exact submission workflow for reproducing it.

**Comment by larrykind** [comment] 2022-03-07 11:28
ok @evilaliv3, sorry to generate uncomfort:
GL version: 4.7.17 - using previously attached questionnaire. I am using also this attached template for identity:
[identity_tpl.zip](https://github.com/globaleaks/GlobaLeaks/files/8197109/identity_tpl.zip)

In the questionnaire I attached before (with some mandatory fields), the "send button" is not disabled by default, anyway error check seems to work fine.

Coming back to the tocket topic, clicking "send button" with the empty questionnaire, and filling fields one by one and clicking send (that is enabled) for every mandatory field filled fot testing purposes, when report is about to be sent, sometimes page is stuck in "loading" status, sometimes redirected to login page: no exception is generated in GL 4.7.17. 
Unfortunately, I wasn't be able to regularly trigger the issue.
