### ISSUE TITLE
Date selection in "Postpone expiration date" is not working

### ISSUE THREAD

**Issue by schris-dk** [globaleaks/GlobaLeaks#3098] opened 2021-11-11 05:59 UTC
I'm in the process of creating a user manual, and has discovered, that the date selection feature in "Postpone expiration date" only allows to postpone 1 day

![image](https://user-images.githubusercontent.com/70965554/141245112-3d5e3d7d-dbde-4365-b2d7-19fde598bf05.png)

It is not possible to select another date in the calendar

Using GL 4.5.1

**Comment by evilaliv3** [comment] 2021-11-11 06:58
Hi @schris-dk this is not a bug but is a usability issue in relation to the limits on the choices of the date that we have currently defined following the discussions with users on https://github.com/globaleaks/GlobaLeaks/issues/3068

The postpone feature currently offer you the possibility to move forward the date of expiration and you can choose only dates lower than the default data retention policy. This limits are set in order to prevent users to anticipate existing expiration (that would result in a deletion) and postpone the expiration indefinitely.

In your retesting this happened:
- The default data retention policy is 3 months
- You made a report that was set to expire on 10 February 2020
- You tried immediately to postpone the date and the system offered you to chose a date between current expiration (10 February 2020) and maximum expiration that by policy you can choose today (10 February 2020).

Maybe to improve the situation we could accept to:
- decrease the date by half (e.g. if current expiration is set to be in 1 year,  make it possible to anticipate it by 6 months)
- increase the the date by the double of max expiration (e.g. if current policy is set to be in 1 year,  make it possible to set a date that is 2 years after the date on which the user make uses the postpone feature)

This way we would have constraints but the feature will appear always intuitive.

What do you think @schris-dk?

\cc @giorgiofraschini @maxmois @larrykind @cyberflaneuse ?

**Comment by evilaliv3** [comment] 2021-11-11 08:00
I consider that actually we could even accept to anticipate but only if the chosen expiration date is above the minimum value above the following:
- the current expiration date
- the expiration date calculated by the policy

This will make it possible to postpone today by the double of the policy, but also to rollback and set the exactly value of the policy.

This still will never enable to go below the exact value offered by the policy.

With this modification, there result that you would have got @schris-dk is the following:
![Screenshot_2021-11-11 GLOBALEAKS - Report](https://user-images.githubusercontent.com/217034/141260444-b97d67b0-c5b0-4603-937b-496159820400.png)

**Comment by schris-dk** [comment] 2021-11-11 10:36
One of the downsides to having the postpone date set by the number of days set in the Context menu is, that if you add a default retention period of 365 days, you will not receive a warning in 358 days, which is surpassed the 90 day case handeling time. 

A solution could be to add a "timer function" based on a "Latest case respond time", which is 90 days passed the initilal reporting date. This feature would give the option to set an expiration-/deletion date (like current expiration date) and a "Latest date of followup", where the whistleblower has to be notified at. Hereby you keep the data in your requested retention period and at the same time you are notified on expiring follow up dates

**Comment by evilaliv3** [comment] 2021-11-11 13:14
@schris-dk: Thank you for the feedback, i will keep this in mind for further development please keep different topic on different tickets if you can.

In relation to your original ticket scope, what do you think about the proposal of correction that i made?

**Comment by giorgiofraschini** [comment] 2021-11-11 13:47
i think it makes sense that the recipient could have the option to postpone the expiry date for the same amount of time set in the policy (e.g. policy 1 year, extension up to 2 years), with the possibility to extend the expiry date which is activable in any moment before the set policy time.
I am against the possibility to shorten the expiry date once it has been postponed, because the whistleblower may have seen an extension and it is not correct to "go back" from there.
In any case, and in compliance with GDPR principle, a good practice advice would be not to extend the expiry date at the last possible date but to a date which is reasonable to the process.

**Comment by evilaliv3** [comment] 2021-11-11 14:00
Thank you so much @giorgiofraschini. 

I actually consider your concern about anticipating the expiration very lecit and fair with respect to whistleblowers expectations.

If fine for everybody i will handler this "usability" issue enabling the user to choose a date up to the double the defined data retention policy.

**Comment by evilaliv3** [comment] 2021-11-11 14:44
I confirm that to handle this peculiar usability issue we decided that is acceptable for a user to set an expiration date exceeding the default data retention policy by one additional period.

E.g. if the policy is set to one year the user when postponing will be able to choose a date two years ahead.

Obviously users could face the same usability using twice the feature but at least this would happen less often and when users will have understood how the system works.

**Comment by evilaliv3** [comment] 2021-11-11 14:57
Closing; This improvement will be released in release 4.5.2

**Closed by evilaliv3** 2021-11-11 14:57 UTC
