### ISSUE TITLE
Regression on visualization of answers to fieldgroups introduced in version 4.3.0

### ISSUE THREAD

**Issue by aetdr** [globaleaks/GlobaLeaks#3053] opened 2021-09-24 12:41 UTC
Hi

After v4.3 upgrade, after a questionnaire is filled and submitted, both the whisteblower and the recipient can not see the answers. 

Steps and question groups are visible, but not the answers.

Have tried to create new questionnaires, and I get some mixed results. Sometimes the answers are shown, sometimes not.

**Comment by aetdr** [comment] 2021-09-24 12:51
Seem like only the default questionnaire works

**Comment by evilaliv3** [comment] 2021-09-24 13:01
Thank you for reporting this. I'm actually not able to reproduce the issue.

Have you tried creating a simple questionnaire in order to understand if the issue is caused by a special configuration ?

**Comment by aetdr** [comment] 2021-09-24 13:05
I have now reproduced it in 2 different instances - only the default questionnaire works.

There is no special configuration other than we are not using the english language.
Tried with a simple one too, with only one field. Did not work.

**Comment by evilaliv3** [comment] 2021-09-24 13:06
@aetdr: is it possible that on your platform you have enabled multiple languages but that you have configured by mistake your questions only in english?

Try to visit the platform changing the language and see if you see the answers.

**Comment by aetdr** [comment] 2021-09-24 13:19
Tried switching languages, it does not make any difference.
Also tried to remove all the questionnaires before adding a new one for testing. Still, only the default one or a duplicated version of it works.

**Comment by evilaliv3** [comment] 2021-09-24 16:07
Thank you @aetdr, i just fixed this regression with a patch that will be included in new release 4.3.2.

**Closed by evilaliv3** 2021-09-24 16:07 UTC
Labels: T: Bug, C: Client
