### ISSUE TITLE
UX & Backend bug in Certificate Enrolment trigger: EnvironmentError: Response unexpected on verify_hostname

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2193] opened 2018-03-04 09:58 UTC
Platform: 
Version: 3.0.7

EnvironmentError Base class for I/O related errors.

Traceback (most recent call last):

 File “/usr/lib/python2.7/dist-packages/twisted/internet/defer.py”, line 1128, in _inlineCallbacks
   result = g.send(result)

 File “/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/config.py”, line 78, in verify_hostname
   raise e

EnvironmentError: Response unexpected

**Comment by fpietrosanti** [comment] 2018-06-06 21:38
This bug happen because:
- Backend does not verify that hostname is null
- Client does allow to write an hostname that's not saved, but user click as action "generate" the certificate. 

The fix should be on the backend integrity check and on the client, skipping the need to save manually, if a new hostname has been typed in.

**Comment by DavidLemayian** [comment] 2019-09-02 09:50
I'm getting this error when trying to verify hostname. Blocking SSL certificate renewal. 🤔

**Comment by evilaliv3** [comment] 2019-09-02 18:07
@DavidLemayian: which version are you running?
We had an issue with Letsencrypt renewal that should be now solved starting from release 3.10.6

p.s. the update will solve the renewal issue but probably wont solve the verify hostname defect that is caused by a different issue still to be identified.

**Comment by DavidLemayian** [comment] 2019-09-09 08:40
Makes sense. Upgrade solved this. Thanks @evilaliv3 .

**Comment by evilaliv3** [comment] 2019-09-20 11:46
Closing as fixed.

**Closed by evilaliv3** 2019-09-20 11:46 UTC
Labels: C: Backend, C: Client, T: Bug
