### ISSUE TITLE
Error dist-packages/globaleaks/jobs/job.py", line 49 in globaleaks.log

### ISSUE THREAD

**Issue by zazzati** [globaleaks/GlobaLeaks#2573] opened 2019-05-22 13:29 UTC
globaleaks.log is full of error 

thon3/dist-packages/globaleaks/jobs/job.py", line 49, in run\n    yield self.operation()\n\ntwisted.internet.error.TimeoutError: User timeout caused connection failure.\n
2019-05-22 14:00:05+0200 [-] Stopping factory _HTTP11ClientFactory(<function HTTPConnectionPool._newConnection.<locals>.quiescentCallback at 0x7f1770573a60>, <twisted.internet.endpoints._WrapperEndpoint object at 0x7f1770a33240>)
2019-05-22 15:00:00+0200 [-] Starting factory _HTTP11ClientFactory(<function HTTPConnectionPool._newConnection.<locals>.quiescentCallback at 0x7f176cd481e0>, <twisted.internet.endpoints._WrapperEndpoint object at 0x7f1770323128>)
2019-05-22 15:00:00+0200 [-] Starting factory _HTTP11ClientFactory(<function HTTPConnectionPool._newConnection.<locals>.quiescentCallback at 0x7f176cd539d8>, <twisted.internet.endpoints._WrapperEndpoint object at 0x7f17702ac240>)
2019-05-22 15:00:05+0200 [-] [E] Job ExitNodesRefresh died with runtime 5156.0335 [low: 5014.0000, high: 5515.0000]
2019-05-22 15:00:05+0200 [-] Traceback (most recent call last):
2019-05-22 15:00:05+0200 [-]   File "/usr/lib/python3/dist-packages/globaleaks/jobs/job.py", line 49, in run
2019-05-22 15:00:05+0200 [-]     yield self.operation()
2019-05-22 15:00:05+0200 [-] twisted.internet.error.TimeoutError: User timeout caused connection failure.
2019-05-22 15:00:05+0200 [-] [E] Unhandled exception raised:
2019-05-22 15:00:05+0200 [-] [E] twisted.internet.error.TimeoutError User timeout caused connection failure\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/globaleaks/jobs/job.py", line 49, in run\n    yield self.operation()\n\ntwisted.internet.error.TimeoutError: User timeout caused connection failure.\n
2019-05-22 15:00:05+0200 [-] Stopping factory _HTTP11ClientFactory(<function HTTPConnectionPool._newConnection.<locals>.quiescentCallback at 0x7f176cd481e0>, <twisted.internet.endpoints._WrapperEndpoint object at 0x7f1770323128>)
2019-05-22 15:00:05+0200 [-] [E] Job UpdateCheck died with runtime 5029.0000 [low: 5029.0000, high: 5029.0000]
2019-05-22 15:00:05+0200 [-] Traceback (most recent call last):
2019-05-22 15:00:05+0200 [-]   File "/usr/lib/python3/dist-packages/globaleaks/jobs/job.py", line 49, in run
2019-05-22 15:00:05+0200 [-]     yield self.operation()
2019-05-22 15:00:05+0200 [-] twisted.internet.error.TimeoutError: User timeout caused connection failure.
2019-05-22 15:00:05+0200 [-] [E] Unhandled exception raised:
2019-05-22 15:00:05+0200 [-] [E] twisted.internet.error.TimeoutError User timeout caused connection failure\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/globaleaks/jobs/job.py", line 49, in run\n    yield self.operation()\n\ntwisted.internet.error.TimeoutError: User timeout caused connection failure.\n

The platform seems work correctly but... log are totally full of this errors. 
Any idea ?

**GlobaLeaks version:**
3.8.5 

**Browser:**
N.A.

**Server Operating System and Version (if applicable):**
Ubuntu Bionic

**Comment by evilaliv3** [comment] 2019-05-23 08:38
Good morning @zazzati,  

Actually the error reported is related to a connection failure happened in the job that checks about the updates. I expect so that the issue is related to a failing https connection. Is your system able to reach deb.globaleaks.org via HTTPS?

**Comment by zazzati** [comment] 2019-05-23 09:37
Our VPS are in private subnet and use of proxy is mandatory. 

Configuration of proxy is in global enviroment, by setting http_proxy and https_proxy variabile. 

The update of globaleaks work correctly... 

Does Gl use for all its features che global proxy settings ?

**Comment by evilaliv3** [comment] 2019-05-23 12:58
No actually. GlobaLeaks right do not allow configuration of HTTPS proxy settings.

\cc @fpietrosanti

**Comment by evilaliv3** [comment] 2022-03-26 08:28
Closing as duplicated: https://github.com/globaleaks/GlobaLeaks/issues/3128

**Closed by evilaliv3** 2022-03-26 08:28 UTC

**Comment by santy313** [comment] 2024-04-26 10:55
Good afternoon,

I have version 4.11.5 installed and I am experiencing the following error.
![Screenshot_1](https://github.com/globaleaks/GlobaLeaks/assets/12232865/331af00e-e0b4-4731-a03f-feb91c54f6d7)


I have checked the changelogs and theoretically it's resolved.
However, in my case, I still have the same error.
Has this error been fixed?
In which version was it fixed?
Does this error affect email delivery?
