### ISSUE TITLE
Make it possible to insert a text region

### ISSUE THREAD

**Issue by obiuan81** [globaleaks/GlobaLeaks#2566] opened 2019-05-06 15:05 UTC
Hi all,
it could be nice if it wuold be possible to insert a "text region" in the questionaire with no interaction with the user.

Something like "make this text region visible if the answer to the question X was Y"...

This request originates from particular disclaimer management purposes.

Regards

**Comment by evilaliv3** [comment] 2019-05-06 15:44
Thank you @obiuan81, can you please check ticket https://github.com/globaleaks/GlobaLeaks/issues/2564?

Is that what you are asking for? if yes you will find it in the upcoming release 3.8.0

**Comment by obiuan81** [comment] 2019-05-06 15:57
Hi @evilaliv3  ,
yes it's very similar but I think it could be more usefull if the "text region" could be added as questionaire item, as done for any other questions at the moment.
In this way the text can be added in relation or not with other questions or answers.

**Comment by evilaliv3** [comment] 2019-05-07 16:16
Closing as duplicate of https://github.com/globaleaks/GlobaLeaks/issues/2564

**Closed by evilaliv3** 2019-05-07 16:16 UTC
