### ISSUE TITLE
Questionnaire: All questions set to mandatory

### ISSUE THREAD

**Issue by jschibberges** [globaleaks/GlobaLeaks#2495] opened 2019-01-23 16:25 UTC
**Current behavior**

After upgrading from GlobaLeaks version 3.3.16 to 3.6.5 all question in our questionnaire were marked to mandatory when filling out the questionnaire. Those that were actually configured to be mandatory were visually highlighted but all questions needed to be filled out to advance the questionnaire. In the admin interface, only those questions intended to be mandatory where configured as such. 

A new questionnaire was created to test whether this was just an issue with the questtionnaire created under the previous version. The newly created questionnaire showed the same behaviour tough.

**Expected behavior**

When filling out the questionnaire only those questions configured to be mandatory should prevent the user from completing the questionnaire.

**Steps to reproduce the problem or feature illustration**

**What is the motivation or use case for changing the behavior?**

When all questions are mandatory, many users will not be able to fill out the questionnaire without either entering dummy or false data. Likely many users will abort the questionnaire.

**GlobaLeaks version:**

GlobaLeaks 3.6.5 (Update from 3.3.16)

**Browser:**

Firefox 64.0.2 / Chrome 71.0.3578.98 / Edge 42.17134.1.0

**Server Operating System and Version (if applicable):**
 
Ubuntu 16.04

**Client Operating System and Version (if applicable):**

Windows 10 1803

**Comment by mryber** [comment] 2019-01-24 07:48
I have the same issue, upgrading from 3.6.0 to 3.6.5, basically all fields are set as mandatory. I even tried to create new questions without enabling mandatory, and they are still shown as mandatory. I tried downgrading to 3.6.4 and all field are shown as they should be shown.

**Comment by evilaliv3** [comment] 2019-01-24 09:18
Thank you both, we are rolling out a fix that will solve the issue.

It will be included in 3.6.6 by today.

\cc @DavidLemayian

**Comment by evilaliv3** [comment] 2019-01-24 09:54
@jschibberges @mryber: i'm currently not able to reproduce the issue.

I'm testing on linux with both chrome and firefox.

would you please attach some screenshot and a questionanire with the error?
you could export it via the admin interface by clicking the Export button.

**Comment by mryber** [comment] 2019-01-24 10:48
@evilaliv3 - are the test you do to reproduce, running from a clean install or from a previous configured setup? I am trying to upgrade from 3.5.8 to test it again, and will try to do a clean install, just to see if it shows up on a clean install or only from a previous setup. In my case I used to upgrade from 3.5.8 to 3.6.0 and then to 3.6.5 and I can see that @jschibberges also comes from an earlier version, so maybe the issue is related an ealier version and not a clean install... :-)

**Comment by mryber** [comment] 2019-01-24 12:06
Update: I reproduced this issue from upgrading from 3.5.8 to 3.6.5, will now test a new installation directly with 3.6.5

**Comment by mryber** [comment] 2019-01-24 12:13
Update: Just tested from a clean install, and the standard questionaire also says that Short title and Full description is mandatory. And i tried from a brand new Tab in Firefox and a new Firefox browser client. I have seen the issues on Firefox on both Linux and Windows 10, and with Chrome as well.
I have not tested from a clean 3.6.3/3.6.4 upgraded to 3.6.5.

**Comment by mryber** [comment] 2019-01-24 16:20
I made a screenshot of the default questionaire saying all fields are mandatory:
https://github.com/globaleaks/GlobaLeaks

**Comment by mryber** [comment] 2019-01-24 17:05
... so I did yet another test, a complete new ubuntu 18.04.1 LTS host, installed 3.6.5, issue there, I then downgraded it to 3.6.4, and issue still persists. I then took an old 3.5.8 which was upgraded to 3.6.5 which got the issue after upgrade, then downgraded that one to 3.6.4, and the issue was gone, just like on some other systems I work with. So it seems like there is an issue in 3.6.5 overall, but again, with old versions, the issues only shows up on 3.6.5, but with a brand new 3.6.5 setup and a downgrade to 3.6.5, the issue hangs on... hmmmm

**Comment by evilaliv3** [comment] 2019-01-24 18:21
Thank you both!

The issue has been identified and is due to an error in the latest angularjs: https://github.com/angular/angular.js/issues/16814

We will now rollback angular to 1.6.5 waiting for an upstream patch.

This correction will be included by today in release 3.6.6

**Comment by evilaliv3** [comment] 2019-01-28 14:22
Thank you @mryber, i'm happy you managed to solve.

I guess in the specific test passing from 3.6.5 and upgrading to 3.6.7 your test was affected by the browser cache. Just a browser refresh would have solved the situation because the fix is version independent.

Closing the ticket as fixed.

**Closed** 2019-01-28 14:22 UTC
Labels: C: Client, T: Bug
