### ISSUE TITLE
The Wizard does not enforce the configuration of strong password leading to error

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1441] opened 2015-10-16 14:23 UTC
The Configuration Wizard does not enforce the configuration of strong password leading to an backed validation error when the configuration is finalized.

The Wizard shall prevent the user from going forward without typing a non compliance password (i tried "blahblahblah" and it worked.

**Comment by evilaliv3** [comment] 2015-10-16 14:27
This is probably a regression due to a change that i did.

I will investigate and fix the issue.

**Comment by evilaliv3** [comment] 2015-11-02 14:58
Yep i confirm that this has been fixed in current devel as was simply a regression.

The fix will be shipped in release 2.60.114

**Closed by evilaliv3** 2015-11-02 14:59 UTC
Labels: C: Client, T: Bug
