### ISSUE TITLE
Add Dockerfile to install with Docker

### ISSUE THREAD

**Issue by misjoinder** [globaleaks/GlobaLeaks#692] opened 2013-11-03 04:39 UTC
I've been looking into whether the install process could be simplified with Docker. The Dockerfile which I'm using sets up GlobaLeaks GLClient and GLBackend on an Ubuntu VM. I'm testing it on AWS -  the server runs, but ports aren't working yet. Once it does work, setting up GlobaLeaks it should just be as easy:

```
docker build -t globaleaks - < globaleaks.dockerfile
docker run -p 80:8082 -t globaleaks globaleaks/GLBackend/bin/globaleaks -z -d
```

or if it were included in the GitHub repo

```
docker build -t globaleaks - < github.com/globaleaks/GlobaLeaks
```

It's similar to #179 which was working on setting up GlobaLeaks using Vagrant.

Here's the Dockerfile:

```
# GlobaLeaks
#
# VERSION   1.0

# use ubuntu base image provided by dotCloud
FROM ubuntu

# install Python tools
RUN apt-get -y install python-software-properties

# install Tor
RUN add-apt-repository 'deb http://deb.torproject.org/torproject.org precise main'
RUN gpg --keyserver x-hkp://pool.sks-keyservers.net --recv-keys 0x886DDD89
RUN gpg --export A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89 | apt-key add -
RUN apt-get update
RUN apt-get -y install tor tor-geoipdb curl

# set Tor to automatically start on boot
#RUN update-rc.d tor defaults

# install Python tools
RUN apt-get -y install git python-setuptools python-dev build-essential

# install and prepare pip
RUN easy_install pip
RUN pip install --upgrade pip
RUN pip install --upgrade virtualenv

# install GlobaLeaks requirements.txt
RUN pip install Twisted==13.1.0
RUN pip install apscheduler==2.1.1
RUN pip install zope.component==4.1.0
RUN pip install zope.interface==4.0.5
RUN pip install cyclone==1.1
RUN pip install Storm==0.20
RUN pip install transaction==1.4.1
RUN pip install txsocksx==1.13.0.0rc2
RUN pip install Parsley==1.2
RUN pip install pycrypto==2.6
RUN pip install scrypt==0.6.1
RUN pip install python_gnupg==0.3.5

# Prepare GlobaLeaks directory
RUN mkdir globaleaks

# Download GLBackend
RUN git clone https://github.com/globaleaks/GLBackend.git globaleaks/GLBackend
RUN export PYTHONPATH=`pwd`

# Install NodeJS
RUN echo "deb http://archive.ubuntu.com/ubuntu precise universe" >> /etc/apt/sources.list
RUN add-apt-repository ppa:chris-lea/node.js
RUN apt-get update
RUN apt-get -y install nodejs

# Download GLClient and build using Bower
RUN git clone https://github.com/globaleaks/GLClient.git globaleaks/GLClient
RUN npm install -g grunt-cli bower
RUN ( cd globaleaks/GLClient | bower update -f --allow-root )

# Configuring Tor - not yet set up

# give daemon permission on GlobaLeaks server
RUN chown -R daemon globaleaks/GLBackend
USER daemon
EXPOSE 8082
```
##

**Comment by vodkina** [comment] 2016-12-15 19:28
https://github.com/globaleaks/GlobaLeaks/tree/master/appliance

**Comment by evilaliv3** [comment] 2016-12-15 21:44
This ticket is in my opinion still interesting.

The Appliance as you are saying is now integrated in globaleaks, not update because it does work.

Some additions have been done recently but are still to be integrated in master (are currently in the branch 16.04)

**Comment by ckeeney** [comment] 2017-11-03 03:05
I've created a working Docker image for GlobaLeaks.  The repo for that is [here](https://github.com/ckeeney/docker-globaleaks).  

It needs a little work still.  I'm not thrilled about running Tor and GlobaLeaks in the same container, but it makes the usage really simple.  It also needs documentation and support for mounting volumes in the appropriate places to prevent data loss.

Also, in production I let Traefik or Caddy have ports 80 and 443 on my servers.  They handle Let's Encrypt SSL stuff, and proxy traffic to other containers.  I haven't tried the SSL Let's Encrypt stuff for Globaleaks and probably won't use it.  If that or anything else in my docker image needs a pull request please don't be shy.

I wasn't sure where to put this comment.  #1622 is kind of a duplicate of this issue.

Issue #579 is "Detect if the GlobaLeaks instance is being installed or started from an LXC container, preventing it from starting up".  Unless I'm mistaken, if that change gets implemented then it won't be possible to run GlobaLeaks in Docker.

**Comment by NSkelsey** [comment] 2017-11-03 09:07
@ckeeney #1686 is not going to be implemented. 

If you find a nice way to produce backups from volumes please share. We are looking for good backup strategies.

RE splitting tor into another container: GlobaLeaks needs access to tor's SOCKS proxy (port 9050) and vice versa for Tor (GL on 8083). If you look in `/debian/app/usr.bin.globaleaks` you can the two files GlobaLeaks uses to send commands into to configure its hidden service.

**Comment by ckeeney** [comment] 2017-11-03 15:48
@NSkelsey I'm not in a huge hurry to split off Tor.  There are however 3 bigger issues with my Docker Image

- GlobaLeaks logs are written to a logfile instead of come through to the Docker Host via stdout from the container.
- If GlobaLeaks dies or otherwise stops for any reason, the Docker container keeps running because the foreground process is `sleep`.
- If you try to stop the container with `docker stop <container-name>`, the container does not stop gracefully.  Force killing containers risks triggering [a very nasty and long-running bug](https://github.com/moby/moby/issues/5618#issuecomment-280078302)

However, if we could run Globaleaks as the root user, then it will be possible to simply run Globaleaks in the foreground in the docker container.  This should simultaneously solve all 3 of these issues.  

All of these problems are related to the fact that I'm running GlobaLeaks as a daemon in the background of the container.  When I try to run the GlobaLeaks in the foreground of the docker container, I get

```
Starting GlobaLeaks…
Invalid user: cannot run as root
```

Maybe we should add a `--run-as-root-anyways` type flag to bypass the root restriction.

**Comment by ckeeney** [comment] 2017-11-03 15:53
@NSkelsey regarding backups of the data in the volumes, I am mounting my volumes on the host and plan on just using [the documented backup strategy](https://github.com/globaleaks/GlobaLeaks/wiki/Backup-Guide):

```bash
date=`date +"%Y-%m-%d"`
version=`dpkg -l | awk '$2=="globaleaks" { print $3 }'`
tar zcvfp /tmp/globaleaks-backup-$date-$version.tar.gz /var/globaleaks/ /etc/default/globaleaks
```
It will of course need modified since the `version` string will not get defined on the host and the folders are wherever you happened to mount them on the docker host.

I don't currently need to backup the settings file at `/etc/default/globaleaks`, but if I did I would just mount my settings file there from the host and manage all the backups from the host.

**Comment by evilaliv3** [comment] 2017-11-04 20:39
thanks @ckeeney for all you feedback.

surely we could make ```--run-as-root-anyway``` if you think this is the only way to support this use case.

using ```-n``` you will communicate the APP to not go in background and will print on the terminal in stdout/stderr.

could you then please elaborate about point 3? "If you try to stop the container with docker stop <container-name>, the container does not stop gracefully. Force killing containers risks triggering a very nasty and long-running bug" ???

**Comment by ckeeney** [comment] 2017-11-04 21:20
There are certainly other ways to support this use case, but that is the most straight forward.  An ideal docker container would not be running upstart or any other daemon manager, but would just run the only process it runs in the foreground.  It is also possible to create non-root users for a docker image, but that often leads to other issues.

As for point 3, if you check my repo, the entrypoint of the docker image is [`docker-entrypoint.sh`](https://github.com/ckeeney/docker-globaleaks/blob/master/docker-entrypoint.sh).  Typically, a docker image entrypoint is a single process that runs indefinitely, or at least, when the process dies, the container stops.  In my case, the entrypoint spawns off 2 daemons, and then sleeps indefinitely.  I haven't debugged it much, but the following steps reliably reproduce this issue:
1. Execute `docker run ckeeney/globaleaks`.  This will run GlobaLeaks (but without the required NET_ADMIN capability, it may not work properly but is not relevant to this issue)
2. Try to simply `Ctrl-C` to stop the container and go back to your terminal.  You will see it just printing `^C` into the terminal but without stopping the container.  In fact, even if you ran `docker run -d ckeeney/globaleaks`, it would start up the container and then send it to the background.  If you then try to stop the container with `docker stop ...`, it will try to stop the container gracefully for 10s and then force kill the container with a `SIG_KILL`.

Stopping a container ungracefully has been shown to be one of several ways you can run into the nasty long running bug i linked above.  It is some kind of race condition and so it doesn't happen every time. 
 Typically, if you have a docker host get into the state described by that bug, the only way to remedy the situation is the reboot the entire docker host.

**Comment by evilaliv3** [comment] 2017-11-05 09:21
Thanks again @ckeeney!

We really would like to support this use case the best possible. 

Could you please summarize all the required changes?

As @NSkelsey was suggesting connecting and configuring Tor in a different container would be possible accessing an and a port of the external Tor docker. I would suggest to let's first try to do a single image and then consider this an improvement.

As for the the shutdown couldnt you use service stop? Globaleaks internally will start performing the shutdown and if some activities are ongoing will eventually shut down with a max timeout currently configured to 60 seconds

**Comment by ckeeney** [comment] 2017-11-05 18:38
I just opened a Work-in-progress PR.  The `Dockerfile` in my PR is a bit different from the one in my own repo.  This is because if the Dockerfile is going to live here, it should build GlobaLeaks rather than install from the apt repo.  

If we only install from the app repo, then updates won't hit DockerHub until after updates hit the apt repo.  Additionally, it would be impossible to try out different versions and branches of GlobaLeaks in a docker container since all the Docker images would be installing from apt.  Finally, building the app in Docker lets us setup nice DockerHub automated builds from this repo.

**Comment by ckeeney** [comment] 2017-11-05 18:48
@evilaliv3:  I didn't mean to ignore your last question.  Docker containers run exactly one process on start.  If that process wants to spawn some other processes, that's fine.  However, when the initial process dies, the container stops.  If we wanted to utilize `service stop`, we could.  This would require creating a `docker-entrypoint` that spawns tor, spawns GlobaLeaks, (hopefully) relays logs back to stdout of the Docker container, and also handle signals passed in from Docker, including calling `service stop` when a `SIG_TERM` comes in.  Also, this process should be monitoring the GlobaLeaks process and this process should die when GlobaLeaks dies, so that the container stops.

This is all possible, but I don't think the effort gains us much.  While not unheard of, init systems like systemD, upstart, initd are not commonly used inside Docker.  This is because if you are using docker containers, you should consider them disposable.  If something goes wrong inside my GlobaLeaks container, I like knowing I can just run `docker-compose down;  docker-compose up;` and i should have a fresh install, and all my data is already mounted because of the volumes mounted from within `docker-compose.yml`.

**Comment by evilaliv3** [comment] 2017-11-05 22:27
1) regarding apt/build: globaleaks in production should install only from signed sources, this is the main reason we install only via APT; it is then not clear to me how docker handlers signatures of its own scripts, could you please clarify if you already know about this topic?

2) regarding systemd/upstart: ok, what you can so is to send globaleaks signal SIGTERM and it should start the shutdown procedure, then checking for the pid file deletion you could whait for effective shutdown

**Comment by ckeeney** [comment] 2017-11-05 23:20
1.  I have never dealt with signing docker images.  When you issue a `docker pull <image>`, the docker image is downloaded over HTTPS so a MITM would be quite a challenge.  If we want even more security, Docker does have [support for signing images](https://docs.docker.com/engine/security/trust/content_trust/).  It appears that the docker client does not use any of the signing by default, so if that is the route we want to go we should make sure to include instructions on enabling the docker content trust in the docker usage instructions.


2. That sounds like the plan, and it is almost ready since GlobaLeaks is running in the foreground of the container.  For some reason it still didn't stop gracefully for me yet, and I still haven't looked into it.  I'm not sure how important the PID file is in docker.  Once the GlobaLeaks process stops, the Docker container and all processes inside of it immediately stop.

**Comment by evilaliv3** [comment] 2019-05-29 22:32
Closing as implemented: https://github.com/globaleaks/GlobaLeaks/tree/master/docker

**Closed by evilaliv3** 2019-05-29 22:32 UTC
