### ISSUE TITLE
Bug with IP filtering in multitenant setup

### ISSUE THREAD

**Issue by aetdr** [globaleaks/GlobaLeaks#3041] opened 2021-09-07 18:09 UTC
Hi

In a multisite setup, if an allow-access IP range is defined at both the root tenant (TID 1) and some other tenant, and the two ranges are not equal, the range defined at the root tenant gets applied to subtenant access validation.
This is only the case when the subtenant is accessed via a subdomain. If subtenant accessed by the path, than the locally defined IP range gets applied and it works.

An example:

-	I want to limit administrative access to the root tenant to local IPs only, and define allowed cidr range to 10.20.0.0/16 at root.org
-	site20 tenant should be accessible  from inside our network both internally and externally. I set allowed IP ranges to 10.20.0.0./16 and 200.200.0.0/16
-	If I try to access the subtenant by using its subdomain site20.root.org from 200.200.1.2, I get an error
-	If I try to access the same site, from the same address, by using the path https://root.org/t/20/ instead, it works fine
-	If I modify the allow IP filter at the TID 1 level  by adding 200.200.0.0/16, it works both ways

**Comment by evilaliv3** [comment] 2021-09-07 21:59
Thank you for reporting this @aetdr1 i just retried to reproduce your issue but i'm currently not able to reproduce it.

Have you already tested it on a clean setup to see if the bug is reproducible?

**Comment by aetdr** [comment] 2021-09-08 14:36
Hi @evilaliv3 

I tried once again and the error is reproducable.

- You are allowed to browse the site as an anonymous user. It is first when you enter credentials and click on the submit button that the error pops up.
- REST response 401: {"error_message": "IP Address not allows to login from this location", "error_code": 16, "arguments": []}
- Do not know if this has any impact, but we actually use netmask 21 so it is 200.200.0.0/21 in the previous example

**Comment by aetdr** [comment] 2021-09-08 14:41
Can se that the request actually is the issue (tid=0 is not right):

{"tid":0,"username":"recipient","password":"removed","authcode":""}

**Comment by evilaliv3** [comment] 2021-09-09 12:25
Thank you for the feedback @aetdr, we will proceed rechecking the issue.

Actually tid=0 in the implementation is correct and used to notify the server that the proper tid has to be read from the hostname but probably there is something else not working.

**Comment by evilaliv3** [comment] 2021-09-09 15:03
Thank you @aetdr , i've identified the bug and the fix that will be included in upcoming release 4.3.0

The bug always existed in relation to secondary tenants that were all enforcing the configuration of the root tenant and ignoring their own configuration.

**Closed** 2021-09-09 15:03 UTC
Labels: T: Bug, C: Backend
