### ISSUE TITLE
Suddenly unable to load the report page

### ISSUE THREAD

**Issue by MHHBAB** [globaleaks/GLOBALEAKS#4186] opened 2024-09-12 08:03 UTC
### What version of GlobaLeaks are you using?

Latest 5.0.6

### What browser(s) are you seeing the problem on?

Chrome, Microsoft Edge, Other

### What operating system(s) are you seeing the problem on?

Windows, Android

### Describe the issue

Have been running GlobaLeaks for a couple of years without any issues.
Today i got notified by a user that the report an issue page does no longer load.

The welcome page loads perfectly and so does the admin pages.
I have updated to latest version of Globaleaks but the issue still persists

When clicking on the report a concern button the middle section of the page goes blank(white) and a short animation of a circle spinning shows for a fraction of a second.

Topbanner and fotter is still visible

This has been tested on Edge, Chrome and android mobile browsers like chrome and samsung internet.

### Proposed solution

Could it be some legacy CSS that makes it get stuck?
In Edge DevTools it warns about deprecated -ms-high-constrast

**Comment by evilaliv3** [comment] 2024-09-12 08:40
Hello 

Thank you.

The problem is probably only visual since the version 5 includes significant changes, but do not worry we could solve it easily.

I just need some more input about the problem.

Would you please share me a link to the platform or reach me on community.globaleaks.org?

**Comment by evilaliv3** [comment] 2024-09-12 09:05
Closing the ticket as managed with the user; No bug exist and the issue lied on an incorrect user configuration.

**Closed by evilaliv3** 2024-09-12 09:05 UTC
Labels: T: Bug, C: Client
