### ISSUE TITLE
Disclaimer modal panel is shown two times

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#2861] opened 2020-06-01 13:51 UTC
**Current behavior**

After clicking "next" in disclaimer window, the window is shown again while the background switches to questionnaire.

**Expected behavior**

After clicking "next" in disclaimer window, the window should disappear and the background should switch to questionnaire.

**Steps to reproduce the problem or feature illustration**

1. As admin, In tenant's homepage settings set Disclaimer
2. Fill a questionnaire: Disclaimer is shown.
3. Click "proceed" in the disclaimer window: 
4. Background page switches to the questionnaire: -> disclaimer is shown again

**What is the motivation or use case for changing the behavior?**

After clicking "proceed" the disclaimer modal should disappear.

**GlobaLeaks version:**

4.0.25

**Browser:**

Firefox 76 Chrome 83.0.4103.61

**Server Operating System and Version (if applicable):**
 
debian 10.3 buster

**Client Operating System and Version (if applicable):**

windows 10

**Comment by evilaliv3** [comment] 2020-06-01 16:45
Thank you @larrykind 

this seems to be a regression related to https://github.com/globaleaks/GlobaLeaks/commit/f28e270969db9dc88f79c7ce1acdd490ad9738d1.

I will just revert this commit till we identify the proper fix. thank you.

**Comment by evilaliv3** [comment] 2020-06-01 16:49
Fixed with commit: https://github.com/globaleaks/GlobaLeaks/commit/2df6d4af3eb6710c32a94a4b800b73a14dd3445e

**Closed by evilaliv3** 2020-06-01 16:49 UTC
Labels: C: Client, T: Bug
