### ISSUE TITLE
Exception AttributeError: languages_enabled on version  3.0.16

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2229] opened 2018-03-24 11:26 UTC
Platform: try.globaleaks.org
Host: try.globaleaks.org (bvidswzoj322engc.onion)
Version: 3.0.16

AttributeError Attribute not found.

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 183, in process
    self.render(resrc)

  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 234, in render
    body = resrc.render(self)

  File "/usr/lib/python2.7/dist-packages/globaleaks/rest/api.py", line 328, in render
    self.preprocess(request)

  File "/usr/lib/python2.7/dist-packages/globaleaks/rest/api.py", line 311, in preprocess
    request.language = unicode(self.detect_language(request))

  File "/usr/lib/python2.7/dist-packages/globaleaks/rest/api.py", line 465, in detect_language
    if l in State.tenant_cache[request.tid].languages_enabled:

  File "/usr/lib/python2.7/dist-packages/globaleaks/utils/objectdict.py", line 9, in __getattr__
    raise AttributeError(name)

AttributeError: languages_enabled

**Comment by NCommander** [comment] 2018-03-26 10:00
Looked into this. Unable to reproduce but I can see the root cause. The fundamental problem is languages_enabled doesn't exist as an attribute of TenantState in state.py. It's dynamically set on the fly by db/__init__.py when state is loaded.

The code that does that is this:
```
    for tid, lang in models.EnabledLanguage.tid_list(session, tid_list):
        State.tenant_cache[tid].setdefault('languages_enabled', []).append(lang)
```

So languages_enabled only gets set if that loop gets executed. Otherwise the attribute fails to exist and we get a code explosion. I feel like there's a more to this bug than first glance but here since that model could only be [] if a tenant has no enabled languages which seems wrong.

**Comment by NCommander** [comment] 2018-03-26 10:52
Managed to reproduce it:

```
2018-03-26 10:43:09+0000 [HTTPChannel,1,127.0.0.1] Unhandled Error
        Traceback (most recent call last):
          File "/home/mcasadevall/src/GlobaLeaks/backend/glenv/lib/python2.7/site-packages/twisted/web/http.py", line 1408, in dataReceived
            finishCallback(data[contentLength:])
          File "/home/mcasadevall/src/GlobaLeaks/backend/glenv/lib/python2.7/site-packages/twisted/web/http.py", line 1673, in _finishRequestBody
            self.allContentReceived()
          File "/home/mcasadevall/src/GlobaLeaks/backend/glenv/lib/python2.7/site-packages/twisted/web/http.py", line 1736, in allContentReceived
            req.requestReceived(command, path, version)
          File "/home/mcasadevall/src/GlobaLeaks/backend/glenv/lib/python2.7/site-packages/twisted/web/http.py", line 762, in requestReceived
            self.process()
        --- <exception caught here> ---
          File "/home/mcasadevall/src/GlobaLeaks/backend/glenv/lib/python2.7/site-packages/twisted/web/server.py", line 183, in process
            self.render(resrc)
          File "/home/mcasadevall/src/GlobaLeaks/backend/glenv/lib/python2.7/site-packages/twisted/web/server.py", line 234, in render
            body = resrc.render(self)
          File "/home/mcasadevall/src/GlobaLeaks/backend/globaleaks/rest/api.py", line 328, in render
            self.preprocess(request)
          File "/home/mcasadevall/src/GlobaLeaks/backend/globaleaks/rest/api.py", line 311, in preprocess
            request.language = unicode(self.detect_language(request))
          File "/home/mcasadevall/src/GlobaLeaks/backend/globaleaks/rest/api.py", line 469, in detect_language
            if language is None or language not in State.tenant_cache[request.tid].languages_enabled:
          File "/home/mcasadevall/src/GlobaLeaks/backend/globaleaks/utils/objectdict.py", line 9, in __getattr__
            raise AttributeError(name)
        exceptions.AttributeError: languages_enabled
```

I got this result with a TID missing from the enablelanguage table. The following query should reveal any and all tenants with this problem:

```
SELECT s.id,s.tid,el.name FROM signup AS s LEFT JOIN enabledlanguage AS el ON s.tid=el.tid WHERE s.tid != '' AND el.name IS NULL;```

I'd like to know if the actual problem is missing DB data so if someone can run this on the try.globaleaks.org database and see if it gets any results, that should move us towards getting a proper patch written. At a minimium, it's likely worth setting a sane default if enablelanguages is completely MIA though.

**Comment by evilaliv3** [comment] 2018-03-26 12:26
@NCommander: the result of the wuery is ```1|2|```

**Comment by NCommander** [comment] 2018-03-26 12:28
So the first signup/TID 2 is missing a language. If you try and log into that tenant, it will likely explode with this exception.

**Comment by evilaliv3** [comment] 2018-03-26 17:35
I confirm this analysis @NCommander 
for the moment i've not found a way to reproduce it causing the bug from the web interface.
Its possible that the bug was related to some bugs in one of the first version 3.0.X now fixed.

let's keep the ticket open for a while.

**Comment by evilaliv3** [comment] 2020-05-19 20:51
Closing as outdated.

**Closed by evilaliv3** 2020-05-19 20:51 UTC
Labels: T: Bug
