### ISSUE TITLE
Custom questions templates for "group of questions" - activation triggers options not shown

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#2837] opened 2020-04-30 12:55 UTC
**Current behavior**

During the creation of a custom question group template (for custom identity template), activation triggers are not working. 
I tried with just a single line text field to be activated by a previously set select field with couple of options.

**Expected behavior**

Activation conditions of custom template fields should work as in the normal questionnaire backend behavior.
To the receiver side, the optional fields could be shown as empty, or not shown at all if not filled.

**Steps to reproduce the problem or feature illustration**

1. Create custom question  template selecting "group of questions"
2. Create a select field with some options and save
3. Create a single line (or whatever) input field and go to "activation triggers" -> Nothing is shown. 
Expected the options previously created to be shown as a triggers.

**What is the motivation or use case for changing the behavior?**

To match the behavior of the questionnaire building with custom group questions also.

**GlobaLeaks version:**

v4.0.18

**Browser:**

Firefox 75, Chrome 81.0.4044.122

**Server Operating System and Version (if applicable):**
 
debian 10.3 buster

**Client Operating System and Version (if applicable):**

windows 10

**Comment by evilaliv3** [comment] 2020-04-30 17:03
Thank you the @larrykind , the general bug reported is now fixed.

There is still a minor defect related to the fact that sometimes one sees only options after a page reload that is due to the fact that we miss proper object update but this will be fixed later on at global level.

**Closed by evilaliv3** 2020-04-30 17:03 UTC
Labels: C: Backend, C: Client, T: Bug

**Comment by larrykind** [comment] 2020-05-27 10:18
@evilaliv3 in v. 4.0.24 activation triggers are shown when you set them up, then not saved i guess. So if page is refreshed, triggers just inserted are not there.

**Comment by evilaliv3** [comment] 2020-05-27 11:22
Thank you @larrykind, regression confirmed.

I will try to fix this and as well as for other fixes made to work on implementing automatic testing of this features.

Is there any developer on your side that could eventually support on this aspects so to complete the implementation of the automatic testing for the feature that are currently not covered?

**Comment by evilaliv3** [comment] 2020-05-27 11:26
Thank you @larrykind.

Actually at the current time i'm not able to reproduce this.

The interfaces sometimes requires to be refreshed before crating triggers but aside from this it works on my side.

Would you please provide instructions to reproduce the bug you are encountering?

I will try as well to add this set of features on automatic testing so to identify regressions at early stage.

p.s. Is there any developer on your side that could eventually support on this aspects so to complete the implementation of the automatic testing for the feature that are currently not covered?

**Comment by larrykind** [comment] 2020-05-27 12:54
@evilaliv3 thank you. After browser cache deletion everything worked . About your p.s. I'll talk to our PMO and let you know on slack.
