### ISSUE TITLE
Regression on Tenant Auth Switch introduced in 4.9.1

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#3218] opened 2022-04-19 14:59 UTC
**Describe the bug**
After updating to latest version from 4.7 today I receive an error when accessing configuration of multi tenat sites through the admin site.

**Comment by evilaliv3** [comment] 2022-04-19 17:35
Thank you @elbill , i confirm that this seems to be a regression introduced in 4.9.1.

I'm going to work on a patch and include it in a new release 4.9.3

**Comment by evilaliv3** [comment] 2022-04-21 09:57
Closing as fixed.

**Closed by evilaliv3** 2022-04-21 09:57 UTC
