### ISSUE TITLE
Error trying to update, following the given instructions

### ISSUE THREAD

**Issue by mdio33** [globaleaks/GlobaLeaks#3339] opened 2023-01-31 15:08 UTC
**Describe the bug**
Error trying to update, following the given instructions how to.
https://docs.globaleaks.org/en/main/user/admin/UpgradeGuide.html#upgrade-of-the-distribution-version

**To Reproduce**

apt-get update && apt-get install globaleaks 

**Expected behavior**
Get ubuntu 22.04.1 LTS and Globaleaks 4.10.15  updates

After doing the apt-get update i've got the errors :

W: http://repo.mysql.com/apt/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: http://deb.globaleaks.org/jammy/Release.gpg: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.

If i do the apt-get upgrade, the Globaleaks site stop working.

This a fair recent installation, in a clean ubuntu 22.04.1 install.

**Comment by evilaliv3** [comment] 2023-01-31 15:42
Thank you @mdio33 

The problem is related to a bug in the latest release. we will be fixing this in the next hours with a new release.

I'm closing this ticket as the condition is already tracked by ticket https://github.com/globaleaks/GlobaLeaks/issues/3340

**Closed** 2023-01-31 15:44 UTC

**Comment by evilaliv3** [comment] 2023-02-01 08:17
Fixed with release 4.10.16

**Comment by mdio33** [comment] 2023-02-01 08:39
Thank you very much!
