### ISSUE TITLE
Submit button does not work

### ISSUE THREAD

**Issue by mryber** [globaleaks/GlobaLeaks#2514] opened 2019-02-11 09:46 UTC
**Current behavior**
After upgrading to 3.6.13 and 3.6.14 the submit button does not work.

**Expected behavior**
Expect the site to move on to the reciept page, stating the submission has been sent in.

**Steps to reproduce the problem or feature illustration**
I have tried to downgrade to 3.6.12, where the submit button work fine, then upgrade first to 3.6.13, and the submit button doesn't work, and then again upgrading to 3.6.14 and the submit button still doesn't work.

**What is the motivation or use case for changing the behavior?**
Motivation: hard to get submissions from whistleblowers if they can't submit.

**GlobaLeaks version:**
v3.6.13 + v3.6.14

**Browser:**
Chrome, Firefox and Internet Explorer

**Server Operating System and Version (if applicable):**
Ubuntu LTS 18.04.1

**Client Operating System and Version (if applicable):**
Windows 10 and Linux

**Comment by mryber** [comment] 2019-02-11 12:11
I just did a clean installation of 3.6.14, the submit button still doesn't work, and now, I again see that all text fields are set as mandatory (in the default setup).

Upgrading did not set text fields to mandatory.

**Comment by mryber** [comment] 2019-02-11 12:30
I also tested the clean install, with restoring a backup, the mandatory fields is not an issue on that point, but the submit button still doesn't work.

**Comment by evilaliv3** [comment] 2019-02-11 19:00
Thank you @mryber, i'm now checking about the issue and I will release a 3.6.15 as soon that the issue is identified and fixed.

**Comment by evilaliv3** [comment] 2019-02-11 20:38
@mryber: The issue should be fixed.

Would you please retest if it works for you?

**Comment by evilaliv3** [comment] 2019-02-12 09:19
An other used confirmed the fix. Closing the ticket.

**Closed** 2019-02-12 10:02 UTC
Labels: C: Client, T: Bug

**Comment by mryber** [comment] 2019-02-12 10:54
Sorry, I just got online to check it out, but good to hear that it has been confirmed.

**Comment by mryber** [comment] 2019-02-12 11:49
I can also confirm that both the IP whistelisting and the submit button now works.

**Comment by echo-digitalstudio** [comment] 2021-05-11 15:31
Confirm, missing Recipient 🤦 

Ok for Mention ;) thanks

**Comment by ArturJurewicz** [comment] 2021-12-16 11:27
sorry for refreshing the topic, 
Submit button doesn't work, while putting report (default questionnaires). 
Application installed on Ubuntu 20.04, intall llog looks fine. 
**Globaleaks status:**
" globaleaks.service - LSB: Start the GlobaLeaks server.
     Loaded: loaded (/etc/init.d/globaleaks; generated)
     Active: active (running) since Thu 2021-12-16 12:11:16 CET; 2min 42s ago
       Docs: man:systemd-sysv-generator(8)
    Process: 16792 ExecStart=/etc/init.d/globaleaks start (code=exited, status=0/SUCCESS)
      Tasks: 6 (limit: 9423)
     Memory: 151.5M
     CGroup: /system.slice/globaleaks.service
             └─16854 /usr/bin/python3 /usr/bin/globaleaks --ip=:: --user=globaleaks --working-path=/var/globaleaks/

Dec 16 12:11:14 ubuntu-2004 systemd[1]: Starting LSB: Start the GlobaLeaks server....
Dec 16 12:11:15 ubuntu-2004 globaleaks[16792]:  * Starting GlobaLeaks daemon globaleaks
Dec 16 12:11:15 ubuntu-2004 globaleaks[16792]:  * Enabling Globaleaks Network Sandboxing...
Dec 16 12:11:15 ubuntu-2004 globaleaks[16792]:    ...done.
Dec 16 12:11:15 ubuntu-2004 globaleaks[16792]:  * Starting ...
Dec 16 12:11:16 ubuntu-2004 globaleaks[16792]:    ...done.
Dec 16 12:11:16 ubuntu-2004 systemd[1]: Started LSB: Start the GlobaLeaks server.."_

**Clinet Browser:**
Chrome, Firefox and Tor

**Comment by stajilov** [comment] 2022-09-29 12:16
Ok , in our case
```
GlobaLeaks version: 4.10.10
Database version: 63
```

Probably after an update, some settings got broken and it was necessary to login, edit the context and add the recipients (there were none for some reason).
