### ISSUE TITLE
Could receivers usernames list be replaced by receivers public names list?

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#3163] opened 2022-02-02 16:09 UTC
**Is your feature request related to a problem? Please describe.**
Context flag "Show recipient details on the status page of the report" coud be added by the receiver's public name? Often usernames are not "self-talking" and if It's choosen to see receivers detail, it should be possible to better address the receivers name. 

Furthermore, receiver's login username should not be shown at all also for security reasons (i.e. password recovery attempts, bruteforcing the password, unwanted emails to receivers)

**Describe the solution you'd like**
Just receivers public name should be shown in receivers list, especially if enabled for whistleblowers.

**Comment by evilaliv3** [comment] 2022-02-07 21:06
@larrykind: woululd you please retest this?

I just verified and all seems to be working as designed:
- the username is never shown nor to whistleblowers nor to recipients
- whistleblowers never see the real name of the user but only the public name
- recipients see the real name of the user

I will close this ticket but please feel free to re-open this if you consider a bug exists somewhere or you have any sugestion fo some improvement.

Thank you

**Closed** 2022-02-07 21:22 UTC
Labels: T: Enhancement, C: Client, C: Backend
