### ISSUE TITLE
Cannot paste or import PGP Key in a multi tenant (secondary site) GL instance

### ISSUE THREAD

**Issue by Stephane-FILTRALA** [globaleaks/GlobaLeaks#2395] opened 2018-08-15 10:41 UTC
**Current behavior**
Get an error: "¡Error! Error en la validación de la entrada" when pasting AND importing the GPG key of a receiver in the USER tab..   

**Expected behavior**
Should be able to assign an PGP key to the user.

**Steps to reproduce the problem or feature illustration**
![screenshot 2018-08-15 12 22 46](https://user-images.githubusercontent.com/37292195/44144579-5eaad6d0-a088-11e8-818e-49af7481ada4.jpg)

![screenshot 2018-08-15 12 22 34](https://user-images.githubusercontent.com/37292195/44144587-635fd7fc-a088-11e8-8f02-0f80ad924664.jpg)

**What is the motivation or use case for changing the behavior?**

**GlobaLeaks version:**
v.3.3.0

**Comment by evilaliv3** [comment] 2018-08-15 16:10
thank you @Stephane-FILTRALA for reporting this issue

do you have possibility to access /var/globaleaks/log/globaleaks.log and check if it contains some valuable stacktrace?

will try in the meantime to make a check on a fresh new setup to see if the error exists in latest 3.3.4

**Comment by evilaliv3** [comment] 2018-08-16 09:48
@Stephane-FILTRALA: i just retested locally on a multitenant setup composed by 3 tenants and i managed correctly to load the keys while using py3.

The issue seems not related to multitenancy but to py2; do you confirm your setup is a Xenial setup? (ubuntu 16.04).

On py2 i reproduce an issue on loading the key and the error i get in globaleaks.log is:
```
2018-08-16T11:43:42+0200 [stderr#error] Exception in thread Thread-4:
2018-08-16T11:43:42+0200 [stderr#error] Traceback (most recent call last):
2018-08-16T11:43:42+0200 [stderr#error]   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
2018-08-16T11:43:42+0200 [stderr#error]     self.run()
2018-08-16T11:43:42+0200 [stderr#error]   File "/usr/lib/python2.7/threading.py", line 754, in run
2018-08-16T11:43:42+0200 [stderr#error]     self.__target(*self.__args, **self.__kwargs)
2018-08-16T11:43:42+0200 [stderr#error]   File "/home/user/Development/GlobaLeaks/backend/env2/local/lib/python2.7/site-packages/gnupg.py", line 813, in _read_response
2018-08-16T11:43:42+0200 [stderr#error]     result.handle_status(keyword, value)
2018-08-16T11:43:42+0200 [stderr#error]   File "/home/user/Development/GlobaLeaks/backend/env2/local/lib/python2.7/site-packages/gnupg.py", line 384, in handle_status
2018-08-16T11:43:42+0200 [stderr#error]     raise ValueError("Unknown status message: %r" % key)
```

**Comment by evilaliv3** [comment] 2018-08-16 10:01
I confirm the issue is present on python2 when using gnupg2.

Simpliy adopting gnupg1 makes it work on both python2 and python3

**Comment by evilaliv3** [comment] 2018-08-16 11:18
@Stephane-FILTRALA: we just released version 3.3.5 that should fix your issue.

When you can try to update and please provide us feedback :) thanks!

**Comment by evilaliv3** [comment] 2018-08-16 12:55
@Stephane-FILTRALA: actually with many tests i've not been able to reproduce your failure.

We would require your globaleaks.log file in order to be able to debug this further.

The above error was probably caused by me in an invalid manual setup.

On which version of ubuntu are you experimenting your failure?
Which guide did you followed to perform your setup?

**Comment by evilaliv3** [comment] 2018-11-14 17:29
Closing as outdated.

**Closed by evilaliv3** 2018-11-14 17:29 UTC
Labels: C: Backend, T: Bug
