### ISSUE TITLE
 Problems updating DB to version 4.1.3 from 3.11.54

### ISSUE THREAD

**Issue by matteozoni** [globaleaks/GlobaLeaks#2936] opened 2020-11-27 08:37 UTC
**Current behavior**
After updating to the latest version, the site is no longer accessible

During installation I get

`Ouch! The installation is complete but GlobaLeaks failed to start.`

and in the logs instead I find

```
2020-11-25 13:01:13+0100 [-] twistd 18.9.0 (/usr/bin/python3 3.8.5) starting up.
2020-11-25 13:01:13+0100 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2020-11-25 13:01:16+0100 [-] [E] Found an already initialized database version: 51
2020-11-25 13:01:16+0100 [-] [E] Performing schema migration from version 51 to version 53
2020-11-25 13:01:16+0100 [-] [I] Updating DB from version 51 to version 52
2020-11-25 13:01:16+0100 [-] [I] Migrating table:
2020-11-25 13:01:16+0100 [-] [I]  * Config [#109]
2020-11-25 13:01:16+0100 [-] [I]  * ConfigL10N [#72]
2020-11-25 13:01:16+0100 [-] [I]  * Context [#1]
2020-11-25 13:01:16+0100 [-] [I]  * CustomTexts [#1]
2020-11-25 13:01:16+0100 [-] [I]  * EnabledLanguage [#1]
2020-11-25 13:01:16+0100 [-] [I]  * Field [#99]
2020-11-25 13:01:16+0100 [-] [I]  * FieldAttr [#607]
2020-11-25 13:01:16+0100 [-] [I]  * FieldOption [#54]
2020-11-25 13:01:16+0100 [-] [I]  * File [#2]
2020-11-25 13:01:16+0100 [-] [I]  * Questionnaire [#2]
2020-11-25 13:01:16+0100 [-] [I]  * ReceiverContext [#1]
2020-11-25 13:01:16+0100 [-] [I]  * SubmissionStatus [#3]
2020-11-25 13:01:16+0100 [-] [I]  * Step [#5]
2020-11-25 13:01:16+0100 [-] [I]  * Tenant [#1]
2020-11-25 13:01:16+0100 [-] [I]  * User [#2]
2020-11-25 13:01:16+0100 [-] [E] Failure while executing migration epilogue: 'enable_private_labels'
2020-11-25 13:01:16+0100 [-] [E] Migration failure: 'enable_private_labels'
2020-11-25 13:01:16+0100 [-] [E] Verbose exception traceback:
2020-11-25 13:01:16+0100 [-] [I] Traceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/globaleaks/db/__init__.py", line 88, in update_db\n    migr>
2020-11-25 13:01:16+0100 [-] Server Shut Down.
```

**Expected behavior**

**Steps to reproduce the problem or feature illustration**
Update from 3.11.54 to 4.1.3

**GlobaLeaks version:**
From 3.11.54 to 4.1.3

**Server Operating System and Version (if applicable):**
Ubuntu 20.04.1 LTS

**Comment by evilaliv3** [comment] 2020-11-27 08:46
Thank you for reporting this @matteozoni 


Have you tried to update to 4.1.4? actually i was considering to have fixed this issue already.

When something like this happen you can just revert to the previous version by restoring the previous globaleaks package, because if migration fails the database is kept as it is; so you can just reinstall the previous with apt-get install globaleaks=3.1.58
I'm going to verify this now and keep you posted.

**Comment by matteozoni** [comment] 2020-11-27 08:55
Thanks for the reply, even with version 4.1.4 I have the same problem.


I tried to update to the latest version 3.x but it tells me it doesn't exist

```
root@WB:~# apt-get install globaleaks=3.11.70
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Version '3.11.70' for 'globaleaks' was not found
```

**Comment by evilaliv3** [comment] 2020-11-27 09:29
I'm currently busy but i will be trying to recheck this.

Unfortunately the first release for Ubuntu 20.04 was of the series 4.0

Probably you strarted with an ubuntu bionic and then migrated to focal with ubuntu? in our documentation we actually advise to not do this as it offers less guarantees of reproducibility (eventually in the future evaluate to instantiate a new vps and just do data migration of the direectory /var/globaleaks to preserve a clean environment.

**Comment by matteozoni** [comment] 2020-11-27 10:08
@evilaliv3 
> Probably you strarted with an ubuntu bionic and then migrated to focal with ubuntu? 

Yes, we are in this case

**Comment by evilaliv3** [comment] 2020-11-27 21:57
@matteozoni : Actually i am not able to have the same error on the 4.1.4

Have you retried? Did you solve the issue ?

**Comment by evilaliv3** [comment] 2020-11-28 20:03
@matteozoni : Release 4.1.5 include the fix for this issue. Thank you for reporting this.

**Closed by evilaliv3** 2020-11-28 20:03 UTC
