### ISSUE TITLE
Audit log does not contain the substatuses any more

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#3152] opened 2022-01-17 20:32 UTC
**Describe the bug**
Audit log does not contain the substatus as it used to.
The audit log CSV export does contain the substatus table content, however it is hard to associate with the case substatus as it is not represented as in the case management system (#3028)

As a system may be chosen or rejected based on its auditing capabilities it is very important to contain the substatus, the audit log serial number (#3145) as well as this to be able to be exported in a comprehensive and usable manner in CSV form.

**Comment by evilaliv3** [comment] 2022-01-17 21:44
Thank you @elbill, i will check on this ticket and try to identify the possible regression if any.

**Comment by evilaliv3** [comment] 2022-01-19 18:29
Thank you @elbill, after rechecking on this issue i'm actually not able to reproduce the issue.

The substatus is actually present both on the WEB UI and on the export. In the UI it appear as text while in the export it appear as code.

I'm going to close this issue for now, please feel free to re-open it if you will continue to have this issue.

![Screenshot_2022-01-19 GLOBALEAKS - Audit log](https://user-images.githubusercontent.com/217034/150192022-0d48b73e-51cf-482c-81bb-58e5aaee178e.png)

**Closed** 2022-01-19 18:30 UTC
