### ISSUE TITLE
When connecting to GlobaLeaks with Javascript disabled the error provided is not displayed properly

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1310] opened 2015-06-23 18:15 UTC
When connecting to GlobaLeaks with Javascript disabled the error provided is not displayed properly.

See screenshots below when connecting from Chrome (disabled JS/Cookie) to https://secure.bezkorupce.cz/ .
![screen shot 2015-06-23 at 8 13 29 pm](https://cloud.githubusercontent.com/assets/770363/8313655/78f6c176-19e4-11e5-8ca9-b84cbd53c766.png)

**Comment by evilaliv3** [comment] 2015-06-24 15:11
Aside from showing me the loader (that should be removed) all works great for me on chrome:

**Comment by evilaliv3** [comment] 2015-06-24 15:19
the same on firefox:
![screenshot from 2015-06-24 17 13 42](https://cloud.githubusercontent.com/assets/217034/8333739/9ed086d8-1a94-11e5-99e8-ebe7d0987a86.png)

this make me think that the issue is only with particular plugins like for https://github.com/globaleaks/GlobaLeaks/issues/925. what plugin are you using @fpietrosanti ?

i'm going to fix the presence of the loader and close this ticket.

**Comment by evilaliv3** [comment] 2015-06-24 15:24
ah ok, i got the same issue of you one time fabio, having disabled the cookies after loading globaleaks with javascript enabled and then disabling it. so i think that the issue is not solvable and is part simply of a transient behaviour of the browser.

anyway reloading the page the second time all is ok, so that i do not consider this an issue

**Comment by evilaliv3** [comment] 2015-06-24 15:58
yep i confirm that for me the issue happens only if you have the page open with javascript enabled and i disable jabvascript. on the first update the browser renders it not correctly, but i think the issue lies in the browser and it's not eliminable in the app.

**Closed by evilaliv3** 2015-06-24 15:58 UTC
Labels: A: Oziveni.cz, C: GLClient, Type: bug, U: Whistleblower
