### ISSUE TITLE
Unhandled stack exception on enable_whistleblower_identity sqlalchemy.exc.IntegrityError Wraps a DB-API IntegrityError.

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2339] opened 2018-06-27 18:04 UTC
Platform: xxxxx Leaks TEST
Host: 
Version: 3.1.9

sqlalchemy.exc.IntegrityError Wraps a DB-API IntegrityError.

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python2.7/dist-packages/globaleaks/orm.py", line 110, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/questionnaire.py", line 84, in create_questionnaire
    questionnaire = db_create_questionnaire(session, state, tid, request, language)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/questionnaire.py", line 64, in db_create_questionnaire
    q = models.db_forge_obj(session, models.Questionnaire, questionnaire_dict)

  File "/usr/lib/python2.7/dist-packages/globaleaks/models/__init__.py", line 26, in db_forge_obj
    session.flush()

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2027, in flush
    self._flush(objects)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2145, in _flush
    transaction.rollback(_capture_exception=True)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2109, in _flush
    flush_context.execute()

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 767, in _emit_insert_statements
    execute(statement, multiparams)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)

IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: questionnaire.id [SQL: u'INSERT INTO questionnaire (id, tid, name, enable_whistleblower_identity, editable) VALUES (?, ?, ?, ?, ?)'] [parameters: (u'87e85d2f-cc05-4837-82d3-b69f000aed81', 1, u'Segnalazione', 0, 1)]

**Comment by evilaliv3** [comment] 2018-07-19 18:07
Closing as duplicate of https://github.com/globaleaks/GlobaLeaks/issues/2215

**Closed by evilaliv3** 2018-07-19 18:07 UTC
