### ISSUE TITLE
Failure in migration 50 in relation to recipients that are marked unselectable

### ISSUE THREAD

**Issue by sengelsman** [globaleaks/GlobaLeaks#2661] opened 2019-08-12 14:28 UTC
**Current behavior**
When starting globaleaks version 3.10.4 the service starts successfully however on first access to the portal it doesn't load. Cogwheels remain turning forever and in the logs we see an exception.

2019-08-12 17:17:11+0300 [-] [E] ValueError Inappropriate argument value (of correct type).\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks\n    result = result.throwExceptionIntoGenerator(g)\n\n  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator\n    return g.throw(self.type, self.value, self.tb)\n\n  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/public.py", line 410, in get\n    ret = yield get_public_resources(self.request.tid, self.request.language)\n\n  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext\n    result = inContext.theWork()\n\n  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>\n    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)\n\n  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext\n    return self.currentContext().callWithContext(ctx, func, *args, **kw)\n\n  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext\n    return func(*args,**kw)\n\n  File "/usr/lib/python2.7/dist-packages/globaleaks/orm.py", line 117, in _wrap\n    result = function(session, *args, **kwargs)\n\n  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/public.py", line 394, in get_public_resources\n    'contexts': db_get_public_context_list(session, tid, language),\n\n  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/public.py", line 357, in db_get_public_context_list\n    data = db_prepare_contexts_serialization(session, contexts)\n\n  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/public.py", line 46, in db_prepare_contexts_serialization\n    contexts_ids = [c.id for c in contexts]\n\n  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/loading.py", line 86, in instances\n    util.raise_from_cause(err)\n\n  File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause\n    reraise(type(exception), exception, tb=exc_tb)\n\n  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/loading.py", line 71, in instances\n    rows = [proc(row) for row in fetch]\n\n  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/loading.py", line 428, in _instance\n    loaded_instance, populate_existing, populators)\n\n  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/loading.py", line 486, in _populate_full\n    dict_[key] = getter(row)\n\n  File "/usr/lib/python2.7/dist-packages/sqlalchemy/sql/type_api.py", line 1030, in process\n    return process_value(value, dialect)\n\n  File "/usr/lib/python2.7/dist-packages/globaleaks/models/properties.py", line 28, in process_result_value\n    return json.loads(value)\n\n  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads\n    return _default_decoder.decode(s)\n\n  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n\n  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode\n    raise ValueError("No JSON object could be decoded")\n\nValueError: No JSON object could be decoded\n

**Expected behavior**
Portal loading

**Steps to reproduce the problem or feature illustration**
Upgrade globaleaks to version 3.10.4 and start globaleaks

**What is the motivation or use case for changing the behavior?**
Currently the site is unavailable for reporters and submitters. We have to revert to backup and last known working version.

**GlobaLeaks version:**
3.10.4

**Browser:**
Firefox 68.01

**Server Operating System and Version (if applicable):**

Server Ubuntu 16.04.6

**Client Operating System and Version (if applicable):**
Ubuntu 18.04

============================

**Comment by evilaliv3** [comment] 2019-08-12 15:06
Thank you @sengelsman for reporting this.

I remember that your system was not able to update to the latest version, can you clarify me how you managed to update to the 3.10.4?

To me is clear that the system can be corrupted due to failure or to a skipped update; If you have still an original backup of when the system was fully working we may look at it too understand.

**Comment by evilaliv3** [comment] 2019-08-13 07:15
Good morning @sengelsman,

We analyzed your ticket and identified a possible reason causing the migrations to proceed regardless of an internal failure.

I'm not proceeding releasing an updated package version 3.10.5 and will notify you when done.

As soon that you find it out, would you please retry the update with the original version of the database.
It will probably stop during the migration but at least we should have clear understanding of which is the first migration that is failing and be able to provide a patch.

As your system is still running a version of last November, we should be lucky as this regression causing the migration to not fail was added in April.

**Comment by evilaliv3** [comment] 2019-08-13 07:46
@sengelsman: The package 3.10.5 is now releaed; when you want feel free to test in pre-production.

As soon that you could notify us the errors that you get on the update we could then proceed trying to produce a patch for the failing migration.

Thank you for your collaboration.

**Comment by evilaliv3** [comment] 2019-08-13 16:21
Closing the issue as solved.

While debugging with the help of @sengelsman we identified that the issue was caused by a previous failure that could affect only old platforms.

The patch will be anyhow released in the next release (3.11.6).

**Closed** 2019-08-13 16:22 UTC
Labels: C: Backend, T: Bug, X: PubLeaks
