### ISSUE TITLE
Admin Notification Settings Roles Checkboxes Unchecked Post Upgrade to v5.0.2

### ISSUE THREAD

**Issue by ddimarx** [globaleaks/GlobaLeaks#4172] opened 2024-08-29 10:17 UTC
### What version of GlobaLeaks are you using?

**Environment Details:**

GlobaLeaks Version: v5.0.2
Docker Image: globaleaks/globaleaks:5.0.2
Previous Version: v4.15.8

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What operating system(s) are you seeing the problem on?

Windows, Android, Linux

### Describe the issue

After upgrading GlobaLeaks from Docker v4.15.8 to v5.0.2, I noticed that the checkboxes in the Notifications settings for roles (Admin, Analyst, Custodian, Recipient, etc.) are all unchecked by default.

**Steps to Reproduce:**

1. Upgrade GlobaLeaks using Docker image from https://hub.docker.com/r/globaleaks/globaleaks/tags from globaleaks/globaleaks:v4.15.8 to globaleaks/globaleaks:v5.0.2.
2. Navigate to GlobalLeaks admin > Notifications > Settings .
3. At the bottom of the screen, observe the Notifications Roles section.
4. Check the checkboxes for Admin , Analyst , Custodian , and Recipient .
5. Click the Save button.
6. The page shows the checkboxes "Enabled/checked" as it should.
7. Refresh the web-page or select "Home" and go back to the "Notifications" Settings page.

**Expected Behavior:**
The checkboxes for all selected roles should remain checked after saving the settings.
![image](https://github.com/user-attachments/assets/7f480bb6-3df4-4109-bced-799ab19667cc)

**Actual Behavior:**
All checkboxes become unchecked again after refreshing the page, despite having saved the settings.
![image](https://github.com/user-attachments/assets/ee4bb665-3f6f-4e56-8ac6-506c99bf375d)

**Additional Information:**

I've also tried to test this with a fresh setup of v5.0.1 and v5.0.2 and this issue remains. 
Also, when I used the "Test the configuration" I received the test email even though the checkboxes were unchecked.
It seems that the settings for notification roles are not persisting after an attempted save. This issue might impact the ability to manage notification roles effectively.

**Comment by evilaliv3** [comment] 2024-08-29 12:51
Thank you @ddimarx 

Probably the issue is just visual.

We will proceed rechecking and issuing a fix that will be included in release 5.0.3

**Comment by evilaliv3** [comment] 2024-09-02 18:08
Fixed and fix included in release 5.0.3

**Closed by evilaliv3** 2024-09-02 18:08 UTC
Labels: T: Bug, C: Client, Triage
