### ISSUE TITLE
Error when creating a new admin or recipient on a new site on a multitenant platform.

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#3092] opened 2021-11-09 13:18 UTC
**Describe the bug**
I receive an error when I try to create a new admin or recipient in one new site on a multitenant platform.

**To Reproduce**
I create a new site.
Go to users. Try to create new user (admin or recipient) and receive an error.

**Expected behavior**
Would expect to be straight forward to create a user

**Additional context**
Error message
Host: demo2.sec.fraudline.gr (rpmc7shcsgrlmv5nirlwfkenogqxrx2boa52l25d4xfyrhmh52nl6gqd.onion)
Version: 4.4.5

URL: /admin/users

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

Error Message: Error: [$compile:ctreq] Controller 'flowInit', required by directive 'flowDrop', can't be found!
https://errors.angularjs.org/1.8.2/$compile/ctreq?p0=flowInit&p1=flowDrop

Stacktrace:
[
  {
    "columnNumber": 836,
    "lineNumber": 8,
    "fileName": "https://sec.fraudline.gr/t/17/js/scripts.min.js",
    "source": "    at https://sec.fraudline.gr/t/17/js/scripts.min.js:8:836"
  },
  {
    "columnNumber": 52484,
    "lineNumber": 8,
    "fileName": "https://sec.fraudline.gr/t/17/js/scripts.min.js",
    "functionName": "we",
    "source": "    at we (https://sec.fraudline.gr/t/17/js/scripts.min.js:8:52484)"
  },
  {
    "columnNumber": 52105,
    "lineNumber": 8,
    "fileName": "https://sec.fraudline.gr/t/17/js/scripts.min.js",
    "functionName": "re",
    "source": "    at re (https://sec.fraudline.gr/t/17/js/scripts.min.js:8:52105)"
  },
  {
    "columnNumber": 44918,
    "lineNumber": 8,
    "fileName": "https://sec.fraudline.gr/t/17/js/scripts.min.js",
    "source": "    at https://sec.fraudline.gr/t/17/js/scripts.min.js:8:44918"
  },
  {
    "columnNumber": 52012,
    "lineNumber": 8,
    "fileName": "https://sec.fraudline.gr/t/17/js/scripts.min.js",
    "functionName": "re",
    "source": "    at re (https://sec.fraudline.gr/t/17/js/scripts.min.js:8:52012)"
  },
  {
    "columnNumber": 54451,
    "lineNumber": 8,
    "fileName": "https://sec.fraudline.gr/t/17/js/scripts.min.js",
    "source": "    at https://sec.fraudline.gr/t/17/js/scripts.min.js:8:54451"
  },
  {
    "columnNumber": 95608,
    "lineNumber": 8,
    "fileName": "https://sec.fraudline.gr/t/17/js/scripts.min.js",
    "source": "    at https://sec.fraudline.gr/t/17/js/scripts.min.js:8:95608"
  },
  {
    "columnNumber": 95746,
    "lineNumber": 8,
    "fileName": "https://sec.fraudline.gr/t/17/js/scripts.min.js",
    "source": "    at https://sec.fraudline.gr/t/17/js/scripts.min.js:8:95746"
  },
  {
    "columnNumber": 101109,
    "lineNumber": 8,
    "fileName": "https://sec.fraudline.gr/t/17/js/scripts.min.js",
    "functionName": "d.$digest",
    "source": "    at d.$digest (https://sec.fraudline.gr/t/17/js/scripts.min.js:8:101109)"
  },
  {
    "columnNumber": 103102,
    "lineNumber": 8,
    "fileName": "https://sec.fraudline.gr/t/17/js/scripts.min.js",
    "functionName": "d.$apply",
    "source": "    at d.$apply (https://sec.fraudline.gr/t/17/js/scripts.min.js:8:103102)"
  }
]

**Comment by elbill** [comment] 2021-11-09 13:22
Seems like no users can be created even on existing platforms.

Version: 4.4.5

URL: /admin/users

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

Error Message: Error: [$compile:ctreq] Controller 'flowInit', required by directive 'flowDrop', can't be found!
https://errors.angularjs.org/1.8.2/$compile/ctreq?p0=flowInit&p1=flowDrop

Stacktrace:
[
  {
    "columnNumber": 836,
    "lineNumber": 8,
    "fileName": "https://sec.fraudline.gr/t/16/js/scripts.min.js",
    "source": "    at https://sec.fraudline.gr/t/16/js/scripts.min.js:8:836"
  },
  {
    "columnNumber": 52484,
    "lineNumber": 8,
    "fileName": "https://sec.fraudline.gr/t/16/js/scripts.min.js",
    "functionName": "we",
    "source": "    at we (https://sec.fraudline.gr/t/16/js/scripts.min.js:8:52484)"
  },
  {
    "columnNumber": 52105,
    "lineNumber": 8,
    "fileName": "https://sec.fraudline.gr/t/16/js/scripts.min.js",
    "functionName": "re",
    "source": "    at re (https://sec.fraudline.gr/t/16/js/scripts.min.js:8:52105)"
  },
  {
    "columnNumber": 44918,
    "lineNumber": 8,
    "fileName": "https://sec.fraudline.gr/t/16/js/scripts.min.js",
    "source": "    at https://sec.fraudline.gr/t/16/js/scripts.min.js:8:44918"
  },
  {
    "columnNumber": 52012,
    "lineNumber": 8,
    "fileName": "https://sec.fraudline.gr/t/16/js/scripts.min.js",
    "functionName": "re",
    "source": "    at re (https://sec.fraudline.gr/t/16/js/scripts.min.js:8:52012)"
  },
  {
    "columnNumber": 54451,
    "lineNumber": 8,
    "fileName": "https://sec.fraudline.gr/t/16/js/scripts.min.js",
    "source": "    at https://sec.fraudline.gr/t/16/js/scripts.min.js:8:54451"
  },
  {
    "columnNumber": 95608,
    "lineNumber": 8,
    "fileName": "https://sec.fraudline.gr/t/16/js/scripts.min.js",
    "source": "    at https://sec.fraudline.gr/t/16/js/scripts.min.js:8:95608"
  },
  {
    "columnNumber": 95746,
    "lineNumber": 8,
    "fileName": "https://sec.fraudline.gr/t/16/js/scripts.min.js",
    "source": "    at https://sec.fraudline.gr/t/16/js/scripts.min.js:8:95746"
  },
  {
    "columnNumber": 101109,
    "lineNumber": 8,
    "fileName": "https://sec.fraudline.gr/t/16/js/scripts.min.js",
    "functionName": "d.$digest",
    "source": "    at d.$digest (https://sec.fraudline.gr/t/16/js/scripts.min.js:8:101109)"
  },
  {
    "columnNumber": 103102,
    "lineNumber": 8,
    "fileName": "https://sec.fraudline.gr/t/16/js/scripts.min.js",
    "functionName": "d.$apply",
    "source": "    at d.$apply (https://sec.fraudline.gr/t/16/js/scripts.min.js:8:103102)"
  }
]

**Comment by evilaliv3** [comment] 2021-11-09 13:38
Hello @elbill actually the issue that you are reporting seems not related to the execptions that you are reporting (that are related to an other bug).

Do you have any exception in /var/log/globaleaks.log ?

**Comment by elbill** [comment] 2021-11-09 13:45
I will send it a bit later. I'm running a training in a few mins.

**Comment by elbill** [comment] 2021-11-09 18:39
@evilaliv3 I get the following error from /var/globaleaks/log/globaleaks.log

2021-11-09 18:21:32+0000 [-] [E] Unhandled exception raised:
2021-11-09 18:21:32+0000 [-] [E] nacl.exceptions.CryptoError \n    Base exceptio
n for all nacl related errors\n    \n\nTraceback (most recent call last):\n\n  F
ile "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1384, in _i
nlineCallbacks\n    result = result.throwExceptionIntoGenerator(g)\n\n  File "/u
sr/lib/python3/dist-packages/twisted/python/failure.py", line 408, in throwExcep
tionIntoGenerator\n    return g.throw(self.type, self.value, self.tb)\n\n  File
"/usr/lib/python3/dist-packages/globaleaks/handlers/admin/user.py", line 164, in
 post\n    yield generate_password_reset_token(self.request.tid, self.session, u
ser['id'])\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.p
y", line 250, in inContext\n    result = inContext.theWork()\n\n  File "/usr/lib
/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>\n
 inContext.theWork = lambda: context.call(ctx, func, *args, **kw)\n\n  File "/us
 nlineCallbacks\n    result = result.throwExceptionIntoGenerator(g)\n\n  File "/u
sr/lib/python3/dist-packages/twisted/python/failure.py", line 408, in throwExcep
tionIntoGenerator\n    return g.throw(self.type, self.value, self.tb)\n\n  File
"/usr/lib/python3/dist-packages/globaleaks/handlers/admin/user.py", line 164, in
 post\n    yield generate_password_reset_token(self.request.tid, self.session, u
ser['id'])\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.p
y", line 250, in inContext\n    result = inContext.theWork()\n\n  File "/usr/lib
/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>\n
 inContext.theWork = lambda: context.call(ctx, func, *args, **kw)\n\n  File "/us
r/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithCon
text\n    return self.currentContext().callWithContext(ctx, func, *args, **kw)\n
\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in
 callWithContext\n    return func(*args,**kw)\n\n  File "/usr/lib/python3/dist-p
ackages/globaleaks/orm.py", line 152, in _wrap\n    result = function(session, *
args, **kwargs)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/ad
min/operation.py", line 141, in generate_password_reset_token\n    set_tmp_key(u
ser_session, user)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers
/admin/operation.py", line 123, in set_tmp_key\n    user_cc = GCE.asymmetric_dec
rypt(crypto_escrow_prv_key, Base64Encoder.decode(user.crypto_escrow_bkp1_key))\n
text\n    return self.currentContext().callWithContext(ctx, func, *args, **kw)\n
\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in
 callWithContext\n    return func(*args,**kw)\n\n  File "/usr/lib/python3/dist-p
ackages/globaleaks/orm.py", line 152, in _wrap\n    result = function(session, *
args, **kwargs)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/ad
min/operation.py", line 141, in generate_password_reset_token\n    set_tmp_key(u
ser_session, user)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers
/admin/operation.py", line 123, in set_tmp_key\n    user_cc = GCE.asymmetric_dec
rypt(crypto_escrow_prv_key, Base64Encoder.decode(user.crypto_escrow_bkp1_key))\n
\n  File "/usr/lib/python3/dist-packages/globaleaks/utils/crypto.py", line 321,
in asymmetric_decrypt\n    return SealedBox(prv_key).decrypt(data)\n\n  File "/u
sr/lib/python3/dist-packages/nacl/public.py", line 361, in decrypt\n    self._pr
ivate_key,\n\n  File "/usr/lib/python3/dist-packages/nacl/bindings/crypto_box.py
", line 311, in crypto_box_seal_open\n    raising=exc.CryptoError)\n\n  File "/u
sr/lib/python3/dist-packages/nacl/exceptions.py", line 68, in ensure\n    raise
raising(*args)\n\nnacl.exceptions.CryptoError: An error occurred trying to decry
pt the message\n
2021-11-09 18:21:36+0000 [-] Starting factory <twisted.mail.smtp.ESMTPSenderFact
ory object at 0x7fe8ba0fe2e8>
2021-11-09 18:21:36+0000 [-] Stopping factory <twisted.mail.smtp.ESMTPSenderFact
ory object at 0x7fe8ba0fe2e8>
2021-11-09 18:21:37+0000 [-] Starting factory <twisted.mail.smtp.ESMTPSenderFact
ory object at 0x7fe8bba7e4a8>
2021-11-09 18:21:38+0000 [-] Stopping factory <twisted.mail.smtp.ESMTPSenderFact
ory object at 0x7fe8bba7e4a8>
2021-11-09 18:21:39+0000 [-] Starting factory <twisted.mail.smtp.ESMTPSenderFact
ory object at 0x7fe8bb95ba90>
2021-11-09 18:21:39+0000 [-] Stopping factory <twisted.mail.smtp.ESMTPSenderFact
ory object at 0x7fe8bb95ba90>

**Comment by elbill** [comment] 2021-11-09 19:02
and by email:

Version: 4.4.5

nacl.exceptions.CryptoError
    Base exception for all nacl related errors


Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)

  File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/user.py", line 164, in post
    yield generate_password_reset_token(self.request.tid, self.session, user['id'])

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 152, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/operation.py", line 141, in generate_password_reset_token
    set_tmp_key(user_session, user)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/operation.py", line 123, in set_tmp_key
    user_cc = GCE.asymmetric_decrypt(crypto_escrow_prv_key, Base64Encoder.decode(user.crypto_escrow_bkp1_key))

  File "/usr/lib/python3/dist-packages/globaleaks/utils/crypto.py", line 321, in asymmetric_decrypt
    return SealedBox(prv_key).decrypt(data)

  File "/usr/lib/python3/dist-packages/nacl/public.py", line 361, in decrypt
    self._private_key,

  File "/usr/lib/python3/dist-packages/nacl/bindings/crypto_box.py", line 311, in crypto_box_seal_open
    raising=exc.CryptoError)

  File "/usr/lib/python3/dist-packages/nacl/exceptions.py", line 68, in ensure
    raise raising(*args)

nacl.exceptions.CryptoError: An error occurred trying to decrypt the message

**Comment by evilaliv3** [comment] 2021-11-09 19:03
Thank you @elbill, I think i've identified the issue.

Is it possible that you have recently enable the feature "Enable administrator to change users passwords" on one of the secondary tenants? I've just discovered a bug that when a user enable this feature on the secondary tenant by using an administrator of the root tenant the key escrow of that user is wrongly overwriting making loosing the original escrow key.

The issue cold be easily solved in one of the two following ways:
- if you have an other administrator on the root tenant enabled to change users passwords, you could ask that user to revoke your permission to change users passwords and grant it again to you.
- if you have still a backup of your setup, with the sqlitebrowser app you could open your database, locate your user and restore the value of the attribute ```crypto_escrow_prv_key``` that you read in the backup.

I'm going to issue an immediate release 4.5.0 that will fix the original bug.

@larrykind @maxmois @schris-dk: Please read this comment carefully and consider to verify if your administrators of the root tenant can correclty change users password of the secondary tenant. If not please follow one of the above instructions.

**Comment by elbill** [comment] 2021-11-09 21:43
I updated to V4.5.0
Without taking any other action it seems to be working.
However one other issue has appeared. When creating a new site, one can not configure the new site or existing sites through the root tenant. When you press configure you end up with a still admin log in screen.

**Comment by evilaliv3** [comment] 2021-11-09 22:39
Thank you for detecting this, its actually unrelated but i will take care of checking it.

**Comment by evilaliv3** [comment] 2021-11-09 22:52
@elbill: i guess that in relation to this ticket, you didn't still had the chance to test it.

If i understand correctly your last message, you didn't had the chance to log in with the root administrator on the secondary tenant but i think you accessed with an admin user of the secondary tenant for which the escrow mechanism is correcly working.
This issue is related to a failure on the root tenant admin.

**Comment by evilaliv3** [comment] 2021-11-09 23:45
@elbill: If you want want to retry now with 4.5.1 you should be able to login on secondary tenants from the root tenant and proceed with the retesting of the password change issue originally reported on this ticket.

**Comment by elbill** [comment] 2021-11-10 07:08
I can log in now from root tenant but I believe the initial issue has come back.

**Comment by elbill** [comment] 2021-11-10 07:10
nacl.exceptions.CryptoError
    Base exception for all nacl related errors


Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)

  File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/user.py", line 164, in post
    yield generate_password_reset_token(self.request.tid, self.session, user['id'])

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 149, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/operation.py", line 142, in generate_password_reset_token
    set_tmp_key(user_session, user)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/operation.py", line 124, in set_tmp_key
    user_cc = GCE.asymmetric_decrypt(crypto_escrow_prv_key, Base64Encoder.decode(user.crypto_escrow_bkp1_key))

  File "/usr/lib/python3/dist-packages/globaleaks/utils/crypto.py", line 313, in asymmetric_decrypt
    return SealedBox(prv_key).decrypt(data)

  File "/usr/lib/python3/dist-packages/nacl/public.py", line 361, in decrypt
    self._private_key,

  File "/usr/lib/python3/dist-packages/nacl/bindings/crypto_box.py", line 311, in crypto_box_seal_open
    raising=exc.CryptoError)

  File "/usr/lib/python3/dist-packages/nacl/exceptions.py", line 68, in ensure
    raise raising(*args)

nacl.exceptions.CryptoError: An error occurred trying to decrypt the message

**Comment by elbill** [comment] 2021-11-10 07:11
Version: 4.5.1

sqlalchemy.exc.IntegrityError Wraps a DB-API IntegrityError.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)

sqlite3.IntegrityError: UNIQUE constraint failed: user.tid, user.username


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)

  File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/user.py", line 161, in post
    user = yield create_user(self.request.tid, request, self.request.language)

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 149, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/user.py", line 70, in create_user
    return user_serialize_user(session, db_create_user(session, tid, request, language), language)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/user.py", line 54, in db_create_user
    session.flush()

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2171, in flush
    self._flush(objects)

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2291, in _flush
    transaction.rollback(_capture_exception=True)

  File "/usr/lib/python3/dist-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)

  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2255, in _flush
    flush_context.execute()

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 835, in _emit_insert_statements
    execute(statement, params)

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)

  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info

  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)

  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)

sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.tid, user.username [SQL: 'INSERT INTO user (id, tid, creation_date, username, salt, hash_alg, password, name, description, public_name, role, state, last_login, mail_address, language, password_change_needed, password_change_date, crypto_prv_key, crypto_pub_key, crypto_rec_key, crypto_bkp_key, crypto_escrow_prv_key, crypto_escrow_bkp1_key, crypto_escrow_bkp2_key, change_email_address, change_email_token, change_email_date, reset_password_token, reset_password_date, notification, forcefully_selected, can_delete_submission, can_postpone_expiration, can_grant_access_to_reports, can_edit_general_settings, readonly, two_factor_secret, reminder_date, pgp_key_fingerprint, pgp_key_public, pgp_key_expiration, clicked_recovery_key) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('169c92c3-5edf-4a85-a766-5906faea488f', 13, '2021-11-10 07:06:56.985979', 'test2', 'HzHnMV8JsQqaC3DN/v/QnA==', 'ARGON2', '+4Si02zoOSrq1lXsxHHZfovpbYncr98lZrw42tLW6TU=', 'Vassilis Stamatopoulos', '{"el": ""}', 'Vassilis Stamatopoulos', 1, 1, '1970-01-01 00:00:00.000000', 'vstamatopoulos@gmail.com', 'el', 1, '2021-11-10 07:06:55.975049', '3pgJnE4zjBmQBXojfnZ2vTbqvNgwVy86awzjnCmltJXEJKwofgXMfU5UjjTo5+lOQC0kE/yacRYbwE2m1L3222z9g71gpLZNABqqMbwLpXOvWzBA', 'sAJWiTF2UGrcCZ7Kp6kG2xQydY9PdtdxNjrFG/tBmkk=', 'cTTaZI6rzxesAnZI5WqqoFZ6iezLQ9buWG3mYlnlC0jL9wx/KgKeQHPMXA7o79Pb9ZI/zwPwlyCdu9BPDL4j7mVXunCVzuy1O3SJ67v4RwA=', 'CVgl1KF/uubZKRn9V8Y8qfRYGmv8CkYV40MLKgs0j+Lbuu/XKQcABn1ESiczBJCqzPHWQDQUZ4NXYi7jKKuzrLrEGe824O8i5C50vWl1ZvJ+HG/1', '', 'ulksYPuH8fx81yc7wa+9uurUHsPqHcYw6K7c0LKNlRXipwxPldF+WU1sKPGieZgtodx3ArJJsU0a3O0+tDeviUc6acRNmnQXrSJ3vyrrHAq47cAkeITB2hV8ZSQ=', 'ECGwkB9fgfOlFz1UGyrX5pBCMomB2EN+o0NAQwXZgDY42Va6v2ej4rKrH1W5rLbyeGRUw8Zmje+Y7zyvJgfBTLZ/FYzPEmWS4C/ZaLUSKdssNm+oC/825f05CN0=', '', None, '1970-01-01 00:00:00.000000', None, datetime.datetime(1970, 1, 1, 0, 0), 1, 0, 0, 0, 0, 0, 0, '', '1970-01-01 00:00:00.000000', '', '', '1970-01-01 00:00:00.000000', 0)]

**Comment by evilaliv3** [comment] 2021-11-10 08:33
@elbill: the original issue could not be solved automatically unfortunately but could be only solved manually with one of the procedures described in the comment https://github.com/globaleaks/GlobaLeaks/issues/3092#issuecomment-964446852

**Comment by elbill** [comment] 2021-11-10 10:33
Following the manual procedure the issue seems to be resolved. Thanks @evilaliv3

**Comment by evilaliv3** [comment] 2021-11-10 10:36
Thank you @elbill.

which of the manual two procedures have you followed?

**Comment by elbill** [comment] 2021-11-10 18:01
The one that disabled and enabled the key escrow mechanism on all the
tenants.

**Comment by evilaliv3** [comment] 2021-11-10 21:06
I see. In the case this was a production system ask your users to log in one time this way their keys will be protected by your escrow keys and you will be able to support them in the case in the future they lose their personal passwords.

**Comment by elbill** [comment] 2021-11-11 16:42
The system asks users to change password.
Are keys protected by changing the password or do they also need to log in?
The risk is that a user change the password and then forget to save it.

**Comment by evilaliv3** [comment] 2021-11-11 18:20
Actually you cannot change the password of the users till their new login but on their new login and change of the password you will immediately protected.

So its not a problem if they will change the password and will forget the new one.

The problem is only now if they forget their own current password. In this case if they don't have their own account recovery key the account will be unrecoverable.

So my advise is to get in touch with the users that have received submissions and support them to make a login.

**Comment by evilaliv3** [comment] 2023-02-02 15:48
Closed as resolved long time ago.

**Closed by evilaliv3** 2023-02-02 15:48 UTC
