### ISSUE TITLE
Failed upgrade 4.2.2 to 4.2.12 and error to request ssl or upload custom ssl

### ISSUE THREAD

**Issue by fwppe** [globaleaks/GlobaLeaks#3030] opened 2021-07-22 12:29 UTC
Ubuntu 20.04.2 LTS (GNU/Linux 5.8.0-63-generic x86_64)
Versione del software: 4.2.2
apt-get update ok
apt-get upgrade ok

**# ./install-globaleaks.sh**
_Running the GlobaLeaks installation…
In case of failure please report encountered issues to the ticketing system at: Issues · globaleaks/GlobaLeaks · GitHub 1

Detected OS: Ubuntu - focal
WARNING: GlobaLeaks is actively developed and tested specifically for Debian 10 (Buster)
WARNING: The software lifecycle of the platform includes full support for all Debian and Ubuntu LTS versions starting from Debian 10 and Ubuntu 20.04
Do you wish to continue anyway? [y|n]?
Please answer y/n.
Do you wish to continue anyway? [y|n]?y
Running: “/etc/init.d/globaleaks stop”… SUCCESS
Running: “apt-get -y update”… SUCCESS
Lettura elenco dei pacchetti… Fatto
Generazione albero delle dipendenze
Lettura informazioni sullo stato… Fatto
tzdata è già alla versione più recente (2021a-0ubuntu0.20.04).
Il seguente pacchetto è stato installato automaticamente e non è più richiesto:

libfprint-2-tod1*
Usare “apt autoremove” per rimuoverlo.
0 aggiornati, 0 installati, 0 da rimuovere e 9 non aggiornati.
Current default time zone: ‘Europe/Rome’
Local time is now: Thu Jul 22 08:37:43 CEST 2021.
Universal Time is now: Thu Jul 22 06:37:43 UTC 2021.

Running: “apt-get -y install curl gnupg net-tools software-properties-common”… SUCCESS
Running: “is_tcp_sock_free_check 0.0.0.0:80”… SUCCESS
Running: “is_tcp_sock_free_check 0.0.0.0:443”… SUCCESS
Running: “is_tcp_sock_free_check 127.0.0.1:8082”… SUCCESS
Running: “is_tcp_sock_free_check 127.0.0.1:8083”… SUCCESS

required TCP sockets open*
Adding GlobaLeaks PGP key to trusted APT keys
% Total % Received % Xferd Average Speed Time Time Time Current*
                            Dload  Upload   Total   Spent    Left  Speed*
100 5519 100 5519 0 0 43801 0 --:–:-- --:–:-- --:–:-- 43801
OK
Updating GlobaLeaks apt source.list in /etc/apt/sources.list.d/globaleaks.list …
Running: “apt-get update -y”… SUCCESS
Running: “apt-get install globaleaks -y”… SUCCESS
Ouch! The installation is complete but GlobaLeaks failed to start._

**this is the log:**

_2021-07-22 08:27:18+0200 [-] [E] [1] Initialization of onion-service dqwiohh3tn7loityucewsdsgsyj63a3hbcg523mwy2fjxwh3wtwyheyd.onion completed.
2021-07-22 08:28:02+0200 [-] Stopping factory <Site object at 0x7f01461a90a0>
2021-07-22 08:28:02+0200 [-] [E] Exception while running OnionService
2021-07-22 08:28:02+0200 [-] Traceback (most recent call last):
2021-07-22 08:28:02+0200 [-] File “/usr/lib/python3/dist-packages/globaleaks/services/service.py”, line 25, in run
2021-07-22 08:28:02+0200 [-] yield self.operation()
2021-07-22 08:28:02+0200 [-] twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2021-07-22 08:28:02+0200 [-] [E] Unhandled exception raised:
2021-07-22 08:28:02+0200 [-] [E] twisted.internet.error.ConnectionLost Connection to the other side was lost in a non-clean fashion\n\nTraceback (most recent call last):\n\n File “/usr/lib/python3/dist-packages/globaleaks/services/service.py”, line 25, in run\n yield self.operation()\n\ntwisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.\n
2021-07-22 08:28:02+0200 [-] Server Shut Down_.

**it manually restarts but the software version is always the same**
service globaleaks start

_2021-07-22 08:28:38+0200 [-] twistd 18.9.0 (/usr/bin/python3 3.8.10) starting up.
2021-07-22 08:28:38+0200 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2021-07-22 08:28:39+0200 [-] [E] Found an already initialized database version: 54
2021-07-22 08:28:40+0200 [-] Starting factory <Site object at 0x7ff66319da90>
2021-07-22 08:28:40+0200 [-] GlobaLeaks is now running and accessible at the following urls:
2021-07-22 08:28:40+0200 [-] - [HTTP] → http://segnalazioni.xxxxxxxxxxxx.it
2021-07-22 08:28:40+0200 [-] - [Tor]: → http://dqwiohh3tn7loityucewsdsgsyj63a3hbcg523mwy2fjxwh3wtwyheyd.onion
2021-07-22 08:28:40+0200 [-] [E] Successfully connected to Tor control port
2021-07-22 08:28:43+0200 [-] [E] [1] Initialization of onion-service dqwiohh3tn7loityucewsdsgsyj63a3hbcg523mwy2fjxwh3wtwyheyd.onion completed_.

**or tried to activate https from the gui but it returns this error in the logs:**

_*OpenSSL.crypto.Error \n An error occurred in an OpenSSL.crypto API.\n \n\nTraceback (most recent call last):\n\n File “/usr/lib/python3/dist-packages/twisted/python/threadpool.py”, line 250, in inContext\n result = inContext.theWork()\n\n File “/usr/lib/python3/dist-packages/twisted/python/threadpool.py”, line 266, in \n inContext.theWork = lambda: context.call(ctx, func, *args, **kw)\n\n File “/usr/lib/python3/dist-packages/twisted/python/context.py”, line 122, in callWithContext\n return self.currentContext().callWithContext(ctx, func, *args, **kw)\n\n File “/usr/lib/python3/dist-packages/twisted/python/context.py”, line 85, in callWithContext\n return func(*args,**kw)\n\n File “/usr/lib/python3/dist-packages/globaleaks/orm.py”, line 140, in _wrap\n result = function(session, *args, *kwargs)\n\n File “/usr/lib/python3/dist-packages/globaleaks/handlers/admin/https.py”, line 322, in serialize_https_config_summary\n file_summaries[key] = file_res_cls.db_serialize(session, tid)\n\n File “/usr/lib/python3/dist-packages/globaleaks/handlers/admin/https.py”, line 238, in db_serialize\n x509 = crypto.load_certificate(crypto.FILETYPE_PEM, c)\n\n File “/usr/lib/python3/dist-packages/OpenSSL/crypto.py”, line 1837, in load_certificate\n _raise_current_error()\n\n File “/usr/lib/python3/dist-packages/OpenSSL/_util.py”, line 54, in exception_from_error_queue\n raise exception_type(errors)\n\nOpenSSL.crypto.Error: [(‘PEM routines’, ‘get_header_and_data’, ‘bad end line’)]\n_

plase help me for upgrade error e ssl request

thanks

**Comment by evilaliv3** [comment] 2021-07-22 12:36
Thank you for reporting this @fwppe 

Actually this issue is already discussed and addressed in the ticket https://github.com/globaleaks/GlobaLeaks/issues/2985

Follow the ticket and you shall be able to fix.

**Comment by evilaliv3** [comment] 2021-07-22 12:40
Thank you for reporting this @fwppe.

I will retest a clean install of GlobaLeaks to try to understand if this bug could be scattered by some up to date package in ubungu.

**Comment by evilaliv3** [comment] 2021-07-22 13:30
@fwppe: would you please retry now with ```apt-get update && apt-get install globaleaks``` and tell me if something changed?

**Comment by fwppe** [comment] 2021-07-22 14:12
> @fwppe: would you please retry now with `apt-get update && apt-get install globaleaks` and tell me if something changed?

_Fantastic, this is the log the upgrade ok_:

_2021-07-22 15:56:50+0200 [-] Stopping factory <Site object at 0x7fb98a4220a0>
2021-07-22 15:56:50+0200 [-] [E] Exception while running OnionService
2021-07-22 15:56:50+0200 [-] Traceback (most recent call last):
2021-07-22 15:56:50+0200 [-]   File "/usr/lib/python3/dist-packages/globaleaks/services/service.py", line 25, in run
2021-07-22 15:56:50+0200 [-]     yield self.operation()
2021-07-22 15:56:50+0200 [-] twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2021-07-22 15:56:50+0200 [-] [E] Unhandled exception raised:
2021-07-22 15:56:50+0200 [-] [E] twisted.internet.error.ConnectionLost Connection to the other side was lost in a non-clean fashion\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/globaleaks/services/service.py", line 25, in run\n    yield self.operation()\n\ntwisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.\n
2021-07-22 15:56:50+0200 [-] Server Shut Down.
2021-07-22 15:57:00+0200 [-] twistd 18.9.0 (/usr/bin/python3 3.8.10) starting up.
2021-07-22 15:57:00+0200 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2021-07-22 15:57:02+0200 [-] [E] Found an already initialized database version: 54
2021-07-22 15:57:02+0200 [-] Starting factory <Site object at 0x7f8de7fada00>
2021-07-22 15:57:02+0200 [-] GlobaLeaks is now running and accessible at the following urls:
2021-07-22 15:57:02+0200 [-] - [HTTP]   --> http://segnalazioni.xxxxxxxxxx.it
2021-07-22 15:57:02+0200 [-] - [Tor]:   --> http://dqwiohh3tn7loityucewsdsgsyj63a3hbcg523mwy2fjxwh3wtwyheyd.onion
2021-07-22 15:57:03+0200 [-] [E] Successfully connected to Tor control port
2021-07-22 15:57:05+0200 [-] [E] [1] Initialization of onion-service dqwiohh3tn7loityucewsdsgsyj63a3hbcg523mwy2fjxwh3wtwyheyd.onion completed._

**it is ok, but stop the service and see this error.**

_2021-07-22 16:11:05+0200 [-] [E] Exception while running OnionService
2021-07-22 16:11:05+0200 [-] Traceback (most recent call last):
2021-07-22 16:11:05+0200 [-]   File "/usr/lib/python3/dist-packages/globaleaks/services/service.py", line 25, in run
2021-07-22 16:11:05+0200 [-]     yield self.operation()
2021-07-22 16:11:05+0200 [-] twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2021-07-22 16:11:05+0200 [-] [E] Unhandled exception raised:
2021-07-22 16:11:05+0200 [-] [E] twisted.internet.error.ConnectionLost Connection to the other side was lost in a non-clean fashion\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/globaleaks/services/service.py", line 25, in run\n    yield self.operation()\n\ntwisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.\n
2021-07-22 16:11:05+0200 [-] Stopping factory <Site object at 0x7fe92147d310>
2021-07-22 16:11:05+0200 [-] Server Shut Down._


thanks

**Comment by evilaliv3** [comment] 2021-07-22 14:44
Thank you.

Do you confirm that the issue is solved and could be closed?

**Comment by fwppe** [comment] 2021-07-22 18:26
> Thank you.
> 
> Do you confirm that the issue is solved and could be closed?

yes, the problem is solved, but why when I stop the service goes in error?

# /etc/init.d/globaleaks stop
_2021-07-22 20:24:54+0200 [-] [E] Exception while running OnionService
2021-07-22 20:24:54+0200 [-] Traceback (most recent call last):
2021-07-22 20:24:54+0200 [-]   File "/usr/lib/python3/dist-packages/globaleaks/services/service.py", line 25, in run
2021-07-22 20:24:54+0200 [-]     yield self.operation()
2021-07-22 20:24:54+0200 [-] twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2021-07-22 20:24:54+0200 [-] [E] Unhandled exception raised:
2021-07-22 20:24:54+0200 [-] [E] twisted.internet.error.ConnectionLost Connection to the other side was lost in a non-clean fashion\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/globaleaks/services/service.py", line 25, in run\n    yield self.operation()\n\ntwisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.\n
2021-07-22 20:24:54+0200 [-] Stopping factory <Site object at 0x7fa25d0792e0>
2021-07-22 20:24:54+0200 [-] Server Shut Down._


thanks

**Comment by evilaliv3** [comment] 2021-07-23 10:39
Thank you for confirming. You can actually ignore this error on the teardown that is not causing any issue and will be managed by us in next updates.

**Closed by evilaliv3** 2021-07-23 10:39 UTC
