### ISSUE TITLE
Can't update selection box orientation. 

### ISSUE THREAD

**Issue by filternetz** [globaleaks/GlobaLeaks#1498] opened 2015-11-24 14:39 UTC
When attempting to change the orientation from horizontal to vertical we get "failed".

2015-11-24 15:30:47+0100 [GLHTTPConnection,49,127.0.0.1] &quot;[!] Unable to update field: &#39;type&#39;&quot;
2015-11-24 15:30:47+0100 [-] [ ] 406 PUT &#47;admin&#47;fields&#47;151132bd-8109-4d0a-9811-5c3264f0409a (127.0.0.1): GLException
2015-11-24 15:30:47+0100 [-] Uncaught exception in write_error: KeyError(&#39;type&#39;,) is not JSON serializable
2015-11-24 15:30:47+0100 [-] [http] 406 PUT &#47;admin&#47;fields&#47;151132bd-8109-4d0a-9811-5c3264f0409a (127.0.0.1) 91.98ms

http://imgur.com/RZcovEw <-- image

**Comment by vodkina** [comment] 2015-11-27 13:12
May the problem is: https://github.com/globaleaks/GlobaLeaks/blob/master/client/app/views/admin/fields.html#L193?

**Comment by evilaliv3** [comment] 2015-11-27 14:26
thanks @vodkina 

the issue is not related to the usage of the variable but to the definition of it and probably is lying inside the db migration script that was not migrating things correctly but i've still to investigate it.

**Comment by evilaliv3** [comment] 2015-12-22 00:23
not reproducible; should be probably fixed by latest development.

**Closed by evilaliv3** 2015-12-22 00:23 UTC

**Comment by marceloomens** [comment] 2015-12-22 11:16
We've again run into this problem in the Netherlands, so I guess it's now safe to say that it's not due to an upgrade-related issue. 

As before this will probably work:

    TRUNCATE TABLE eventlogs

but that's not exactly a long-term solution. Apparently every so often a notification is generated that blocks the mailqueue, for whatever reason, leading to no notifications being delivered by the node at all. I find it hard to believe that we're the only ones with this problem.

**Comment by marceloomens** [comment] 2015-12-22 11:43
We've again run into this problem in the Netherlands, so I guess it's now safe to say that it's not due to an upgrade-related issue. 

As before this will probably work:

    TRUNCATE TABLE eventlogs

but that's not exactly a long-term solution. Apparently every so often a notification is generated that blocks the mailqueue, for whatever reason, leading to no notifications being delivered by the node at all. I find it hard to believe that we're the only ones with this problem.
