### ISSUE TITLE
GlobaLeaks should gracefully handle ACME server failures when no JSON response occurs

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2317] opened 2018-06-13 11:20 UTC
Platform:  
Host:  
Version: 3.1.8

ValueError Inappropriate argument value (of correct type).

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/base.py", line 53, in run
    yield self.operation()

  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)

  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/certificate_check.py", line 75, in operation
    yield self.check_tenants_for_cert_expiration()

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python2.7/dist-packages/globaleaks/orm.py", line 108, in _wrap
    result = function(self.instance, session, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/certificate_check.py", line 43, in check_tenants_for_cert_expiration
    self.cert_expiration_checks(session, tenant[0])

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/certificate_check.py", line 57, in cert_expiration_checks
    db_acme_cert_issuance(session, tid)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/https.py", line 518, in db_acme_cert_issuance
    Settings.acme_directory_url)

  File "/usr/lib/python2.7/dist-packages/globaleaks/utils/letsencrypt.py", line 50, in run_acme_reg_to_finish
    terms_of_service_agreed=True

  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 584, in new_account
    regr = self._regr_from_response(response)

  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 68, in _regr_from_response
    body=messages.Registration.from_json(response.json()),

  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)

  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)

  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")

ValueError: No JSON object could be decoded

**Comment by NCommander** [comment] 2018-06-14 07:16
Reviewed this bug, and checked through the exception logs. This isn't a GL bug per say; what's happening is that we're reaching out to the Let's Encrypt ACME endpoint and for whatever reason, we're not getting a valid response back (or the connection lagged out). This can be caused by LE's issuance server flaking out for a moment, momentarily connection issues, or an internal firewall between the GL instance and LE.

While we can't correct network problems, we should probably handle this more gracefully as well as attempt to retry a few times in case of intermediate network issues.

**Comment by NCommander** [comment] 2018-06-28 16:10
Fix for this got merged.

**Closed by NCommander** 2018-06-28 16:10 UTC
Labels: C: Backend, T: Bug
