### ISSUE TITLE
When a "Multiple Entries" field is added from a field database, the "description" of the Add button is not editable

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1455] opened 2015-10-23 09:00 UTC
When a "Multiple Entries" field is added from a field database, the "description" of the Add button is not editable

**Comment by NSkelsey** [comment] 2015-11-05 21:07
I have looked at this issue and I cannot determine where this issue shows up. Is the problem on the whistleblower's side or the administration side? 

A picture would clarify my question.

**Comment by evilaliv3** [comment] 2015-11-05 21:34
The issue is related to the adminnistration side.

Basically the platform allows the admin to
- create questions templates
- reuse question templates in context for reference

what the platform is still missing completely (and this is why there is this issue that @fpietrosanti considered a bug) is the possibility for overriding texts of question templates in the context; (e.g. it is not possible having two different contexts, reusing the same question template for reference but with different text ovverrides but each of the texts of the field template require to be configured in the template and is global to all the context that use it.
Implementing this fix would require not simply a UI fix but a design of how to store personalized and keep track that the user provided them.

Here follows the screenshots that clarify the issue;

First the template configuration where the text is configurable (/#/admin/fields):
![screenshot from 2015-11-05 22 29 20](https://cloud.githubusercontent.com/assets/217034/10982305/d5382ad2-840c-11e5-8440-13b82da76ce1.png)


Second the context configuration where the template is used as reference and the editor of the hint is disabled (/#/admin/contexts):
![screenshot from 2015-11-05 22 30 05](https://cloud.githubusercontent.com/assets/217034/10982304/d1da5ebe-840c-11e5-9e7d-d232f937bccb.png)

**Comment by NSkelsey** [comment] 2015-11-06 16:46
This does specify the problem well. Be aware I do not have time in the coming days to address the issue.

**Comment by evilaliv3** [comment] 2015-12-07 01:12
this should be fixed since few time. i'm going to recheck it in the next days.

**Closed** 2016-01-02 21:48 UTC
Labels: C: Backend, C: Client, F: Internationalization, OTF-D4.2: Introduce configuration profiles (ready-made submission fields), OTF-D4: Easier Configuration, T: Bug, U: Admin
