### ISSUE TITLE
Issues with closing statuses 

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2608] opened 2019-06-28 09:48 UTC
Issue 1
**Current behavior**
The custom closing statuses do not appear in the submission status (no matter if it is in english or greek). It always  shows closed(closed) 
**Expected behavior**
It should show closed(malicious) for example.
![image](https://user-images.githubusercontent.com/23246886/60333559-09391b80-99a2-11e9-9ec0-a38ba3d49ab5.png)

Issue 2
**Current behavior**
This affects closing status  in a two language setup (greek english). when I enter a Greek translation for my custom english closing status, the english one does not appear at all. When I reenter the english text the greek is being replaced by the english text.

Using latest version of globaleaks on ubuntu 18.04LTS, updated chrome browser on windows 10

**Comment by evilaliv3** [comment] 2019-06-28 10:32
Thank you for reporting this @elbill

**Comment by evilaliv3** [comment] 2019-07-01 18:52
@elbill the issue is fixed and the patch will be released starting from the upcoming version 3.9.8

**Closed** 2019-07-01 18:52 UTC
Labels: C: Client, T: Bug
