### ISSUE TITLE
ConnectionError: HTTPSConnectionPool(host='acme-v01.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2213] opened 2018-03-12 12:50 UTC
Platform: 
Version: 3.0.10

requests.exceptions.ConnectionError A Connection error occurred.

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/https.py", line 552, in post
    regr_uri, tos_url = letsencrypt.register_account_key(Settings.acme_directory_url, accnt_key)

  File "/usr/lib/python2.7/dist-packages/globaleaks/utils/letsencrypt.py", line 26, in register_account_key
    acme = client.Client(directory_url, accnt_key)

  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 63, in __init__
    self.net.get(directory).json())

  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 627, in get
    self._send_request('GET', url, **kwargs), content_type=content_type)

  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 609, in _send_request
    response = requests.request(method, url, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)

  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)

  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)

  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)

ConnectionError: HTTPSConnectionPool(host='acme-v01.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fa4aab6e090>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

**Comment by evilaliv3** [comment] 2018-03-13 08:09
This error was caused by the unreliability of the website of LetsEncrypt.

A proper handling of this exception be to log and report the issue to the user without sending an exception.

**Comment by RalfOlaf** [comment] 2019-11-04 20:10
Hi,
I had the same message. In my case it was caused by IPv6.
After disabling IPv6 everything works fine.
So I extended my script by disabling IPv6, updating the certificates and the again enabling IPv6.

**Comment by mithlajkn** [comment] 2022-03-22 12:18
Iam also getting safe error

**Comment by evilaliv3** [comment] 2022-03-22 12:21
@mithlajkn  : Is this a new setup were you are trying to configure HTTPs or is this an old setup where you are trying to renew the certificate?

**Comment by mithlajkn** [comment] 2022-03-22 12:29
its a new setup..

**Comment by evilaliv3** [comment] 2022-03-22 13:00
I see.

Whould you please answer the following questions?

1. which domain are you tring to configure? (if you can say)
2. do you own it already?
3. have you already configured the dns for the domain to point to the ip of the server?
4. do you have a firewall in front of your server and is it configured to accept connections on port 80 and 443?

**Comment by mithlajkn** [comment] 2022-03-22 13:33
I owned the domain and configured the DNS to the IP of my server. firewall is disabled.  All other applications are working fine using my domain name and subdomains.

**Comment by mithlajkn** [comment] 2022-03-23 11:02
@evilaliv3 I think I am using an old image of letsencrypt to create the certificate.  So this URL acme-v01.api.letsencrypt.org is not valid now.

**Comment by evilaliv3** [comment] 2022-03-23 11:28
Ah, yes definitely. 

I did not understood it before. Probably you are not even using GlobaLeaks but you just found us due to the same error? 

I will close this in the scope of GlobaLeaks as this does not apply but please feel free to load possible questions if you have any in relation to our project.

Thank you.

**Closed by evilaliv3** 2022-03-23 11:28 UTC
Labels: T: Bug, C: Backend
