### ISSUE TITLE
Mention forum.globaleaks.org in admin landing page support options list

### ISSUE THREAD

**Issue by vodkina** [globaleaks/GlobaLeaks#1954] opened 2017-05-09 13:38 UTC
**Current behavior**
When configuring the installation in admin landing page, a list of options to obtain support is mentioned, but the forum is not included in it.

**Expected behavior**
When configuring the installation in admin landing page, include the forum (https://forum.globaleaks.org) has to mentioned.

**Steps to reproduce the problem or feature illustration**
Install globaleaks and configure it; the first page of admin interface is the landing page with the mentioned list

**What is the motivation or use case for changing the behavior?**
Making users aware of forum for obtaining support for the software.

**GlobaLeaks version (just run globaleaks --version):**
GlobaLeaks version: 2.67.4
Database version: 36

**Browser:**

- [x] All browsers
- [ ] Chrome:  v45.0.1
- [ ] Firefox: v55.0.1
- [ ] Safari:
- [ ] Mobile Chrome:
- [ ] Other: 
- [x ] Not Applicable

**Server Operating System and Version (if applicable):**
<!--
Indicate the server operating system and its version
e.g.: Ubuntu(14.04)
not applicable

**Client Operating System and Version (if applicable):**
not applicable

**Comment by NSkelsey** [comment] 2017-05-10 15:13
This is a valid point. I'd suggest a string in like:

`To find an answer to commonly asked questions use our [community support forum]`

**Comment by fpietrosanti** [comment] 2017-05-10 15:31
This ticket is duplicate of #1857

**Comment by NSkelsey** [comment] 2017-05-10 15:57
This is resolved in 52b7c05

**Closed by NSkelsey** 2017-05-10 15:57 UTC
Labels: C: Client
