### ISSUE TITLE
Questionnaire Identity section set as single line field

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#3156] opened 2022-01-28 15:40 UTC
**Describe the bug**
When "whistleblower_identity" template is set, in the questionnaire backend it's shown as a single line field, so is not possible 

- to choose to submit or not the identity to custodian 
- to set texts to show on negative withleblower's answers and negative confirm text

**To Reproduce**
1. Go to questionnaires and build an identity section
2. Click on templates question and choose whitleblower default identity template
3. A single line field is set and its not possibile to set the options above 

**Expected behavior**
In the identity template backend should be possible to set the options above

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser firefox 96, chrome 97

**Smartphone (please complete the following information):**
-

**Additional context**
GL version 4.7.6

**Comment by evilaliv3** [comment] 2022-01-28 17:34
Thank you for reporting this @larrykind , i will recheck this  issue and get sure this is fixed within the next minor release.

**Comment by evilaliv3** [comment] 2022-01-28 18:14
@larrykind: i just verified and this is actually not a bug.

Let me explain what happened.

- The whistleblower identity has been always shown named "single line field" but actually i agree that this is confusing
- If the whistleblower identity field is used and in the system there is at least a Custodian user in status enabled the feature that subjects the identity visualization to the custodian authorization will be automatically enabled.
- The option for providing a text to the user in case of negative answer has been removed as considered not useful; What is your experience?

**Comment by larrykind** [comment] 2022-01-31 09:04
thanks @evilaliv3 for explanations.

- no problem with "single line field". It's a bit confusing, I just thought it could be a flag for a a buggy behaviour.
- ok, thanks for the clarification. I thougt It could be derived from previous point
- About both the texts for "negative answer" and "continue for anonymous report", I actually found them very useful cause Italian laws will grant wistleblower just in case he/she declares identity data. Both these two text fields are used by me to warn whistleblowers about that, so my request is to restore them if possible. About this, if the second radio to "continue for anonymous" is without ext wo show, my suggestion is to not show the radio at all.

**Comment by evilaliv3** [comment] 2022-01-31 10:06
Thank you @larrykind 

Agreed to restore the possibility to show a text for the negative answer. Thank you for the feedback.

**Comment by evilaliv3** [comment] 2022-01-31 13:12
@larrykind : After a complete evaluation we have considered to add again the option "Text shown upon negative answer" but without the options "Prompt confirmation upon negative answer" and "Text shown upon confirmation".

This in fact should be enough to be able provide the user a message that clarify the aim of collecting the identity information without adding the more compliated interface and the set of options we had before.

**Comment by evilaliv3** [comment] 2022-01-31 14:43
Functionality restored with commit: https://github.com/globaleaks/GlobaLeaks/commit/69857f931e81b3556855bce578aa8e40d17ad5cc

The interface will look like this:
![Screenshot from 2022-01-31 15-39-33](https://user-images.githubusercontent.com/217034/151813792-1ccbca3c-75b9-4e58-9abd-b95d5d58f893.png)

The feature will be included starting from minor release 4.7.8

**Closed** 2022-01-31 14:43 UTC
