### ISSUE TITLE
False email notification informing of a new message from WB

### ISSUE THREAD

**Issue by SylvainFPU** [globaleaks/GlobaLeaks#2555] opened 2019-04-17 08:40 UTC
**Current behavior**

**Expected behavior**
Some users at PubLeaks report that they receive sometime an email notification from the platform informing them about a new message (potentially from a whistleblower). They rush there but there is nothing new. No new message.

**Steps to reproduce the problem or feature illustration**

**What is the motivation or use case for changing the behavior?**
It is possible that the message is a message from others recipients and that there is a bug that notify them incorrectly

**GlobaLeaks version:**
3.6.44

**Browser:**
Tor

**Comment by evilaliv3** [comment] 2019-04-18 18:23
Thank you for reporting this @SylvainFPU.

I made some tests and i'm currently not able to reproduce the issue to confirm the bug.

Let's leave the ticket open till someone will be able to replicate the situaton

**Comment by evilaliv3** [comment] 2021-12-02 20:13
Closing as probably outdated.

**Closed by evilaliv3** 2021-12-02 20:13 UTC
