### ISSUE TITLE
Afrileaks 001 - login page will offer receiver name in a selectbox

### ISSUE THREAD

**Issue by vecna** [globaleaks/GlobaLeaks#1071] opened 2015-01-02 23:02 UTC
Due to the fact that:

  * some journalists make mistake remembering email address
  * the email address has not to be leaked via API
  * the email address has not to be kept secret
  * the password bruteforce protection are already in place

The issue here proposal will make easier the login process for the journalist. Instead of the username, will just select the display name associated to her/him (and insert password).

In order to do so, the login can support UUIDv4 as username, having a dedicated login_type (in order to impact least as possible in authentication.py)

This ticket has been already discussed with @evilaliv3 as an urgency. Will probably require a release for the 10 of January.

**Comment by evilaliv3** [comment] 2015-01-03 09:22
this whould involve changing also the login page giving to it a tabbed view where one can select a tab for Receiver Login (will be the default) or for the Admin.

depending on a DB setting: receiver_login_type "STANDARD|DOMAINMAIL|SELECTION" on the receiver login we will show one of this three different possibilities:
1) standard login (it's the current one)
2) domain mail, the login as now but where the "@domain.tld" is altready there
3) selection, where the receiver view it's name and have simply to insert a password.

**Comment by evilaliv3** [comment] 2015-01-03 09:31
i'm not totally sure that 3 will simplify the workflow as i think also for afrileaks.
this comment is based on two ideas:

1) every website has a login. if a receiver is not skilled enough to remember a login and a password for me he is not skilled enough to join the initiative and should not be not be admitted on the platform. this is also in the thinking of afrileaks project were they decided to do assesment of receiver trainings.

2) adding this preselection will reduce the complexity of the current threat model of the login.
 where the login username will become know and should be reflected on password complexity. for this reason also i'm against this change if we dont't increase the password complexity (that obviously has some usability drawback more thant the change you are proposing.

i would like also others dev to express their ideas: @hellais  @mmaker  @fpietrosanti 

 then by today i could be available to implement it. i prefer to do this as eventually i already have a clear idead of know to implement it in the glclient.

**Comment by fpietrosanti** [comment] 2015-01-03 10:36
This ticket is a duplicate of #1048

**Comment by vecna** [comment] 2015-01-03 12:40
no @fpietrosanti we've think about. #1048 is about putting a default domain address, this is about show a list of receiver (quite similar to the submission page) where the receiver just select the logo/name of the initiative and put the password.

admin has to login in a different page.

**Comment by vecna** [comment] 2015-01-03 12:46
@evilaliv3 honestly no security downgrade is there. the username has never to be considered secret for security purpose. we just prefer consider the email "private" in order to reduce phishing-like attacks. the current password security has a lots of entropy bit, and the current "password wrong slow down" will cripple any bruteforce. I'm just tring to reduce the amount of thing that journalists have to remember.

also doing so, the step to be remembered remain 4:

  * keypassx database file,
  * when PGP password has to be put (has a cache, is another reason of confusione),
  * where take the PGP password,
  * where take the Globaleaks login password,

and probably/luckily can be reduced with a wide keypassx configuration.

**Comment by evilaliv3** [comment] 2015-01-03 13:15
ok anyhow also if we do this i would prefer implementing a small interface
using simply a select box and not a complex one with big boxes like in
receiver selection box.

what do you think? i find it really more usable and less confusing also in
situation like these where we have a lot of receivers.

**Comment by evilaliv3** [comment] 2015-01-05 11:48
Preview of the new simplified receiver login interface:
![screenshot from 2015-01-05 12 45 58](https://cloud.githubusercontent.com/assets/217034/5612665/04233fe0-94d9-11e4-9636-8f6a468a5a95.png)
![screenshot from 2015-01-05 12 46 12](https://cloud.githubusercontent.com/assets/217034/5612663/04210108-94d9-11e4-8437-519f57a09e3b.png)
![screenshot from 2015-01-05 12 46 25](https://cloud.githubusercontent.com/assets/217034/5612664/042296ee-94d9-11e4-9dff-0feaad46b086.png)

\cc @vecna @hellais @mmaker @fpietrosanti

**Comment by vecna** [comment] 2015-01-05 11:50
as you feel

**Comment by evilaliv3** [comment] 2015-01-05 11:51
Preview of the new receiver login interface:

![screenshot from 2015-01-05 12 50 32](https://cloud.githubusercontent.com/assets/217034/5612697/9349ee9e-94d9-11e4-87a0-f70d3e02af73.png)
![Uploading Screenshot from 2015-01-05 12:50:37.png . . .]()
![Uploading Screenshot from 2015-01-05 12:50:46.png . . .]()

**Comment by fpietrosanti** [comment] 2015-01-05 11:55
The login button should be highlighted only when the password being inserted, match the password  strength policy set by the node.

The title of the page shall move from "Login" to "Receiver Login"

The user should be informed of bad password attempt, clearly explaining that there is a lockout policy, that after another X wrong password, he will be locked out and will need to ask the admin to reset his password.

**Comment by evilaliv3** [comment] 2015-01-05 11:58
1) point one has been already done (look at the screenshots)
2) i'm appling point 2
3) lets move point 3 to a different improval ticket related to password lockout that is still not implemented. i'm going to ticketize them all as part of my schedule by today

**Closed** 2015-01-09 15:22 UTC
Labels: F: AdopterRequest, OTF-D5.2: Make a major re-work on UX-design following a UX-consultancy and UX-usability improvement, OTF-D5: Usability Improvement, Type: enhancement, U: Receiver
