### ISSUE TITLE
Problems opening site in Windows Explorer

### ISSUE THREAD

**Issue by schris-dk** [globaleaks/GlobaLeaks#3085] opened 2021-11-03 07:44 UTC
I've been trying to open one of our testpages in Internet Explorer - and it hangs

![image](https://user-images.githubusercontent.com/70965554/140024157-f7b673b3-20b9-4bd2-bea2-da92b02a04fe.png)

OS is Win 10 cf. the picture 

Is this a known bug?

/Soren

**Comment by schris-dk** [comment] 2021-11-03 07:56
Just been trying to open a different production site in 2 different Internet Explorer versions - and they fail - This is NOT good ....

**Comment by evilaliv3** [comment] 2021-11-03 10:20
Thank you @schris-dk for reporting this. This currently a not known bug.

Which is the version of Internet Explorer?

**Comment by evilaliv3** [comment] 2021-11-03 10:44
Thank you @schris-dk, after re-testing this i confirm that this appear to be a regression caused by this line https://github.com/globaleaks/GlobaLeaks/blob/devel/client/app/js/directives.js#L6 and introduced in commit https://github.com/globaleaks/GlobaLeaks/commit/8f9894ec7e621ccc422ab8a2c5522bdd1dc98a49

The bug was introduced in release 4.2.13 on the 4th of August.

**Comment by evilaliv3** [comment] 2021-11-03 12:13
The fix will be included in release 4.4.6

**Closed** 2021-11-03 12:12 UTC
Labels: T: Bug, C: Client

**Comment by schris-dk** [comment] 2021-11-04 06:31
Super - Thnx :-)
