### ISSUE TITLE
Whistleblowers can not upload new file attachments after submission 

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2967] opened 2021-01-27 09:20 UTC
When whistleblowers try to upload new file attachments in the chat environment, the files seem to be uploading but never appear in the case management. This is hard to spot, found out during testing for a new system.

**GlobaLeaks version:**
 v4.1.13

**Browser:**
chrome

**Server Operating System and Version (if applicable):**
ubuntu 18.04

**Comment by elbill** [comment] 2021-01-27 09:51
In addition to my previous issue report when a whistleblower uploads a new file attachment, the square thumbnail  representing the file is blank unless it is a picture. Is this normal?

**Comment by evilaliv3** [comment] 2021-01-27 14:10
Thank you @elbill i confirm that this seems to be a regression introduced by commit https://github.com/globaleaks/GlobaLeaks/commit/3b3ae9d6c77df50736d1114ec37108dce4bed8a3#diff-3534bfebc28d5488a6639b5a4af93df05cbb6435213a75975ccba51f3c46a8c1 and present since release 4.1.10.

As for the thumbnail actually there is no way in HTML to show a preview except for images.

**Comment by evilaliv3** [comment] 2021-01-27 17:30
Fixed and fix released in version 4.1.15

**Closed by evilaliv3** 2021-01-27 17:30 UTC
Labels: C: Client, T: Bug
