### ISSUE TITLE
Migration 34 failure in relation to new fields check constraints

### ISSUE THREAD

**Issue by infosquatter** [globaleaks/GlobaLeaks#1759] opened 2016-09-08 17:56 UTC
Updating DB from version 32 to version 33
Migrating table:
 * Anomalies [#0]
 * ArchivedSchema [#10]
 * ApplicationData [#0]
 * Comment [#3]
 * Context [#1]
 * CustomTexts [#0]
 * Field [#63]
Failure while migrating table Field: constraint failed 
constraint failed

**Comment by evilaliv3** [comment] 2016-09-08 23:09
Thanks for reporting @infosquatter 

the issue is a known issue just discovered few days ago on a deployment and i implemented the patch in the last days: https://github.com/globaleaks/GlobaLeaks/commit/eac381072b39d948badefd6c26b9c29188225b3b

i'm about now oing to reissue a stable release including this fix only.

**Comment by evilaliv3** [comment] 2016-09-08 23:55
https://github.com/globaleaks/GlobaLeaks/commit/d494aac720a7cecdfe745b25dc90c085668f5809

here you go @infosquatter; release 2.63.5 is out and fix only this issue.
you should be able to fix simply doing: ```apt-get update && apt-get install globaleaks```

**Comment by kyrylkov** [comment] 2016-09-24 14:07
@evilaliv3 The issue is back:

```
Updating DB from version 33 to version 34
Migrating table:
 * Anomalies [#0]
 * ArchivedSchema [#32]
 * ApplicationData [#1]
 * Comment [#0]
 * Context [#2]
 * CustomTexts [#0]
 * Field [#146]
Failure while migrating table Field: CHECK constraint failed: check_parent
```

**Comment by NSkelsey** [comment] 2016-09-24 14:45
@kyrylkov thanks for reporting. This a tricky one to reproduce. @kyrylkov could you give a provide a version of the software that you originally started with?

**Comment by kyrylkov** [comment] 2016-09-24 14:48
@NSkelsey 2.63.1

**Comment by NSkelsey** [comment] 2016-09-24 15:48
@kyrylkov its unlikely that a fix will exist for you today.

Can you post the output of `globaleaks.log` after the restart and the attempt at the update?

**Comment by kyrylkov** [comment] 2016-09-24 15:53
@NSkelsey the latest log record in `globaleaks.log` is from 2016-09-19 06:25:18

**Comment by NSkelsey** [comment] 2016-09-24 16:26
@evilaliv3 please take a look at `d40c18d` I believe it addresses the issue, but it is a bit aggressive in dropping fields that we may actually want to keep around.

**Comment by evilaliv3** [comment] 2016-09-24 18:51
Yes i do not think this a regression, but simply that my fix was not considering all the situations.

Your patch seems good to me @NSkelsey, i will reanalyze a second time and eventually complete it 

i do not consider it aggressive at all because the anomalous fields are fore sure dead fields caused by deletions of parents, and are anyhow unrechable by the admin since time.
and greate you implemented also a test for the fix.

@kyrylkov i think that by tomorrow the issue will be fixed.
i will notify you on the ticket when the package will be available.

**Comment by evilaliv3** [comment] 2016-09-25 09:57
@NSkelsey i confirm that the patch you developed work and the retesting is perfect.

I've fixed it's integration and i will issue the package by today.

**Comment by evilaliv3** [comment] 2016-09-25 14:30
@kyrylkov you find the package 2.63.3 out if you want to try to updating

**Comment by kyrylkov** [comment] 2016-09-25 16:49
@evilaliv3 you mean 2.64.3?  it still doesn't work.

**Comment by NSkelsey** [comment] 2016-09-25 20:02
@kyrklkov you are stuck in a very funky spot now, but I think I have a solution. Your system somehow made it to 33 without throwing the constraints that should have protected from this exact situation. Sorry. If you know any SQL or have a friend that does you can quickly get into the DB and just drop the rows that fail the constraint.

@evilaliv3 we can move `migrate_Field` that drops these fields to migration 34 and do the enforcement there. This will have no effect on anybody moving through older migrations and should resolve the issue. See `41abffd`

**Comment by kyrylkov** [comment] 2016-09-26 12:26
@NSkelsey could you post example commands?

**Comment by evilaliv3** [comment] 2016-09-26 12:48
@kyrylkov: we just debugged the issue and we got the full understanding of why it is already present for your setup.

I'm now retesting the fix and i will write you in an hour when i will be out.

thanks for the patience.

**Comment by evilaliv3** [comment] 2016-09-26 14:18
@kyrylkov: the bugfixed release is out, could you please see if the migration now works with you?

**Comment by kyrylkov** [comment] 2016-09-26 16:38
@evilaliv3 This time the upgrade went fine

**Closed** 2016-09-26 16:41 UTC
Labels: C: Backend, T: Bug
