### ISSUE TITLE
Provide a statistics on how many Whistleblowers get back with their receipt

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1776] opened 2016-09-27 08:20 UTC
Discussing with Giorgio of TI-it with their ALAC platform, we've been chatting on the fact that many whistleblowers doesn't seems to get back on his Tip.

Basically the need we've been discussing is to notify the Whistleblower back when there is a new message for him like the features described at #1157 and #898 that are more and more a requirement.

Before going that path, with all the privacy implication that it means requiring proper awarenes text and configuration, this ticket is to provide a statistics on how many Whistleblowers get back with their receipt and how many just don't log in back.

This ticket is to display in the Receiver page and in the Admin page a statistics of all the current and previous Tip (also the deleted ones) on:
- the amount of Tip where the whistleblowers logged in back vs. not
- the amount of time whistleblower logged in back
- the amount of time that passed since the first time the whistleblower logged in

Additionally on the Tip page the Receiver should be able to see if the Whistleblower ever logged in back and how much time passed since the last time he logged in on that Tip.

**Comment by NSkelsey** [comment] 2016-09-27 08:46
I can see this as a simple visualization for tips of a given context.

A pie chart of submissions created, visitors to the submission page, and returning whistleblowers that use the platform.

**Comment by evilaliv3** [comment] 2017-05-16 09:06
Closing as duplicate of: https://github.com/globaleaks/GlobaLeaks/issues/1188

**Closed by evilaliv3** 2017-05-16 09:06 UTC
Labels: T: Enhancement, X: TransparencyIT
