### ISSUE TITLE
issues in whistleblower's Identity template with files

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#3157] opened 2022-01-28 16:27 UTC
**Describe the bug**
If an identity template contains a file request I would to notice the following issues:
- if the file is filled in whistleblower's backend, and file is uploaded after the rest of the fields, send button will be disabled until all the fields under the file are filled again.
- file uploaded in the identity section in whistleblower's backend cannot be deleted before to send, red  cross to delete is not there. Only way to do it is to reload the page.

**To Reproduce**
1. Fill a questionnaire with optional identity data declaration and send a report as anonymous
2. Access to the report after it is sent
3. Fill the identity form field but upload the file after the other fields
4. Upload the file -> send button is disabled / it is not possible to delete the file

**Expected behavior**
Send button should be enabled after check on mandatory fields in the context of delayed identity declaration , and delete butto for file upload should be there

**Screenshots**

![identity_after_tip](https://user-images.githubusercontent.com/61267901/151584207-67dc2b82-6d9e-4811-a822-8b4206be8709.JPG)

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser firefox 96, chrome 97

**Smartphone (please complete the following information):**
-

**Additional context**
GL version 4.7.6

**Comment by evilaliv3** [comment] 2022-01-28 17:39
Thank you for reporting this and with this great detail @larrykind, i will look into this and get sure the issue is solved within the next minor update.

**Comment by evilaliv3** [comment] 2022-01-31 16:57
@larrykind: Actually after re-reading this ticket i can already argument on the two issues reported on this ticket:
- The first is probably a bug and will be addressed by me within this ticket
- The second is a limitation of the current implementation that applies both on the whistleblower identity and to the additional questionaire; Both the two features does currently upload the file as soon that the file is loaded onto the system. I condiser that we should work on this by preventing any file upload till the user click the button send. This is why you do not find the possibility to remove the file. In your ticket description you say that a fix is to reload the page, but actually if you verify well, you will find that the file has been loeded anyway. This is due to the fact that both the two feature were financed and implemented in projects not requiring  file uploads so this issue was not identified. I consider that in general could rework the file upload functionality also for the initial submission and upload the files only at the end of the submission when users will click submit.

**Comment by evilaliv3** [comment] 2022-02-08 17:37
Update:

With commit https://github.com/globaleaks/GlobaLeaks/commit/69822a0d31ca8f53e395af3061b36f8ba99b6475 the system now will require a confirmation for any file upload.

Specifically:
- upload during initial submission: files are uploaded only when the user click submit at the end of the questionnaire
- upload on existing submissions: files are uploaded requiring a confirmation by the user
- upload on the additional questionnaire feature: files are uploaded when the user click submit at the end of the questionnaire
- upload on whistleblower identity feature: files are uploaded when the user complete the identity questionnaire

**Closed** 2022-02-08 17:37 UTC
Labels: T: Bug, C: Client
