### ISSUE TITLE
Globaleaks 2.72.3 not visibile su Google Chrome in HTTP

### ISSUE THREAD

**Issue by alepartenza** [globaleaks/GlobaLeaks#2088] opened 2017-09-20 14:45 UTC
Ho appena installato l'ultima versione di Globaleaks 2.72.3 ma non riesco a visualizzare la pagina su Google Chrome. Il problema non c'è sugli altri browser (Firefox, Edge, Explorer), dove è perfettamente visibile.

GlobaLeaks version: v2.72.3
Browser: Chrome 61.0.3163.91
Server Operating System and Version (if applicable): Ubuntu(16.04)
Client Operating System and Version (if applicable):Windows 10

**Comment by alepartenza** [comment] 2017-09-20 15:26
Dopo aver abilitato il HTTPS con Let's Encrypt è tornato ad essere visibile.

**Comment by evilaliv3** [comment] 2017-09-20 17:32
Grazie @alepartenza per aver riportato l'errore. Indagheremo quanto prima per risolvere entro il prossimo rilascio.

Quando non funzionava, stavi accedendo tramite IP o via nome di dominio?

**Comment by evilaliv3** [comment] 2017-09-20 19:14
Non riesco a riprodurre l'errore.

@alepartenza: potresti gentilmente se sei in grado di riprodurlo vedere se nella console javascript del browser ti viene segnalato qualche errore? Su chrome la attivi con ctrl+shift+j.

grazie!

**Comment by alepartenza** [comment] 2017-09-21 07:00
Avevo provato sia da IP che da nome di dominio, con lo stesso risultato. Avevo aperto anche la console javascript che non segnalava alcun errore. Stranamente aprendo il sorgente pagina, il codice html era visibile!

**Comment by NSkelsey** [comment] 2017-09-22 15:32
I believe I have identified the issue.

The latest versions of chrome and chromium  -- at least mine > `60.0.3` -- require that window.crypto.subtle functions be loaded in a defined `SafeContext`. I can't find the changelog to confirm the missing API, but from a remote host name I can confirm in HTTP `window.crypto.sublte ==
undefined` while in HTTPS `window.crypto.subtle` is defined.

This behavior is documented in the WC3 [Secure Context specification](https://www.w3.org/TR/secure-contexts/#ancestors) and we haven't noticed because localhost is considered one of these contexts while external hosts served over http are not. Further the chromium project specifically talks about this choice on their [wiki](http://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features).

The solution would be to drop [these checks ](https://github.com/globaleaks/GlobaLeaks/blob/v2.72.4/client/app/index.html#L285-L290)in the frontend, because we actually don't use these functions as the check in question was added to anticipate the integration of browser crypto . . .  Or take an action like warning the user that they are in an insecure context.

**Comment by NSkelsey** [comment] 2017-09-22 15:33
Notice the `[SecureContext]` tag in the web crypto [spec](https://www.w3.org/TR/WebCryptoAPI/#crypto-interface).

**Comment by evilaliv3** [comment] 2017-09-23 15:08
I confirm that the issue is based on https://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features spec.

No solution exists to the issue but as we could not cut of Chrome from the supported browser with @fpietrosanti we have identified a possibile minimal patch that would allow to use Chrome in http during the first development stages of the platform.

The idea is to disable the proof of work requirement in case the user using the application is a chrome user accessing via HTTP in a not Tor connection.

I'm picking up the implementation of a PoC for this that we could test and evaluate.

**Comment by evilaliv3** [comment] 2017-09-23 15:41
In the meantime that we discuss how to roperly solve this specific condition for chrome i've fixed the visualization of the not compatible error that was currently not shown.

**Comment by evilaliv3** [comment] 2017-09-25 11:50
The fix has been integrated in version 2.72.5

**Closed by evilaliv3** 2017-09-25 11:50 UTC
Labels: C: Client, T: Bug
