### ISSUE TITLE
GlobaLeaks integrated mode does not work when a .onion integrate a .onion

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1311] opened 2015-06-24 07:53 UTC
GlobaLeaks integrated mode does not work when a .onion integrate a .onion .

Up to now it has only be tested with https-site including a https-tor2web-exposed-globaleaks .

It has now been verified that once integrating GlobaLeaks from a .onion in a .onion it does not work properly, as per example on URL:
 http://hokioisec7agisc4.onion/contact-details/iframe_test_sd87gausjihfais.php

The error given is "Error" with no further specification.

By firing Web Developer console it's possible to see that /submission is giving 403 error:
![screen shot 2015-06-24 at 9 52 42 am](https://cloud.githubusercontent.com/assets/770363/8325094/e198f362-1a56-11e5-9dfb-c32668648617.png)
##

**Comment by evilaliv3** [comment] 2015-06-24 16:52
the issue is not related to GLBackend but to GLClient, and verify only on the Tor Browser (probably firefox), while Chrome+Privoxy works well.

**Comment by fpietrosanti** [comment] 2015-06-24 18:32
From IRC conversation on #tor-dev sounds like that this ticket cannot be fixed, until we get rid of using Cookie in GlobaLeaks, due to https://trac.torproject.org/projects/tor/ticket/3246

naif
7:12 mikeperry: do you know if there are some iframe specific restrictions on Tor Browser, compared to normal Firefox? As we found out that a .onion site, embedding a GlobaLeaks form residing on another .onion site, is not working properly on TBB (but it works on Chrome+Tor+Privoxy)
arthuredelstein
8:15 naif: What about the embedded iframe is not working properly?
naif
8:17 arthuredelstein: that's the problem https://github.com/globaleaks/GlobaLeaks/issues/1311 . Sounds like Tor Browser, when we are embedding GlobaLeaks in an iframe, does not send back a session cookie (While it works on stock firefox on https + Chrome/Tor/Privoxy)
arthuredelstein
8:20 naif: Currently third party cookies are disabled. I think (though I'm not sure) that a cookie in an iframe from another domain will be considered third party.
arthuredelstein
8:20 I mean if the cookie and iframe are from domain B.com, and the parent page is A.com, then the cookie will be blocked.
naif
8:21 arthuredelstein: but communication "within the iframe" should be untouched
8:23 naif: Unfortunately that's not the case right now. There is a ticket for a better implementation: https://trac.torproject.org/projects/tor/ticket/3246 but that hasn't been done yet.
zwiebelbot
8:23 (notice) tor#3246: Isolate HTTP cookies according to first and third party domain contexts - https://bugs.torproject.org/3246
arthuredelstein
8:26 naif: The reason for blocking third parties, is that many advertisers use iframes and cookies to track people across domains. Sorry this is breaking your site!
naif
8:27 arthuredelstein: mmm i see, do you think that with the new Tor Browser based on latests version of Firefox is going to work?naif
8:27 arthuredelstein: well, we shall change the integration logic to JS-widget + CORS rather than iframe
arthuredelstein
8:27 naif: It will have the same problem until we implement #3246 or mozilla does.
8:27 naif: You could use window.localStorage instead. That is correctly isolated by url bar domain, more like #2346.
zwiebelbot
8:27 (notice) tor#2346: Failing to write state file means you try every second - https://bugs.torproject.org/2346
arthuredelstein
8:28 Er, #3246.
8:28 Or window.sessionStorage
8:29 n8fr8 [~n8fr8@wrls-140-247-0-135.wrls.harvard.edu] entered the room.
naif
8:29 arthuredelstein: well yes, the *final solution* on GlobaLeaks is to a) Move away from using Cookie b) Implement XSRF with double check HTTPHeader+JSONParameter c) Provide integration without using iFrame but JS-Widget + CORS
arthuredelstein
8:30 Sure. I just thought window.sessionStorage is a more-or-less drop-in replacement for session cookies.
8:31 I'm not familiar with XSRF but it sounds evil
8:31 amieiro [~amieiro@tor-exit.squirrel.theremailer.net] entered the room.
naif
8:31 arthuredelstein: We need a double-check on two different channel for anti-XSRF, now it's Cookie+HTTP-Header, tomorrow will be JsonParameter+HTTP-Header (so we get rid of cookie)

**Comment by evilaliv3** [comment] 2021-01-20 12:02
Closing as deprecated; see https://github.com/globaleaks/GlobaLeaks/issues/1270 for research purposes

**Closed by evilaliv3** 2021-01-20 12:03 UTC
Labels: C: Client, T: Bug
