### ISSUE TITLE
During the upgrade some question configurations seems to be resetted

### ISSUE THREAD

**Issue by ktmrev** [globaleaks/GlobaLeaks#2588] opened 2019-06-12 10:34 UTC
**Current behavior**

Configuration of the whistleblower identity feature are lost during softare upgrade.

This happened specifically on the option "Subject answer visibility to the autorization of the custodian"

**Expected behavior**

During the software update it is expected that every user configuration is preserved.

**Steps to reproduce the problem or feature illustration**

**What is the motivation or use case for changing the behavior?**

**GlobaLeaks version:**

3.9.5

**Browser:**

Chrome 74.0.3729.169

**Server Operating System and Version (if applicable):**
 
Ubuntu (18.04.2)

**Client Operating System and Version (if applicable):**

Windows 10

**Comment by evilaliv3** [comment] 2019-06-12 12:05
Thank you for reporting this @ktmrev.

The feature is currently under development and it is likely that migration scripts are still not fully implemented.

i will try to recheck it in the next days to get proper understanding of the situation

**Comment by evilaliv3** [comment] 2019-06-12 21:19
Actually the bug is generic and seems to be a regression on the reset of the attributes of the questions.

The bug seems have been always present since commit: https://github.com/globaleaks/GlobaLeaks/commit/ebbe064702

**Comment by evilaliv3** [comment] 2019-06-13 09:40
@kituser the bug is now fixed and the fix included in release 3.9.6

**Closed** 2019-06-13 09:40 UTC
Labels: C: Backend, T: Bug
