### ISSUE TITLE
Score column does not show in the recipient interface

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2831] opened 2020-04-26 08:34 UTC
**Current behavior**
Score does not show in the recipient interface. When score feature is deactivated and then reactivated (on purpose) then score shows again. After a while when I relogin the score column disappears. 

**Expected behavior**
Would expect the score column to show when scoring is activated.

**GlobaLeaks version:**
4.0.17

**Server Operating System and Version (if applicable):**
ubuntu 18.04

**Client Operating System and Version (if applicable):**

**Comment by evilaliv3** [comment] 2020-04-28 15:58
Thank you @elbill 

At the current time i'm not able to reproduce this issue. Whould you please re-test it and let us know if you still verify it? 

The score is enabled a platform level and the configuration apply in any interface. The configuration could be subject to cache and it is likely that when you experienced the issue you disabled the feature but the cache was still considering it enabled or viceversa. Maybe this is the case?

Thank you!

**Comment by elbill** [comment] 2020-04-28 16:28
I'm pretty certain. The checkbox is checked but score nowhere to be seen. Last column is preview. I have tried from edge as well and get same results. I get the same result in a .try.globaleaks.org  so I'm pretty sure there is nothing wrong with my configuration. It may come back when I uncheck, save and check (not always) and after 1-2 logins it vanishes.

**Comment by elbill** [comment] 2020-04-28 16:49
![Reports - Google Chrome 28_4_2020 7_41_47 μμ](https://user-images.githubusercontent.com/23246886/80514116-c01e7300-8988-11ea-8767-084a376bdc39.png)
![Reports - Google Chrome 28_4_2020 7_41_58 μμ](https://user-images.githubusercontent.com/23246886/80514125-c3196380-8988-11ea-9c88-429c61fbc0f0.png)

Log out and login
![Reports - Google Chrome 28_4_2020 7_43_06 μμ](https://user-images.githubusercontent.com/23246886/80514577-5fdc0100-8989-11ea-94f2-6cc5571e1cb6.png)
![Reports - Google Chrome 28_4_2020 7_43_44 μμ](https://user-images.githubusercontent.com/23246886/80514583-62d6f180-8989-11ea-803c-af243837c662.png)

**Comment by evilaliv3** [comment] 2020-04-29 15:21
I see. So it seems to disappear only on the page of the list of the submissions. Do you confirm?

**Comment by elbill** [comment] 2020-04-29 17:32
I confirm. It is only the list of sumissions

**Comment by elbill** [comment] 2020-05-04 09:04
@evilaliv3 just an update that the problem persists after updating from 4.0.17 to 4.0.18

**Comment by evilaliv3** [comment] 2020-05-05 18:22
Nothing changes automagically @elbill ! ;)

**Comment by evilaliv3** [comment] 2020-05-05 18:29
Fixed! The fix will be included starting from release 4.0.19

**Closed** 2020-05-05 18:29 UTC
Labels: C: Client, T: Bug
