### ISSUE TITLE
Feature do not expose user's names

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2807] opened 2020-04-06 07:54 UTC
Has the feture do not expose user's names been removed in v4? Cant find it in advanced settings.
How can one hide recipient identity and replace it with project name or anything else?

V 4.0.8 on Ubuntu 18.04

**Comment by evilaliv3** [comment] 2020-04-06 07:58
@elbill: In version 4 we added a Pseudonym functiality that make it possible to configure for every user a pseudonym.

This has deprecated the explicit functionality of not exposing user nams.

Do you consider woth it to keep a general setting for this as well?

**Comment by elbill** [comment] 2020-04-06 08:05
Thanks @evilaliv3 . Having a  a general setting that would replace the user names and pseudonyms with project name or something configurable would be useful.

**Comment by evilaliv3** [comment] 2020-04-06 09:36
Thank you for the feedback, we will evaluate to add this in next development.

Current implementation is technically more simple and safe as the public name is always removed in any interface but we will evaluate how to implement a similar solution fo this.

The code was changed here: 4787dce3762fc52c611412c7a73d037e162e06c2

**Comment by evilaliv3** [comment] 2020-05-06 21:27
Feature re-added @elbill and it will be released with 4.0.19

I've considered to make this the default of the application but for making this change i would need to wait for the next database version. This is the reason i will keep this ticket open till release 4.1.0

**Comment by elbill** [comment] 2020-05-07 12:59
@evilaliv3 I agree with this approach. It will keep you on the safe side (not exposing recipient identity) without having to dig into settings when not very familiar with a globaleaks installation.

**Comment by evilaliv3** [comment] 2020-05-15 22:31
@elbill: The feature has been reimplemented and included in 4.0.19.

The the default settings will implemented in the future when will be released 4.1.X

**Comment by elbill** [comment] 2020-05-16 07:22
@evilaliv3 thanks. Has there been some change in the landing page in 4.0.19? Loggos look huge, twice as big. Should I report it as an issue?

**Comment by elbill** [comment] 2020-05-16 09:46
@evilaliv3 I see. You have changed the way logo sizes appear, so larger logos can be accomodated. This is no problem, I may have to resize some of my logos.

**Comment by evilaliv3** [comment] 2020-05-16 10:40
Thank you @elbill.

Yes we are rebranding the whole application and trying to apply uniform
choices. If you have patches you want to propose to preserve part of the
previous css configurations please let me know because we are still trying
to understand what is best for users.

Please consider keep every topic on a separated ticket

**Comment by evilaliv3** [comment] 2020-05-16 13:08
@elbill: Actually do not mind to the logo size, i just noticed the regression to iwch you are probably referring and i will get sure the size remain the same.

**Closed** 2020-09-20 08:03 UTC
